DFE-Digital/teaching-record-system

.github/workflows/build.yml
README.md
docs/running-functional-tests.md

Moves the docs on running the functional tests into the docs folder so it will be available in the tech docs site.
Also amends the build pipeline so it will not be triggered when only the docs have changed.
N/A

Move functional tests docs into docs folder

---

.github/dependabot.yml

Sets up dependabot for the API and for GitHub actions.
By updating dependencies regularly we stay on top of security updates and reduce the chance of pain that comes with larger, less frequent dependency updates.
List any dependencies that are required for this change.
N/A

Add dependabot config for the app itself and GitHub actions

---

.github/workflows/build.yml
src/DqtApi/Program.cs
src/DqtApi/Startup.cs

Adds the OWASP API scan to our CI pipeline.
Also fixes a few low priority warnings that came out of the scan (security & caching headers).
https://trello.com/c/94Sj3Sta/80-add-owasp-api-test-to-ci-pipeline

Add OWASP API Scan to build pipeline

---

docs/environment-setup.md
src/DqtApi/Configuration/ConfigurationBuilderExtensions.cs
src/DqtApi/Configuration/EnvironmentVariableJsonConfigurationSource.cs
src/DqtApi/Program.cs
terraform/api-app.tf

Use a single JSON-encoded Key Vault secret for storing application config.
This removes the need for some complex Terraform gymnastics mapping multiple Key Vault secrets through to the app by convention. It should also prevent a mass of secrets accumulating in Key Vault and make them simpler to manage.
https://trello.com/c/evDyTEmq/94-use-a-single-key-vault-secret-for-app-config

Simplify passing sensitive configuration to application in PAAS

---

.github/workflows/actions/deploy-environment/action.yml
.github/workflows/build.yml

Give the OWASP scan valid API credentials so it can do more thorough checking.
https://trello.com/c/94Sj3Sta/80-add-owasp-api-test-to-ci-pipeline

Ensure OWASP scan can authenticate against API

---

src/DqtApi/Models/GetTeacherRequest.cs
src/DqtApi/Program.cs
tests/DqtApi.Tests/Operations/GetTeacherTests.cs

Tweaks the generated API spec for the Get Teacher operation to tidy some schema names and to align parameter names with EAPIM API implementation.
https://trello.com/c/Lh8Sg0RN/113-build-the-get-teacher-operation-endpoint

Tidy generated Swagger spec for Get Teacher operation

---

tests/DqtApi.TestCommon/DqtApi.TestCommon.csproj

Ensure `TestCommon` project isn't treated as a test project.

Fix error running tests against helper library

---

.github/workflows/build.yml

When builds are running concurrently we're seeing intermittent test failures due to multiple instances of the integration tests running at the same time. This change ensures that only one will run at once.

Ensure integration test runs happen one at a time on CI

---

src/DqtApi/Filters/CrmServiceProtectionFaultExceptionFilter.cs
src/DqtApi/Program.cs
tests/DqtApi.Tests/ApiFixture.cs
tests/DqtApi.Tests/Filters/CrmServiceProtectionFaultExceptionFilterTests.cs

Forward any API limit-related errors to our API consumers
https://docs.microsoft.com/en-us/powerapps/developer/data-platform/api-limits#service-protection-api-limit-errors-returned

Add an exception filter to map CRM service protection errors to a 429 response

---

.github/workflows/actions/deploy-environment/action.yml
.github/workflows/actions/functional-tests/action.yml
.github/workflows/build.yml
azure/azuredeploy.prod.parameters.json
terraform/prod.backend.tfvars
terraform/prod.tfvars.json

Adds production environment deployment to CI/CD pipeline after the test environment has been deployed.
Also splits out the functional test running so it can be more easily skipped (which we do for production - we don't have stable test data to run tests with currently).
https://trello.com/c/ttA2o9jD/144-provision-production-environment

Add production deployment to pipeline

---

src/DqtApi/DataStore/Sql/DbContextTransactionExtensions.cs
src/DqtApi/DataStore/Sql/DqtContext.cs
src/DqtApi/DataStore/Sql/DqtDesignTimeDbContextFactory.cs
src/DqtApi/DqtApi.csproj
tests/DqtApi.Tests/ApiTestBase.cs
tests/DqtApi.Tests/DbHelper.cs

Adds a few helper methods for:
- getting a Postgres advisory lock;
- working with `DbContext` in tests (e.g. for adding test data).
Applies a snake case naming convention to generated database objects.
Apply fluent entity configurations via discovery.
Also fixes design-time DbContext creation (so that generating migrations works correctly).

DB conventions & testing helpers

---

.github/workflows/build.yml
src/DqtApi/ApiVersionConvention.cs
src/DqtApi/Program.cs
src/DqtApi/V1/Controllers/TeachersController.cs
src/DqtApi/V1/Responses/EntityExtensions.cs
src/DqtApi/V1/Responses/GetTeacherResponse.cs
src/DqtApi/V1/Responses/Induction.cs
src/DqtApi/V1/Responses/InitialTeacherTraining.cs
src/DqtApi/V1/Responses/LinkedEntity.cs
src/DqtApi/V1/Responses/Qualification.cs
src/DqtApi/V1/Responses/QualifiedTeacherStatus.cs
src/DqtApi/V1/Responses/Subject.cs
src/DqtApi/V1/Validators/GetTeacherRequestValidator.cs
tests/DqtApi.FunctionalTests/Endpoints/SwaggerTests.cs
tests/DqtApi.FunctionalTests/Endpoints/V1/GetTeacherTests.cs
tests/DqtApi.Tests/V1/Operations/GetTeacherTests.cs
tests/DqtApi.Tests/V1/UnitTests/GetTeacherRequest.cs
tests/DqtApi.Tests/V1/UnitTests/GetTeacherResponse.cs
tests/DqtApi.Tests/V1/UnitTests/TeachersController.cs

Adds a convention for separating endpoints into API versions by namespace e.g. controllers in the `DqtApi.V1` namespace go into the V1 API, `DqtApi.V21 into the V2 API etc.
Updates the OWASP scan to crawl both the V1 and V2 API specs.
Pre-requisite for https://trello.com/c/EgaTYdhB/146-decommission-dttp

Add a V2 API spec and separate operations by namespace

---

.github/workflows/build.yml
azure/azuredeploy.preprod.parameters.json
terraform/api-app.tf
terraform/dev.tfvars.json
terraform/preprod.backend.tfvars
terraform/preprod.tfvars.json
terraform/prod.tfvars.json
terraform/test.tfvars.json
terraform/variables.tf

Adds pre-production environment deployment to CI/CD pipeline between the test and production environments.
Also amends the `logging` user-defined service to give it an environment-specific name, since pre-prod's resource live in the same PAAS space as the test environment.
https://trello.com/c/wCvn2TBm/145-provision-pre-production-environment

Add pre-production environment to pipeline

---

src/DqtApi/Configuration/MetricLabels.cs
src/DqtApi/Program.cs
tests/DqtApi.FunctionalTests/DqtApi.FunctionalTests.csproj

Defines labels for all Prometheus metrics for the PAAS app name, org, space and app instance.
https://trello.com/c/mlmPAocF/111-set-up-prometheus-for-tra-services

Add PAAS environment details to Prometheus metrics

---

src/DqtApi/DqtApi.csproj
src/DqtApi/Program.cs

https://trello.com/c/FoAsQBD8/82-add-production-api-to-teacher-services-status-site
Adds a `/status` endpoint which runs checks against Postgres & CRM and returns either 200 or 503 based on whether all checks have passed or any have failed.
N.B. this is a different endpoint to `/health`, which is used by PAAS to decide whether a specific app instance is healthy. Since this check includes external components (which should *not* trigger PAAS to restart app nodes) it's a different endpoint.
- Run the app, browse to `/status` and observe successful status check response.
- Stop local Postgres instance, browse to `/status` and observe failed status check response.

Add status endpoint and include Postgres & CRM checks

---

tests/DqtApi.Tests/ApiFixture.cs

60271d9491e376e292a68c3544243fa1dca9b7c2 made a change that required
connection strings be resolvable from our API entry point (i.e.
Program.cs) but our user secrets config source was being added *after*
the entry point ran (so any config set there isn't available to the
entry point). This change eagerly gets IConfiguration from user secrets
and ensures it's available to the entry point.
Fixing something I broke here 60271d9491e376e292a68c3544243fa1dca9b7c2
Adjusts when user-secret-derived config is retrieve so it happens *before* the entry point is hit.
-   [ ] Attach to Trello card - N/A

Fix running tests locally when relying on User Secrets

---

src/DqtApi/CamelCaseErrorKeysProblemDetailsFactory.cs
src/DqtApi/DataStore/Crm/Models/GetTeacherRequest.cs
src/DqtApi/DqtApi.csproj
src/DqtApi/Json/DateOnlyConverter.cs
src/DqtApi/ModelBinding/Constants.cs
src/DqtApi/ModelBinding/DateTimeReverseOrderBinder.cs
src/DqtApi/ModelBinding/HybridBodyApiDescriptionProvider.cs
src/DqtApi/ModelBinding/HybridBodyModelBinderProvider.cs
src/DqtApi/ModelBinding/MvcOptionsExtensions.cs
src/DqtApi/Program.cs
src/DqtApi/Swagger/JsonSerializerDataContractResolver.cs
src/DqtApi/V2/Controllers/TrnRequestsController.cs
src/DqtApi/V2/Requests/GetTrnRequest.cs

This PR contains some of the model binding tweaks extracted from the PR for the 'Put TRN request'.
Pre-requisite for https://trello.com/c/FJHFPAxn/155-register-api-create-put-request
There are three changes here:
The previous intention was to use [HybridModelBinding](https://github.com/billbogaiv/hybrid-model-binding) but it doesn't play nicely with Swashbuckle so the generated Swagger doc is incorrect. This implementation is based on what HybridModelBinding does but trimmed down and with support for generating a correct Swagger doc.
Having a single object for the entire request is desirable as it works better with MediatR and FluentValidation, both of which expect a single request object.
`System.Text.Json` doesn't yet support `DateOnly` so we add it here ourselves.
When we generate a …

Model binding and Swagger improvements

---

.github/workflows/build.yml
Sync-ApiSpecs.ps1
docs/api-specs/v1.json
docs/api-specs/v2.json

Adds a script to extract Swagger docs from a running instance of the API and amends the build process to sync Swagger docs on PR builds, if required.
https://trello.com/c/6lyWqai7/130-create-tech-docs-space-and-pull-guidance-across-from-confluence-etc
- Powershell script to generate Swagger docs.
- CI pipeline addition for PR builds

Extract API specs

---

src/DqtApi/CacheKeys.cs
src/DqtApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
src/DqtApi/DataStore/Crm/DataverseAdapter.cs
src/DqtApi/Program.cs
tests/DqtApi.Tests/DataverseIntegration/CrmClientFixture.cs
tests/DqtApi.Tests/DataverseIntegration/GetMatchingTeachersTests.cs

https://trello.com/c/JFFRWNZ2/169-add-caching-to-reference-data-lookups-in-put-trn-request-operation
Adds caching to reference data lookups performed when creating a teacher. This reference data is effectively static so we're not worried about having to expire cache entries here.

Add caching to reference data lookups for Teacher creation

---

docs/api-specs/v1.json
docs/api-specs/v2.json
src/DqtApi/DqtApi.csproj
src/DqtApi/Program.cs
src/DqtApi/Security/ApiClientResolveContributor.cs
src/DqtApi/Security/ClaimsPrincipalCurrentClientProvider.cs
src/DqtApi/Security/RateLimitConfiguration.cs
src/DqtApi/Security/RateLimitMiddleware.cs
src/DqtApi/Swagger/RateLimitOperationFilter.cs
src/DqtApi/appsettings.Production.json
terraform/api-app.tf
terraform/data.tf
terraform/dev.tfvars.json
terraform/preprod.tfvars.json
terraform/prod.tfvars.json
terraform/test.tfvars.json
terraform/variables.tf

https://trello.com/c/OE5G3TVw/181-add-rate-limiting-to-api
- Adds a Redis service to every environment.
- Adds API rate limiting (300 requests per minute, mirroring EAPIM API implementation)
Verify Terraform changes meet Teacher Services standards.

Add rate limiting to API

---

tests/DqtApi.Tests/DataverseIntegration/CreateTeacherTests.cs
tests/DqtApi.Tests/DataverseIntegration/CrmClientFixture.cs
tests/DqtApi.Tests/DataverseIntegration/DataverseTestCollection.cs
tests/DqtApi.Tests/DataverseIntegration/EntityCleanupHelper.cs
tests/DqtApi.Tests/DataverseIntegration/ExclusiveCrmTestCollection.cs
tests/DqtApi.Tests/DataverseIntegration/GetCountryTests.cs
tests/DqtApi.Tests/DataverseIntegration/GetEarlyYearsStatusTests.cs
tests/DqtApi.Tests/DataverseIntegration/GetHeQualificationByNameTests.cs
tests/DqtApi.Tests/DataverseIntegration/GetHeSubjectByNameTests.cs
tests/DqtApi.Tests/DataverseIntegration/GetIttProvidersTests.cs
tests/DqtApi.Tests/DataverseIntegration/GetIttSubjectByNameTests.cs
tests/DqtApi.Tests/DataverseIntegration/GetMatchingTeachersFixture.cs
tests/DqtApi.Tests/DataverseIntegration/GetMatchingTeachersTests.cs
tests/DqtApi.Tests/DataverseIntegration/GetOrganizationByUkprnTests.cs
tests/DqtApi.Tests/DataverseIntegration/GetTeacherStatusTests.cs
tests/DqtApi.Tests/DataverseIntegration/GetTeacherTests.cs
tests/DqtApi.Tests/DataverseIntegration/UnlockTeacherRecordTests.cs
tests/DqtApi.Tests/DqtApi.Tests.csproj
tests/DqtApi.Tests/Startup.cs

Split apart from one of the new APIs for Register - https://trello.com/c/ngFfEsOx/16-register-api-create-put-request-for-qts
* Adds dependency injection support for tests
This allows us to have dependencies between fixtures, something that isn't possible with out-of-the-box xUnit. Specifically `CrmClientFixture` is now injected via DI and is singleton-scoped, meaning the CRM `ServiceClient` is now created and re-used across all tests. This is an enabler for the next change...
* Re-use some test data in a data-driven test
Lots of data permutations in `Given_details_that_do_not_match_existing_records_allocates_trn` previously meant that the same entity was getting created and cleaned up many times needlessly. This sets it up once, re-uses it for all test cases then cleans it up.
* Batch the …

Improve CRM integration tests performance

---

Set-AppConfigSecret.ps1

Make adding new application secrets easier.
Adds a script that will add the specified config entry into the JSON-encoded Key Vault secret for the specified environment including a read-only 'dry run' option. 
Previous steps involved getting old JSON from Key Vault, re-formatting it to make it readable, adding new JSON & adding back into Key Vault, crossing fingers that everything was valid. 
Review docs and sanity check script.
-   [ ] Attach to Trello card - N/A

Add script for adding app config secrets to Key Vault

---

.github/workflows/actions/deploy-environment/action.yml
src/DqtApi/DqtApi.csproj
src/DqtApi/HttpRequestExtensions.cs
src/DqtApi/Logging/ApplicationBuilderExtensions.cs
src/DqtApi/Logging/LogEventExtensions.cs
src/DqtApi/Logging/RedactQueryParamAttribute.cs
src/DqtApi/Logging/RedactedUrlParameters.cs
src/DqtApi/Logging/RemoveRedactedUrlParametersEnricher.cs
src/DqtApi/Logging/RemoveRedactedUrlParametersEventProcessor.cs
src/DqtApi/Program.cs
src/DqtApi/V1/Controllers/TeachersController.cs
src/DqtApi/appsettings.Production.json
src/DqtApi/appsettings.json
terraform/api-app.tf
terraform/dev.tfvars.json
terraform/preprod.tfvars.json
terraform/prod.tfvars.json
terraform/test.tfvars.json
terraform/variables.tf

https://trello.com/c/LM4vWwgI/59-integrate-with-sentry-dqt-api
* Adds Sentry integration
Send the `environment` and `version` with every event too. `version` is the deployed commit SHA.
* Prevent logging PII from query parameters
Annotating an action method with one or more `RedactQueryParamAttribute`s will redact the query parameter value when logging. Sentry is configured to never send the request body.

Sentry integration

---

.editorconfig
docs/running-load-tests.md
load-tests/get-teacher.js
load-tests/package-lock.json
load-tests/package.json

https://trello.com/c/hB1bNKtO/76-test-dqt-api
Adds a simple load test of the Get Teacher API using k6. Test is configured to go up to 300reqs/minute to match our rate limiting configuration.
Pull PR and try to execute tests using docs.

Add simple load test of Get Teacher API using k6

---

terraform/api-app.tf
terraform/data.tf
terraform/preprod.tfvars.json
terraform/prod.tfvars.json
terraform/test.tfvars.json
terraform/variables.tf

Terraform resources and variable defined for creating a route for
education.gov.uk. This will enable access of API instance through
custom domain.
https://trello.com/c/5J3h8Phh

Add education.gov.uk domain

---

src/DqtApi/Program.cs
src/DqtApi/appsettings.Production.json

Don't track every request - only log errors. Reduces the volume of events we're sending to Sentry.

Turn off Sentry sampling

---

src/DqtApi/V2/Handlers/FindTeachersHandler.cs
tests/DqtApi.Tests/V2/Operations/FindTeachersTests.cs

We want to always return a response, even if the find had no results.

Don't return 204 when there are no search results

---

src/DqtApi/DataStore/Crm/DataverseAdapter.cs

CPD reported the API is returning `null` `qtsDate` for a teacher where the CRM portal has a non-`null` value. The teacher in question has multiple `qtsregistration` records; one is `Inactive` and the other is `Active`. The API currently doesn't exclude `Inactive` records and arbitrarily picks the first one and returns that.
Exclude `Inactive` `qtsregistration` records from being returned from the Get Teacher endpoint.
Also moved the `Add..Link` methods to be local functions; their names only make sense in the context of the `GetMatchingTeachersAsync` method.

Ignore Inactive qtsregistration records in v1 Get Teacher operation

---

src/DqtApi/DataStore/Crm/DataverseAdapter.SetIttResultForTeacher.cs
src/DqtApi/DataStore/Crm/DataverseAdapter.UpdateTeacher.cs
src/DqtApi/DataStore/Crm/DataverseAdapter.cs
src/DqtApi/DataStore/Crm/IDataverseAdapter.cs
src/DqtApi/V1/Controllers/TeachersController.cs
src/DqtApi/V2/Handlers/GetOrCreateTrnRequestHandler.cs
src/DqtApi/V2/Handlers/GetTrnRequestHandler.cs
src/DqtApi/V2/Handlers/UnlockTeacherHandler.cs
tests/DqtApi.Tests/DataverseIntegration/GetMatchingTeachersTests.cs
tests/DqtApi.Tests/DataverseIntegration/GetTeacherTests.cs
tests/DqtApi.Tests/DataverseIntegration/SetIttOutcomeForTeacherTests.cs
tests/DqtApi.Tests/DataverseIntegration/UnlockTeacherRecordTests.cs
tests/DqtApi.Tests/DataverseIntegration/UpdateTeacherTests.cs
tests/DqtApi.Tests/V1/UnitTests/TeachersController.cs
tests/DqtApi.Tests/V2/Operations/FindTeachersTests.cs
tests/DqtApi.Tests/V2/Operations/GetOrCreateTrnRequestTests.cs
tests/DqtApi.Tests/V2/Operations/GetTrnRequestTests.cs
tests/DqtApi.Tests/V2/Operations/SetIttOutcomeTests.cs
tests/DqtApi.Tests/V2/Operations/UnlockTeacherTests.cs
tests/DqtApi.Tests/V2/Operations/UpdateTeacherTests.cs

- Remove Async suffix from method names.
- Return arrays instead of IEnumerable<T>.
- Fix up a few method names.

Tidy signature of IDataverseAdapter

---

.zap/rules.tsv

We get these erratically on CI and it's not a real issue.

Disable Timestamp Disclosure ZAP errors

---

.github/workflows/build.yml

https://trello.com/c/h9MO3pOl/207-fix-sql-migration-issues-on-test-environment
Errors applying migrations have historically not failed the pipeline which means the test environment has had an issue for a while. This fixes the pipeline so errors fail each stage. Fixing the test environment has been done manually.

Ensure errors applying migrations fail the deployment stage

---

src/DqtApi/Properties/StringResources.Designer.cs
src/DqtApi/Properties/StringResources.resx
src/DqtApi/V1/Validators/GetTeacherRequestValidator.cs
src/DqtApi/Validation/Constants.cs

https://trello.com/c/w4spryA5/206-fix-validation-exception-from-get-teacher-endpoint
Add extra validation to ensure the birth date is within the acceptable bounds for CRM.

Fix out of range birth date triggering an error from CRM

---

src/DqtApi/Logging/ApplicationBuilderExtensions.cs
src/DqtApi/Program.cs

This makes debugging considerably easier.
We have an error on Sentry with a `NullReferenceException` and the stack trace is somewhere inside Fluent Validation. Getting the request body with errors such as this will make debugging simpler.
Disabled for production environment because a) buffering the request has a cost and b) we don't want to store PII in logs.
Add a `RequestBody` property to logs for non-production environments.

Log request body with errors for non-production environments

---

src/DqtApi/V2/Validators/GetOrCreateTrnRequestValidator.cs
tests/DqtApi.Tests/V2/Operations/GetOrCreateTrnRequestTests.cs

Added new validation rule to stop dob being in the future and less than 1940-01-01
new validation rule & tests.
-   [] Attach to Trello card

Added Validation rule to not allow dob >= today & dob < 01-01-1940

---

src/DqtApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
src/DqtApi/DataStore/Crm/DataverseAdapter.RequestBuilder.cs
src/DqtApi/DataStore/Crm/DataverseAdapter.cs
src/DqtApi/DataStore/Crm/IDataverseAdapter.cs
src/DqtApi/V2/Handlers/FindTeachersHandler.cs
tests/DqtApi.Tests/V2/Operations/FindTeachersTests.cs
tests/DqtApi.Tests/xunit.runner.json

Some operations like Create Teacher need to lookup a lot of data from CRM. Our helper methods on `DataverseAdapter` are used for these lookups. Currently these methods both construct the CRM requests *and* send them. With this design we cannot easily batch requests; the best we could do was running these requests in parallel.
This PR changes reference data methods to introduce a second, private overload that takes a `RequestBuilder` argument. `RequestBuilder` is a new type that can be used for bundling requests then send them all to CRM in a single hit. With this we can decouple the sending of the request from our lookup methods and have the caller orchestrate that when it's ready. The general pattern is:
```cs
public Task<Thing> LookupThing(string id) => LookupThing(id, requestBuilder: …
```

CRM request batching improvements

---

src/DqtApi/Configuration/MetricLabels.cs

Changed metric label from instance to app_instance. This enables to
easily identify and process instance metrics in prometheus.
https://trello.com/c/xDKhH54u

Change prometheus metric label

---

docs/api-specs/v2.json
src/DqtApi/V2/Handlers/SetIttOutcomeHandler.cs
src/DqtApi/V2/Handlers/UpdateTeacherHandler.cs
src/DqtApi/V2/Requests/SetIttOutcomeRequest.cs
src/DqtApi/V2/Requests/UpdateTeacherRequest.cs
src/DqtApi/V2/Validators/SetIttOutcomeValidator.cs
src/DqtApi/V2/Validators/UpdateTeacherValidator.cs
tests/DqtApi.Tests/V2/Operations/SetIttOutcomeTests.cs
tests/DqtApi.Tests/V2/Operations/UpdateTeacherTests.cs

Added validation rule for birthdate to stop birthdate being optional and causing an error when not being provided & updated corresponding tests.
Added birthdate to the querystring parameter and updated tests.

Added validation to setittoutcome and update teacher to make birthdate mandatory

---

src/DqtApi/Program.cs
src/DqtApi/Validation/PreferModelBindingErrorsValidationInterceptor.cs

Prevents us returning multiple errors like 'Birthdate is invalid' and
'Birthdate is required'.

Prefer errors from model binders over FluentValidation errors

---

src/DqtApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
src/DqtApi/DataStore/Crm/DataverseAdapter.cs
src/DqtApi/V2/Handlers/GetTrnRequestHandler.cs
tests/DqtApi.Tests/DataverseIntegration/CreateTeacherTests.cs

https://trello.com/c/lmnxcAtJ/173-close-up-gaps-between-dttp-integration-tests-and-dqt-api-tests
- Fix pulling back TRN column for a merged record.
- Ensure `Status` field is consistent for both Create and Get TRN request operations.
- Amend copy for duplicate review task.

Simple fixes for TRN generation process

---

terraform/preprod.tfvars.json
terraform/prod.tfvars.json
terraform/statuscake.tf
terraform/test.tfvars.json

Status cake contact group name passed in fails to populate contact group
field on deployment. Contact group ID fixes this issue. Default check
rate is too high means url could be down for few minutes without alerts
being sent. This commit address these to issues.
https://trello.com/c/yZ1wrROi

Fix bug and modify checkrate

---

src/DqtApi/Json/DateOnlyConverter.cs

`DateOnly` parse failures inside a JSON request currently return a useless error message that doesn't even include the field name. This fixes that.
Change exception thrown on parse failure so the failure is rendered in the error response.

Ensure JSON DateOnly parse failures yield a useful error message

---

src/DqtApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs

The query that returns potential duplicate teachers wasn't returning the fields we matching so weren't correctly figuring out the Task description.
Include the matched fields in the response so we correctly produce description.

Fix Task description to show matched attributes on duplicate teacher

---

src/DqtApi/DataStore/Crm/DataverseAdapter.UpdateTeacher.cs
src/DqtApi/DataStore/Crm/UpdateTeacherResult.cs
src/DqtApi/V2/Handlers/UpdateTeacherHandler.cs
tests/DqtApi.Tests/DataverseIntegration/UpdateTeacherTests.cs
tests/DqtApi.Tests/V2/Operations/UpdateTeacherTests.cs

Updated update teacher handler to allow returning more than one error, which will stop 500 error messages.
Update endpoint previously threw 500 errors when there are more than one error on when calling the endpoint (e.g. more than one lookup fails).

Update endpoint to allow multiple errors to be returned

---

.github/workflows/build.yml
Dockerfile

Sentry release ID relies on a `GitSha` environment variable that wasn't being set. Fix that here.

Fix Sentry release identification

---

terraform/api-app.tf
terraform/data.tf
terraform/dev.tfvars.json
terraform/network-policies.tf
terraform/prod.tfvars.json
terraform/variables.tf

Add internal route for the api app and network policy so that Prometheus can receive metrics from the api app through internal route. This will enable aggregation of metrics over the number of api app instances running.
https://trello.com/c/G6763qSL

Add internal route

---

src/DqtApi/DataStore/Crm/DataverseAdapter.cs

Immediate fix for passing dateonly to crm rather than a date time.
This fix stops the api from throwing a 500 when calling find.

stop passing dateonly to crm rather than datetime

---

src/DqtApi/V2/Handlers/FindTeachersHandler.cs
tests/DqtApi.Tests/V2/Operations/FindTeachersTests.cs

Handler was previously not able to handle nulls when there are no query string parameters, the dataverseadapter returned null early, but the handler was tryting to call .select on null. This change fixes this.
Change handler to handle nulls & add a missing test.

Fix to handle nulls in find teacher

---

src/DqtApi/DataStore/Crm/IWebApiAdapter.cs
src/DqtApi/DataStore/Crm/WebApiAdapter.cs
src/DqtApi/DqtApi.csproj
src/DqtApi/Program.cs
src/DqtApi/Services/LogRemainingCrmLimitsService.cs

https://trello.com/c/BEEIWcVq/273-spike-dqt-reg-performance-load-monitoring
Adds a `BackgroundService` that periodically calls CRM and extracts the remaining API limits and logs these to Prometheus.

Add Prometheus metrics for CRM service limits

---

src/DqtApi/DataStore/Crm/DataverseAdapter.SetIttResultForTeacher.cs
tests/DqtApi.Tests/DataverseIntegration/SetIttOutcomeForTeacherTests.cs

Update set itt outcome to clear teacherstatusid/earlyyearsstatusid conditionally.

Set correct status to null when teacher is withdrawn

---

src/DqtApi/DataStore/Crm/DataverseAdapter.UpdateTeacher.cs
tests/DqtApi.Tests/DataverseIntegration/UpdateTeacherTests.cs
tests/DqtApi.Tests/ExecuteTransactionRequestExtensions.cs

This stops creating a new qualification when there are alreay more than 1 qualification.
It was raised on the DTTP testing spreadsheet that when there are more than one qualification - dqt api was creating a new qualification incorrectly.
-   [] Attach to Trello card

Stop creating new qualification incorrectly

---

src/DqtApi/DataStore/Crm/DataverseAdapter.UpdateTeacher.cs
tests/DqtApi.Tests/DataverseIntegration/UpdateTeacherTests.cs

Issue was raised on DTTP spreadsheet that when updating a ITT record whereby the provider does not match, then a new record is created, however the result was always null. This PR sets the result field to InTraining when we create a new ITT record.

Set ITT Result to intraining when creating a new ITT record from update endpoint

---

.github/workflows/build.yml

We currently run tests on PRs (these have to pass before we can merge) then we merge to `main` then the same tests run again. These tests aren't the fastest so we're wasting time in actually deploying the change. This changes that so we don't run the tests for `main`.
Don't run unit & integration tests for builds on `main`.

Only run unit/integration tests for PRs

---

src/DqtApi/Program.cs

https://trello.com/c/K2jtnkau/321-remove-verbose-server-headers-from-api
Remove the `Server: Kestrel` header.

Remove the Server header

---

src/DqtApi/DataStore/Crm/DataverseAdapter.RequestBuilder.cs
src/DqtApi/DataStore/Crm/DataverseAdapter.cs
tests/DqtApi.Tests/DataverseIntegration/CreateTeacherTests.cs
tests/DqtApi.Tests/DataverseIntegration/CrmClientFixture.cs
tests/DqtApi.Tests/DataverseIntegration/SetIttOutcomeForTeacherTests.cs
tests/DqtApi.Tests/DataverseIntegration/UpdateTeacherTests.cs
tests/DqtApi.Tests/DqtApi.Tests.csproj
tests/DqtApi.Tests/Startup.cs
tests/DqtApi.Tests/TestDataHelper.CreatePerson.cs
tests/DqtApi.Tests/TestDataHelper.cs

Also add caching for reference data lookups.
Integration tests are taking longer and longer to run. Many tests do the same work (around creating teacher records etc.). We can optimise some of this by caching lookups. As a side-effect we get a single helper method for creating a teacher.
- Add a `TestDataHelper.CreatePerson()` method for creating contact, ITT, qualification, QTS and sanction records. Use caching for reference data lookups.
- Allow more test classes to run in parallel. There's no data dependency between them so they're fine to run in parallel.

Use a common helper method for creating teacher records in tests

---

docs/api-specs/v2.json
src/DqtApi/DataStore/Crm/DataverseAdapter.cs
src/DqtApi/DataStore/Crm/IDataverseAdapter.cs
src/DqtApi/DataStore/Crm/Models/FindTeachersQuery.cs
src/DqtApi/V2/Handlers/FindTeachersHandler.cs
src/DqtApi/V2/Requests/FindTeachersRequest.cs
tests/DqtApi.Tests/DataverseIntegration/FindTeachersTests.cs
tests/DqtApi.Tests/DataverseIntegration/SetIttOutcomeForTeacherTests.cs
tests/DqtApi.Tests/TestDataHelper.CreatePerson.cs
tests/DqtApi.Tests/V2/Operations/FindTeachersTests.cs

https://trello.com/c/dRCLwGgG/380-update-matching-rules-for-qualified-teachers-api-find-endpoints
Amend the matching rules to align with https://tra-digital-design-history.herokuapp.com/find-a-lost-trn/matching-rules-for-mvp/ - require a match on at least 3 identifiers (of ITT provider, DOB, NINO and Name).
Added de-duping for cases where a person has multiple ITT records but hasn't necessarily matched on ITT provider.
Also changed ITT Provider lookup to ensure we're only looking at training provider orgs. (We were occasionally getting errors from duplicates before.)

Amend FindTeachers endpoint to use revised matching criteria

---

src/DqtApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
src/DqtApi/DataStore/Crm/DataverseAdapter.SetIttResultForTeacher.cs
src/DqtApi/DataStore/Crm/DataverseAdapter.UpdateTeacher.cs
src/DqtApi/DataStore/Crm/DataverseAdapter.cs
src/DqtApi/DataStore/Crm/IDataverseAdapter.cs
src/DqtApi/DataStore/Crm/Models/FindTeachersQuery.cs
src/DqtApi/V2/Handlers/FindTeachersHandler.cs
tests/DqtApi.Tests/DataverseIntegration/FindTeachersTests.cs
tests/DqtApi.Tests/DataverseIntegration/GetOrganizationsByUkprnTests.cs
tests/DqtApi.Tests/DataverseIntegration/UpdateTeacherTests.cs
tests/DqtApi.Tests/TestDataHelper.CreatePerson.cs
tests/DqtApi.Tests/V2/Operations/FindTeachersTests.cs

In some cases there are multiple providers for a given set of criteria
(now we're returning Inactive records too).
https://sentry.io/organizations/dfe-teacher-services/issues/3278065486/?project=6165440&referrer=slack
Change `GetOrganization*` methods to return `Account[]` instead of `Account`.

Fix GetProvider* queries to return an array

---

src/DqtApi/Security/ApiClient.cs
src/DqtApi/Security/ConfigurationApiClientRepository.cs
src/DqtApi/appsettings.Development.json
src/DqtApi/appsettings.Testing.json

Support multiple api keys
https://trello.com/c/fBsebtXB/451-support-multiple-keys-per-client-in-dqt
Allow multiple api keys so that keys can be pulled/swapped out.

support multiple apikeys

---

.github/workflows/build.yml

This is to aid testing changes up to the pre-prod environment.
Deploying to production is controlled by an option ('false' by default).

Add workflow_dispatch trigger to build workflow

---

docs/api-specs/v2.json
src/DqtApi/DataStore/Crm/Models/GeneratedOptionSets.cs
src/DqtApi/V2/ApiModels/Gender.cs

https://trello.com/c/GnZ9EmFw/268-align-dqt-values-for-gender-with-register-and-hesa
Adds two additional values for `gender` - `NotProvided` and `NotAvailable`.

Add additional values for gender

---

Generate-CrmModels.ps1
src/DqtApi/DataStore/Crm/Models/GeneratedCode.cs

The ServiceContext gives us an IQueryable for each entity type to make
crafting queries easier, especially for ad-hoc scripts and tooling.

Generate an OrganizationServiceContext for CRM

---

src/DqtApi/V1/Handlers/GetTeacherHandler.cs

We have some errors in Sentry where a `contact` has an `Induction` but that `Induction` doesn't have an `InductionStatus`. This change is to handle that case and return null for `InductionStatusName`.

Handle missing InductionStatus on Get Teacher endpoint

---

docs/api-specs/v2.json
src/DqtApi/DataStore/Crm/Models/GeneratedOptionSets.cs
src/DqtApi/V2/ApiModels/IttProgrammeType.cs
tests/DqtApi.Tests/DataverseIntegration/CreateTeacherTests.cs
tests/DqtApi.Tests/DataverseIntegration/UpdateTeacherTests.cs

https://trello.com/c/4lSfYUNW/485-create-new-itt-programme-types-in-dqt-for-provider-led-postgrad-and-provider-led-undergrad
added new programme type for itt provider in crm and generated option sets.
- provider-led (postgrad)
- provider-led (undergrad)
added new programme type for itt provider in crm and generated option sets.

Add new itt programmetypes

---

docs/api-specs/v2.json
src/DqtApi/DataStore/Crm/DataverseAdapter.cs
src/DqtApi/DataStore/Crm/Models/FindTeachersQuery.cs
src/DqtApi/V2/Handlers/FindTeachersHandler.cs
src/DqtApi/V2/Requests/FindTeachersRequest.cs

https://trello.com/c/K7eLDbBh/563-re-enable-email-match-in-the-dqt-api
Restore the `email` field on the 'find' endpoint.

Restore the email field on the Find endpoint

---

src/DqtApi/Properties/StringResources.Designer.cs
src/DqtApi/Properties/StringResources.resx
src/DqtApi/V2/Handlers/UnlockTeacherHandler.cs
src/DqtApi/Validation/ErrorRegistry.cs
tests/DqtApi.Tests/V2/Operations/UnlockTeacherTests.cs

https://trello.com/c/o7Zr0VuL/605-prevent-unlocking-a-teacher-with-active-sanctions
Stop allowing a teacher account to be unlocked when there are active sanctions.

Stop allowing a teacher to be unlocked when it has active sanctions

---

src/DqtApi/V2/Validators/GetOrCreateTrnRequestValidator.cs

If the `InitialTeacherTraining` property isn't provided at all in the request all our subsequent validations fail with `NullReferenceException`s. Fix that up here.

Handle completely missing ITT block on the TRN endpoint

---

src/DqtApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
src/DqtApi/V2/Handlers/GetOrCreateTrnRequestHandler.cs
tests/DqtApi.Tests/V2/Operations/GetOrCreateTrnRequestTests.cs

https://trello.com/c/95M3M2vB/635-split-forenames-into-first-and-middle-names-for-hesa-trainees
The name passed from HESA is in a single field and Register split it into first & last name (they don't have middle name). This splits first name to populate middle name.
Split first name and populate middle name for HESA trainees.

Split FirstName for HESA trainees

---

docs/api-specs/v2.json
src/DqtApi/DataStore/Crm/DataverseAdapter.cs
src/DqtApi/DataStore/Crm/IDataverseAdapter.cs
src/DqtApi/DateOnlyExtensions.cs
src/DqtApi/V2/ApiModels/IttOutcome.cs
src/DqtApi/V2/Controllers/TeachersController.cs
src/DqtApi/V2/Handlers/GetTeacherHandler.cs
src/DqtApi/V2/Requests/GetTeacherRequest.cs
src/DqtApi/V2/Responses/GetTeacherResponse.cs
src/DqtApi/V2/Validators/GetTeacherRequestValidator.cs
tests/DqtApi.TestCommon/AssertEx.Http.cs
tests/DqtApi.Tests/V2/Operations/GetTeacherTests.cs

https://trello.com/c/Ng9O2kzc/647-add-eyts-date-and-early-years-teacher-status-to-the-api
Current v1 API doesn't include Early Years info, which is required by Register.
This adds a v2 'get teacher' endpoint including this information. (The V1 API has some quirks and we don't really want to extend it.)
Add a `GET /v2/teachers/{trn}` endpoint.

Add a v2 Get Teacher endpoint including EYTS

---

src/DqtApi/V2/Handlers/GetOrCreateTrnRequestHandler.cs
src/DqtApi/V2/Validators/GetOrCreateTrnRequestValidator.cs

We currently explode if the `address` property isn't provided. None of the address fields are mandatory so the `address` block itself shouldn't be mandatory either.
Handle when the `address` block is not provided (or is `null`).

Handle a missing Address block on the TRN endpoint

---

src/DqtApi/Program.cs
src/DqtApi/Services/CrmKeepAliveService.cs

We're seeing connection timeouts when the API is cold. This calls into
the CRM API every two minutes to try to ensure we have a warm connection
cache when an API call comes in.

Add a service to call CRM API every 2 minutes

---

docs/api-specs/v2.json
src/DqtApi/DataStore/Crm/DataverseAdapter.cs
src/DqtApi/DataStore/Crm/Models/FindTeachersByTrnBirthDateAndNinoQuery.cs
src/DqtApi/DataStore/Crm/Models/FindTeachersQuery.cs
src/DqtApi/V2/Requests/FindTeachersRequest.cs
tests/DqtApi.Tests/DataverseIntegration/GetMatchingTeachersFixture.cs
tests/DqtApi.Tests/V1/Operations/GetTeacherTests.cs

https://trello.com/c/wUKo1HUn/648-allow-specifying-a-trn-when-looking-up-a-trn
Adds the `trn` field to the Find API operation.

Add support for specifying TRN in Find operation

---

src/DqtApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
tests/DqtApi.Tests/DataverseIntegration/EntityTrackingOrganizationService.cs
tests/DqtApi.Tests/DataverseIntegration/GetTeachersByTrnAndDobTests.cs

This makes the task to extract the created entities from CRM responses a parent of the method result rather than a sibling. As such, any exceptions thrown by that extraction process are observed by the caller.

Fix clearing down test data

---

src/DqtApi/DataStore/Crm/CreateTeacherResult.cs
src/DqtApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
src/DqtApi/DataStore/Crm/DataverseAdapter.UpdateTeacher.cs
src/DqtApi/DataStore/Crm/DataverseAdapter.cs
src/DqtApi/DataStore/Crm/IDataverseAdapter.cs
src/DqtApi/DataStore/Crm/UpdateTeacherResult.cs
src/DqtApi/Properties/StringResources.Designer.cs
src/DqtApi/Properties/StringResources.resx
src/DqtApi/V2/Handlers/GetOrCreateTrnRequestHandler.cs
src/DqtApi/V2/Handlers/UpdateTeacherHandler.cs
src/DqtApi/Validation/ErrorRegistry.cs
tests/DqtApi.Tests/DataverseIntegration/GetTeacherByHusIdTests.cs
tests/DqtApi.Tests/DataverseIntegration/UpdateTeacherTests.cs
tests/DqtApi.Tests/V2/Operations/GetOrCreateTrnRequestTests.cs
tests/DqtApi.Tests/V2/Operations/UpdateTeacherTests.cs

https://trello.com/c/AVwiSVbZ/649-reject-trn-requests-with-duplicate-husids-in-the-dqt-api
Reject creating a teacher when husid is being used for another teacher.
Endpoints that have been updated to reject duplicate husids
- UpdateTeacher
- GetOrCreateTrn

reject trn requests with duplicate husids

---

docs/api-specs/v2.json
src/DqtApi/V2/Controllers/UnlockTeacherController.cs
src/DqtApi/V2/Handlers/UnlockTeacherHandler.cs
src/DqtApi/V2/Requests/UnlockTeacherRequest.cs
src/DqtApi/V2/Responses/UnlockTeacherResponse.cs
tests/DqtApi.Tests/V2/Operations/UnlockTeacherTests.cs

Also changed behavior to leave the loginfailedcounter as-is unless it's over the locked threshold.
https://trello.com/c/sCZ4KJ5F/670-log-dqt-accounts-unlocked-by-find
Return a flag indicating whether the teacher was actually unlocked.

Return whether a teacher was actually unlocked

---

src/DqtApi/DataStore/Crm/DataverseAdapter.cs

https://trello.com/c/t4OHWRvz/731-stop-returning-inactive-data-on-the-v1-get-teachers-endpoint
Add a `state == 'Active'` filter to all the joined records in the V1 Get Teacher endpoint.

Only return active records from v1 Get Teacher endpoint

---

.github/workflows/build.yml

This reverts commit bd85c4b51cbda1339d1d3574f6e2564417027256.
Issues were caused by old test data that had TRNs allocated that were *ahead* of the autonumber range, hence the collisions.

Revert "Disable tests on CI until build environment issues are fixed"

---

src/DqtApi/V2/Handlers/FindTeachersHandler.cs
tests/DqtApi.Tests/V2/Operations/FindTeachersTests.cs

The current `find` operation will return an error if either the ITT provider UKPRN or name is specified but the lookup doesn't return a successful result. This effectively means a non-exact match on the ITT provider name will fail the lookup completely. That's not desirable.
https://trello.com/c/VhsP8hmX/206-amend-find-api-to-not-return-an-error-if-the-itt-provider-lookup-fails
Don't return an error if the ITT provider lookup returns no results.

Don't return an error if the ITT provider lookup returns no results

---

src/DqtApi/DqtApi.csproj
src/DqtApi/NoopAsyncDisposable.cs
src/DqtApi/Program.cs
src/DqtApi/Services/IDistributedLockService.cs
src/DqtApi/Services/LocalDistributedLockService.cs
src/DqtApi/Services/RedisDistributedLockService.cs
src/DqtApi/V2/Handlers/GetOrCreateTrnRequestHandler.cs
src/DqtApi/V2/Handlers/SetIttOutcomeHandler.cs
src/DqtApi/V2/Handlers/UpdateTeacherHandler.cs

We're seeing various API issues that seem to come from Postgres' advisory locks not behaving as we expect them to. Until we understand why this replaces PG advisory locks with Redis and its Redlock algorithm.

Use Redis instead of Postgres for locking

---

src/DqtApi/DataStore/Crm/DataverseAdapter.cs

Previous change to ignore all inactive data was too aggressive; we do want to return subjects even if they're inactive.
Return inactive subjects from Get Teacher endpoint

Don't filter out inactive subjects in Get Teacher endpoint

---

src/DqtApi/V2/Handlers/GetOrCreateTrnRequestHandler.cs

We have an error in Sentry caused by us doing `.Value` on an optional `DateOnly?` property. This removes the `.Value` call.
~~-   [] Attach to Trello card~~

Fix TRN endpoint when qualification has no date

---

DqtApi/src/DqtApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
DqtApi/src/DqtApi/DataStore/Crm/DataverseAdapter.UpdateTeacher.cs
DqtApi/src/DqtApi/DataStore/Crm/UpdateTeacherCommand.cs
DqtApi/src/DqtApi/V2/Handlers/UpdateTeacherHandler.cs
DqtApi/tests/DqtApi.Tests/DataverseIntegration/UpdateTeacherTests.cs

Previously we looked at TRN to know if the matched record was the same one as we're updating. This amends that check to look at ID instead. That's little more robust as IDs don't change and move around like TRNs do.

Amend HUSID duplicate check to look at ID instead of TRN

---

DqtApi/src/DqtApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
DqtApi/src/DqtApi/DataStore/Crm/DataverseAdapter.UpdateTeacher.cs
DqtApi/src/DqtApi/MemoryCacheExtensions.cs

If, say, a provider doesn't exist but then is added we may still return an error as we've cached the `null` lookup result.
This change skips writing a cache entry for `null` lookup results.

Don't cache failed lookup results

---

DqtApi/src/DqtApi/DataStore/Crm/DataverseAdapter.SetIttResultForTeacher.cs
DqtApi/src/DqtApi/DataStore/Crm/DataverseAdapter.UpdateTeacher.cs

Ensure we don't select an InTraining ITT record for an Assessment Only programme type.

Tighten logic on ITT record matching

---

.github/workflows/build.yml
DqtApi/src/DqtApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
DqtApi/src/DqtApi/DataStore/Crm/DataverseAdapter.cs
DqtApi/src/DqtApi/DqtApi.csproj
DqtApi/src/DqtApi/FeatureFlags.cs
DqtApi/src/DqtApi/Program.cs
DqtApi/src/DqtApi/Services/TrnGenerationApi/ITrnGenerationApiClient.cs
DqtApi/src/DqtApi/Services/TrnGenerationApi/NoopTrnGenerationApiClient.cs
DqtApi/src/DqtApi/Services/TrnGenerationApi/ServiceCollectionExtensions.cs
DqtApi/src/DqtApi/Services/TrnGenerationApi/TrnGenerationApiClient.cs
DqtApi/src/DqtApi/Services/TrnGenerationApi/TrnGenerationApiOptions.cs
DqtApi/src/DqtApi/appsettings.json
DqtApi/tests/DqtApi.Tests/DataverseIntegration/CreateTeacherTests.cs
DqtApi/tests/DqtApi.Tests/DataverseIntegration/CrmClientFixture.cs
DqtApi/tests/DqtApi.Tests/DataverseIntegration/GetMatchingTeachersTests.cs
README.md

Generate TRN from a REST API to be able to assign it immediately when creating a new teacher in DQT
rather than the Create / Update overhead which happens at the moment
A feature management controlled feature to be able to generate a TRN by calling the TRN Generation API.
To use the TRN Generation API to generete a TRN requires an appropriate deployment for that API + the feature to be enabled in DQT API.
-   [ x] Attach to Trello card
-   [ x] Rebased master
-   [x ] Cleaned commit history
-   [ x] Tested by running locally

Integrate trn generation api

---

DqtApi/src/DqtApi/V2/Handlers/GetOrCreateTrnRequestHandler.cs
DqtApi/tests/DqtApi.Tests/V2/Operations/GetOrCreateTrnRequestTests.cs

We have logic in place for HESA trainees to split the `FirstName` into `FirstName` and `Middlename` since we get all given names in a single field. This change extends the logic to work with overseas qualified teachers.

Always split FirstName into first & middle name

---

.github/dependabot.yml
Makefile
terraform/terraform.tf

Provider versions are changed inadvertently when `terraform plan` is ran locally.  It is preferable to manage this with dependabot.
- remove the upgrade arg from terraform init to prevent inadvertent upgrades when running plan locally
- pin providers to current patch version
- enable dependabot for terraform
Running `make dev terraform-plan` locally should result in no changes to `.terraform.lock.hcl` file

Managed terraform providers with dependabot

---

DqtApi/src/DqtApi/DataStore/Crm/Models/GeneratedOptionSets.cs
DqtApi/src/DqtApi/V2/ApiModels/IttProgrammeType.cs
docs/api-specs/v2.json

Adds a programme type for iQTS.
Adds `InternationalQualifiedTeacherStatus` option on `IttProgrammeType` and maps to corresponding CRM option set value.

Add iQTS programme type

---

.github/workflows/build.yml

Integration tests that are executed as part of the build use secrets that are stored in GitHub.  These are difficult to maintain and if dependabot is implemented fully will need to be duplicated.  Secrets are easier to manage in KeyVault and just as secure.
- Add steps to the build to download secrets from KeyVault
- Generate a random password for Postgres in the workflow.  This needs to exist before the build job starts to be set for the Postgres service that is span up as part of the build job
- Separate to the PR, add a JSON document to KeyVault that holds the secrets
- Check the logs for the build run to make sure the secrets aren't exposed
-   [x] Delete secrets from GitHub

Get integration test secrets from KeyVault

---

.github/workflows/build.yml

The default permissions for GitHub Actions and dependabot triggered jobs are different, Actions have broader write permissions, dependabot has read-only.  Explicitly setting the required permissions ensures that jobs triggered by either service will not encounter permissions errors.
Set permissions for build job.
- PR will trigger a GitHub Actions run, logs can be reviewed
- It won't be possible to test whether this change fixes dependabot PRs until it is merged, though if the explicit permissions work for GitHub Actions they should also work for dependabot

Add permissions to build job

---

DqtApi/src/DqtApi/V2/Handlers/GetTeacherHandler.cs
DqtApi/src/DqtApi/V2/Responses/GetTeacherResponse.cs
docs/api-specs/v2.json

We don't want internal CRM enums exposed on API endpoints. This fixes the v2 Get Teacher endpoint to use the `IttProgrammeType` API model, like we use elsewhere instead of the internal CRM `dfeta_ITTProgrammeType`.

Fix type of programmeType field on v2 Get Teacher endpoint

---

DqtApi/src/DqtApi/DataStore/Crm/CreateTeacherResult.cs
DqtApi/src/DqtApi/DataStore/Sql/Models/TrnRequest.cs
DqtApi/src/DqtApi/DqtApi.csproj
DqtApi/src/DqtApi/Migrations/20230208143135_AddIdentityUserIdAndLinkedToIdentity.Designer.cs
DqtApi/src/DqtApi/Migrations/20230208143135_AddIdentityUserIdAndLinkedToIdentity.cs
DqtApi/src/DqtApi/Program.cs
DqtApi/src/DqtApi/Properties/StringResources.resx
DqtApi/src/DqtApi/Services/GetAnIdentityApi/ClientCredentialsBearerTokenDelegatingHandler.cs
DqtApi/src/DqtApi/Services/GetAnIdentityApi/GetAnIdentityApiClient.cs
DqtApi/src/DqtApi/Services/GetAnIdentityApi/GetAnIdentityApiOptions.cs
DqtApi/src/DqtApi/Services/GetAnIdentityApi/GetAnIdentityApiUser.cs
DqtApi/src/DqtApi/Services/GetAnIdentityApi/IGetAnIdentityApiClient.cs
DqtApi/src/DqtApi/Services/GetAnIdentityApi/ServiceCollectionExtensions.cs
DqtApi/src/DqtApi/Services/LinkTrnToIdentityUserService.cs
DqtApi/src/DqtApi/V2/Handlers/GetOrCreateTrnRequestHandler.cs
DqtApi/src/DqtApi/V2/Requests/GetOrCreateTrnRequest.cs
DqtApi/src/DqtApi/Validation/ErrorRegistry.cs
DqtApi/src/DqtApi/WebhostEnvironmentExtensions.cs
DqtApi/tests/DqtApi.Tests/ApiFixture.cs
DqtApi/tests/DqtApi.Tests/Services/LinkTrnToIdentityUserServiceTests.cs
DqtApi/tests/DqtApi.Tests/V2/Operations/GetOrCreateTrnRequestTests.cs
docs/api-specs/v2.json

Added backgroundservice to sync teachers that have a trn & haven't been linked to an identity to call get-an-identity api.
https://trello.com/c/tY5RjJMH/610-add-support-to-dqt-api-for-passing-in-a-teacher-id-when-creating-a-contact-record
BackgroundService added.
Updated GetOrRequestTrn endpoint

Add IdentityUserId to getorcreate teacher endpoint & add background service to sync with get-an-identity

---

QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/FeatureFlags.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Services/TrnGenerationApi/ServiceCollectionExtensions.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/appsettings.json
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/CreateTeacherTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/CrmClientFixture.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/GetMatchingTeachersFixture.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/GetMatchingTeachersTests.cs

Now that TRN Generation API is rolled out everywhere we no longer need to keep its use behind a feature flag.

Remove UseTrnGenerationApi feature flag

---

.github/workflows/build.yml

The DB isn't exposed outside of the agent running the job so a fixed, public password is ok.

Remove workflow step that generates postgres password

---

QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Handlers/GetTeacherHandler.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Responses/GetTeacherResponse.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V2/Operations/GetTeacherTests.cs
docs/api-specs/v2.json

Husid required on the get teacher endpoint.
Register require husid to be returned from the get teacher endpoint. Husid has been added to both the ITT (dfeta_traineeid) response and Contact response (dfeta_HusID).

Added husid to get teacher endpoint

---

QualifiedTeachersApi/src/QualifiedTeachersApi/Dockerfile

We've added a new endpoint for the QTS certificate. The following error was thrown when trying to get the certificate from the deployed app:
FileNotFoundException: No Fonts installed on this device!
Install MS Core fonts in the docker build step

Install MS Core fonts to docker container for PdfSharpCore

---

QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.SetIttResultForTeacher.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.UpdateTeacher.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/UpdateTeacherCommand.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Properties/StringResources.Designer.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Properties/StringResources.resx
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Handlers/UpdateTeacherHandler.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Requests/UpdateTeacherRequest.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Validators/UpdateTeacherValidator.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/SetIttOutcomeForTeacherTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/UpdateTeacherTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V2/Operations/SetIttOutcomeTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V2/Operations/UpdateTeacherTests.cs
docs/api-specs/v2.json

Allow updates to deferred records via the API which will help register reduce the number of failed api calls.
[Include relevant motivation and context.](https://trello.com/c/q4tdHTvh/5269-allow-updates-to-deferred-records-via-the-api)
This change updates two endpoints to allow handling deferred/withdrawn ITT records.
- /v2/teacher/update
- /v2/teachers/{trn}/itt-outcome
Update to the endpoints allows updating records which are deferred/withdrawn based on programmetype. 
**The itt-outcome** endpoint has also been updated to no longer error if the ITT record is deferred and the request body is also Deferred, so that updates that DQT already know about do not cause register api call to fail. In this scenario we do not return an error, however also do not do an update.
-   [x] Attach to …

Allow updates to deferred records 

---

QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/CreateTeacherCommand.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Handlers/GetOrCreateTrnRequestHandler.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Requests/GetOrCreateTrnRequest.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Validators/GetOrCreateTrnRequestValidator.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/CreateTeacherTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V2/Operations/GetOrCreateTrnRequestTests.cs
docs/api-specs/v2.json

Regs have changed regarding overseas qualified teachers. This updates the TRN endpoint with new rules.
- Removes the `EuropeanEconomicArea` route.
- Add validation for `InitialTeachingTraining.TrainingCountry`.

Update TRN endpoint for new overseas regs

---

QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Handlers/GetTeacherHandler.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Responses/GetTeacherResponse.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/GetTeacherTests.cs
docs/api-specs/v3.json

QTS and EYTS are inconsistent with the way we specify NPQ details so need to align them. 
Tweak to get teacher response to make QTS and EYTS have their own section.
Simple change in API and test.

Nest qts and eyts data in own properties

---

QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/IDataverseAdapter.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Services/Certificates/CertificateGenerator.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Controllers/CertificatesController.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Handlers/GetInductionCertificateHandler.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Handlers/GetTeacherHandler.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Requests/GetInductionCertificateRequest.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Responses/GetTeacherResponse.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/GetInductionByTeacherTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/GetInductionCertificateTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/GetTeacherTests.cs
docs/api-specs/v3.json

Need to be able to generate induction certificate in qualifications v3 API to be consumed by new UI.
Code changes + tests + change to certificate generation to remove unncessary metadata
API / Dataverse adapter / tests

Add code and tests to support induction certificate v3 API endpoint

---

QualifiedTeachersApi/src/QualifiedTeachersApi/CacheKeys.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.SetIttResultForTeacher.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.UpdateTeacher.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/GetEarlyYearsStatusTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/GetInductionByTeacherTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/GetQualificationsForTeacherTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/GetTeacherStatusTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/SetIttOutcomeForTeacherTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/TestDataHelper.CreatePerson.cs

More and more Teacher statuses are being used in the dataverse adapter methods. This PR is to introduce a cache of teacher statuses so we do not have to fetch the teacher/eyts statuses every time we need them.
The Below tickets were the triggers for making the change. Register require more statuses in the setittoutcome/update endpoints, which would dramatically reduce performance. 
- https://trello.com/c/DWSeHva5/5303-when-a-trainee-is-awarded-in-register-and-its-already-awarded-in-dqt-error-if-the-qts-date-differs-between-the-services
- https://trello.com/c/kygTQwKa/5304-allow-the-unwithdrawal-of-a-withdrawn-record-in-dqt

Add teacher status cache

---

QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Handlers/GetTeacherHandler.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Responses/GetTeacherResponse.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Handlers/GetTeacherHandler.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Responses/GetTeacherResponse.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V2/Operations/GetTeacherTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/GetTeacherTests.cs
docs/api-specs/v2.json
docs/api-specs/v3.json

We’re building an Account page for a user to change their DQT name and this includes middle name. The current DQT API endpoints don’t include middle name but we need it to be able to play back the user’s current name completely.
Add a MiddleName property to the v2 and v3 ‘get teacher’ endpoints, mapped from the contact’s middlename attribute.

Add middle name to the V2 and V3 GET teachers endpoint

---

.github/workflows/actions/deploy-environment/action.yml

The action we use to download the CF CLI is currently broken as `curl`-like user agents are being blocked. This change copies the guts of the action and spoofs the user agent to make the download work.

Workaround CF CLI download issue

---

.github/workflows/build.yml

CRM integration tests are expensive to run. This change will skip those tests for PRs if none of the CRM integration files or their tests have been changed.

Don't run CRM integration tests if not required

---

QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.UpdateTeacher.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/UpdateTeacherResult.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Properties/StringResources.Designer.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Properties/StringResources.resx
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Handlers/UpdateTeacherHandler.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Validation/ErrorRegistry.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/UpdateTeacherTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V2/Operations/UpdateTeacherTests.cs

Register sometimes withdraw a teacher accidentally, and are unable to unwithdraw. This PR allows a teacher can be unwithdrawn to InTraining/Deferred.
https://trello.com/c/kygTQwKa/5304-allow-the-unwithdrawal-of-a-withdrawn-record-in-dqt-needs-working-out-of-technical-implementation
Added tests to the update teacher endpoint to verify it matches the following test matrix.
https://docs.google.com/document/d/1E10xuLPd3mw5rwi0JFoANMeIP3n1IyUqSYd8J3FiUrY/edit#heading=h.9gc6soagpn66
https://docs.google.com/spreadsheets/d/1WsINbQV7yvnYtl-3KkqZ63ji8B4RMgRQ9UXRfW359Fs/edit#gid=0

Allow Register to unwithdraw a teacher to deferred/intraining

---

QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Controllers/TeacherController.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Requests/GetTeacherRequest.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Validators/GetTeacherRequestValidator.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/GetTeacherByTrnTests.cs
docs/api-specs/v3.json

The Right to teach service needs to able to retrieve data for a teacher by a TRN. The existing v3 endpoints are authorised by an ID access token, which has a TRN baked in. We need an alternative endpoint where the TRN can be specified.
Add a `GET /v3/teachers/<trn>` endpoint. It should be authorised using the ApiKey authorization policy. It should return data in the same format as the existing /v3/teacher endpoint, for the TRN specified in the URL. If the TRN is not 7 digits, return a 400 response. If no teacher exists with the specified TRN, return a 404.

Add new v3 GET teachers endpoint with TRN parameter

---

QualifiedTeachersApi/src/QualifiedTeachersApi/CacheKeys.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.RequestBuilder.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/IDataverseAdapter.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Handlers/GetTeacherHandler.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Responses/GetTeacherResponse.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/GetTeacherByTrnTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/GetTeacherTestBase.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/GetTeacherTests.cs
docs/api-specs/v3.json

Properties are computed by looking for active `incident`s for the `contact`. I've had to omit tests for `GetIncidentsByContactId` since the `build` environment seems to be broken when transitioning incidents to completed.
This also moves some common test logic for the v3 teacher response into a base class.

Add Pending{Name|DateOfBirth} properties to v3 teacher response

---

QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Handlers/GetOrCreateTrnRequestHandler.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/CreateTeacherTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V2/Operations/GetOrCreateTrnRequestTests.cs

- Remove validation rule that stops the create endpoint from creating a new teacher when the husid is already being used by an existing teacher.
- Added Tests 
https://trello.com/c/Tp9TIkiT/5369-no-error-on-the-dqt-api-if-theres-an-existing-husid
- Removed validation rule
- Removed consume validation rule from hander
- Added tests 

Remove husid duplicate check on create endpoint

---

QualifiedTeachersApi/src/QualifiedTeachersApi/V3/AccessMode.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Controllers/TeacherController.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Controllers/TeachersController.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Handlers/GetTeacherHandler.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Requests/GetTeacherRequest.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Responses/GetTeacherResponse.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.TestCommon/AssertEx.Http.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/GetTeacherByTrnTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/GetTeacherTestBase.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/GetTeacherTests.cs
docs/api-specs/v3.json

Certificates are only available when the caller is authorised using an ID access token. Remove the various `certificateUrl` properties from the `/v3/teachers/{trn}` response since that's not authorised the same way.

Remove certificate URL properties when they're not accessible

---

.github/workflows/build.yml

We run tests on PR and we enforce linear history so there's no value in running tests on pushes to main.

Don't run tests on pushes to main

---

.github/workflows/build.yml

Similar to https://github.com/DFE-Digital/qualified-teachers-api/pull/453 there's no value running linting on pushes to main.

Skip lint on pushes to main

---

QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Handlers/GetOrCreateTrnRequestHandler.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/CreateTeacherTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V2/Operations/GetOrCreateTrnRequestTests.cs

This reverts commit b2a9c9eb494344ceb98319b97d0ba782fc305dd0.
This commit was merged previously, but does not behave how dqt want this to behave. Backing changes out until changes have been done that match the existing dqt dup matching.
https://trello.com/c/Tp9TIkiT/5369-no-error-on-the-dqt-api-if-theres-an-existing-husid

Revert "Remove husid duplicate check on create endpoint (#446)"

---

QualifiedTeachersApi/src/QualifiedTeachersApi/Services/GetAnIdentity/WebHooks/GetAnIdentityEndpoints.cs

Signatures are a hex string; a difference in casing shouldn't fail the equality check.

Use case-insensitive comparison for webhook signature checking

---

QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Handlers/GetOrCreateTrnRequestHandler.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/CreateTeacherTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V2/Operations/GetOrCreateTrnRequestTests.cs

https://trello.com/c/Tp9TIkiT/5369-no-error-on-the-dqt-api-if-theres-an-existing-husid
- Remove duplicate check on husid & follow existing dupliate check logic by creating a new crm task to review in the future.
- Removed old test
- added two new tests

Remove Husid Duplicate check

---

.github/workflows/build.yml

The Cloud Foundry Terraform provider corrupts its own state when terraform apply is cancelled mid-way, as happens when GitHub cancels the workflow because there's a newer commit.

Don't cancel in-flight builds for same branch

---

QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Handlers/FindTeachersHandler.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Responses/FindTeacherResult.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.TestCommon/AssertEx.Http.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.TestCommon/AssertEx.Json.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.TestCommon/QualifiedTeachersApi.TestCommon.csproj
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V1/Operations/GetTeacherTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V2/Operations/FindTeachersTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V2/Operations/GetOrCreateTrnRequestTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V2/Operations/GetTeacherTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V2/Operations/SetIttOutcomeTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V2/Operations/SetNpqQualificationTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V2/Operations/UnlockTeacherTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V2/Operations/UpdateTeacherTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/CreateDateOfBirthChangeTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/CreateNameChangeTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/GetTeacherTestBase.cs

Switch to using `System.Text.Json` like we use in the app itself and in ID.
I've ported the `AssertEx` types from ID and made a few fixes, which will be back-ported to ID.

Remove Newtonsoft from tests

---

.github/workflows/build.yml

Mirroring change made in ID:
The lint step of our build is becoming slow, since we scan the entire solution. This change amends the step to only lint changed files for PR builds.

Only lint changed files for PR builds

---

QualifiedTeachersApi/src/QualifiedTeachersApi/Infrastructure/Swagger/SchemaGenerator.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Program.cs

Swashbuckle's built-in `ISchemaGenerator` can't handle `Option<T>` types correctly and it's unfortunately not easily extensible. This copies the in-box implementation an adds support for these types.
This is a quick fix; the long-term solution will use NSwag instead of Swashbuckle and we can look at a proper solution during migration.

Fix v3 swagger gen for Option<T> members

---

.github/workflows/actions/deploy-environment/action.yml
.github/workflows/build.yml
QualifiedTeachersApi/QualifiedTeachersApi.sln
QualifiedTeachersApi/src/QtCli/Program.cs
QualifiedTeachersApi/src/QtCli/QtCli.csproj
QualifiedTeachersApi/src/QualifiedTeachersApi/Dockerfile
QualifiedTeachersApi/src/QualifiedTeachersApi/QualifiedTeachersApi.csproj
QualifiedTeachersApi/src/QualifiedTeachersApi/entrypoint.sh
terraform/api-app.tf
terraform/variables.tf

Adds the beginnings of a new CLI app with DB migration the only support command for now.
Bundles this CLI tool with the API app itself and adds an entrypoint.sh script that deploys the DB changes from the app's container instead of via Terraform.
This tool will be extended in future for both the AKS migration (to run migrations from an init container, perhaps) and also to deploy changes to the MSSQL reporting DB.

Deploy DB changes from app's Docker container

---

QualifiedTeachersApi/src/QualifiedTeachersApi/Infrastructure/Json/JsonSerializerOptionsExtensions.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Infrastructure/Json/NotificationEnvelopeConverter.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Services/GetAnIdentity/WebHooks/GetAnIdentityEndpoints.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Services/GetAnIdentity/WebHooks/INotificationMessage.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Services/GetAnIdentity/WebHooks/NotificationEnvelope.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Services/GetAnIdentity/WebHooks/UserCreatedHandler.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Services/GetAnIdentity/WebHooks/UserCreatedMessage.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Services/GetAnIdentity/WebHooks/UserCreatedRequest.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/Services/GetAnIdentity/WebHooks/GetAnIdentityEndpointsTests.cs

We’re adding a new web hook message type for when users are created. We need to handle this and update the corresponding DQT record in the same way we do for the UserUpdated messages.
Change to webhook receiver endpoint and additional handler for user created messages.
N/A

Added code to receive user created messages via webhook

---

QualifiedTeachersApi/src/QtCli/Commands.MigrateDb.cs
QualifiedTeachersApi/src/QtCli/Commands.MigrateReportingDb.cs
QualifiedTeachersApi/src/QtCli/Commands.ResetReportingDbJournal.cs
QualifiedTeachersApi/src/QtCli/Program.cs
QualifiedTeachersApi/src/QtCli/Properties/launchSettings.json
QualifiedTeachersApi/src/QualifiedTeachersApi/QualifiedTeachersApi.csproj
QualifiedTeachersApi/src/QualifiedTeachersApi/Services/DqtReporting/Migrator.cs

Since we're inheriting an existing schema, using SQL scripts is going to be the simplest way for performing updates. This adds DbUp and some tooling around it to update the DB.
In addition, there's another command to update DbUp's journal table to mark `Initial.sql` is applied; we will need this when we roll the process out onto the existing databases since they'll already have this schema in place.

Add tooling to upgrade the reporting DB schema

---

QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.SetIttResultForTeacher.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/SetIttResultForTeacherResult.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Handlers/SetIttOutcomeHandler.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/SetIttOutcomeForTeacherTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V2/Operations/SetIttOutcomeTests.cs

Register require an update to the **v2/setittoutcome** endpoint to stop error'ing when the asessement date matches the one that dqt hold. In Addition, to reject an update if the assessment date differs.
https://trello.com/c/DWSeHva5/5303-award-api-endpoints-should-be-idempotent
- Update to the dataverse update operation to handle update when a teacher has qts/eyts. 
- Update to the tests to handle returning errors when assessment date differs from the one dqt holds.
- added new tests to show that passing a pass to dqt that dqt already know about does not return an error.

Reject update when assessment date differs from the one dqt hold

---

QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.UpdateTeacher.cs

When fetching ITT records that are not associated with an establishment, the api fails and returns a 500 error. This fixes this problem.
bug fix.

Bugfix to handle ITT records with no establishmentid

---

.github/workflows/build.yml
QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/IDataverseAdapter.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Program.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Services/CrmEntityChanges/DataverseCrmEntityChangesService.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Services/CrmEntityChanges/ServiceCollectionExtensions.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Services/DqtReporting/DqtReportingOptions.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Services/DqtReporting/DqtReportingService.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Services/DqtReporting/Migrator.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Services/DqtReporting/ServiceCollectionExtensions.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/appsettings.Development.json
QualifiedTeachersApi/src/QualifiedTeachersApi/appsettings.json
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/ApiFixture.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/ApiTestBase.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/CrmClientFixture.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DbFixture.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/Infrastructure/TestConfiguration.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/QualifiedTeachersApi.Tests.csproj
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/Services/DqtReportingFixture.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/Services/DqtReportingServiceTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/Startup.cs

Adds the core implementation of the DQT Reporting service. This uses the `ICrmEntityChangesService` previously added and writes the results to a SQL Server DB. 
For now this is disabled on deployed environments until we've got the initial migration, configuration and monitoring components added.

Base DQT reporting service

---

terraform/api-app.tf
terraform/dqt-reporting.tf
terraform/storage.tf

Tags are automatically applied in our Azure subscriptions. Without this Terraform thinks a change is required on every run.

Ignore tag changes on Azure resources

---

QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.cs

We've had an error in prod ID because the result from a Find call doesn't have a TRN.

Ensure results from Find operation have a TRN

---

.github/workflows/actions/test/action.yml
.github/workflows/pr.yml
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/ApiFixture.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/Infrastructure/TestConfiguration.cs

We used to prevent more than one `build` step running at once but that's a little too coarse-grained and it's causing workflows to get cancelled and removed from the merge queue. The aspect that isn't safe to run concurrently is the CRM integration tests. They have their own concurrency check built in and I've split that out into its own step to ensure the lock is held for as short a time as possible.

Reduce PR workflow contention

---

QualifiedTeachersApi/src/QualifiedTeachersApi/Services/DqtReporting/EntityTableMapping.cs

A new attribute - `msft_datastate` - has magically appeared in metadata over the weekend and our DB schema doesn't have it. The production reporting DB, populated by DES, doesn't have it either so I'm skipping it for now.
Also adds some `DebuggerDisplayAttribute`s so it's easier to pick out attributes when debugging.

Ignore msft_datastate attribute

---

QualifiedTeachersApi/src/QtCli/Commands.ResetReportingDbChangeCursor.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Services/CrmEntityChanges/CrmEntityChangesService.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Services/CrmEntityChanges/ICrmEntityChangesService.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Services/DqtReporting/DqtReportingService.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/Services/DqtReportingFixture.cs

Previously we've used the `ChangesKey` for retrieving a named CRM `ServiceClient`. We may want to have multiple change keys to a single named ServiceClient. This adds an additional parameter to avoid the conflation.

More explicit ServiceClient for DqtReportingService

---

QualifiedTeachersApi/src/QualifiedTeachersApi/Infrastructure/Json/Modifiers.cs

The whole point of `Option<T>` properties is that they're optional.

Ensure Option<T> properties are not required

---

QualifiedTeachersApi/src/QualifiedTeachersApi/Migrations/20230519120619_RequiredTrnRequestTeacherId.Designer.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Migrations/20230519120619_RequiredTrnRequestTeacherId.cs

A previous change made the model property non-nullable, this updates the DB schema to match.

Make teacher_id column of trn_requests table non-nullable

---

QualifiedTeachersApi/src/QualifiedTeachersApi/Filters/SupportsReadOnlyMode.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Program.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V1/Controllers/TeachersController.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Controllers/IttProvidersController.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Controllers/NpqQualificationsController.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Controllers/TeachersController.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Controllers/UnlockTeacherController.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Controllers/CertificatesController.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Controllers/TeacherController.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Controllers/TeachersController.cs

When we move the DQT API from PAAS to AKS we want to do it without impacting the availability of services that depend on the API. The reason for the migration incurring down time is the database move; writes need to be stopped to the existing DB so that it can be copied and restored in the new DB without missing any data. Most of our endpoints don’t actually use the DB, they talk to CRM directly, so we don’t need to take these endpoints down.
This change adds a filter that checks the `ReadOnlyMode` value from configuration. If that value is `true`, requests to any endpoints that are not decorated with `SupportsReadOnlyMode` will return a `503` response.

Add read-only mode

---

QualifiedTeachersApi/src/QualifiedTeachersApi/Program.cs

We now have better ways of setting up a DB for development; this is just extra startup cost.

Don't try to create DB on startup

---

QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Sql/DqtContext.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Sql/Mappings/EventMapping.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Sql/Models/Event.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Events/DummyEvent.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Events/EventBase.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Events/Processing/IEventObserver.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Events/Processing/NoopEventObserver.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Events/Processing/PublishEventsBackgroundService.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Events/Processing/ServiceCollectionExtensions.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Migrations/20230522115339_Events.Designer.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Migrations/20230522115339_Events.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DisableParallelization.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/Events/Processing/PublishEventsBackgroundServiceTests.cs

For the automated QTS emails we need to log who we’ve emailed and when. ID uses an event system that is used to record all data changes that works well and could be replicated here and used everywhere for TRS going forward.
Port code from identity.
There are no "real" events yet so a DummyEvent has been temporarily created to allow the event publishing to be tested.

Ported the Events feature from get an identity

---

QualifiedTeachersApi/src/QualifiedTeachersApi/Services/DqtReporting/DqtReportingService.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/Services/DqtReportingFixture.cs

I went a little overboard when adding metrics to the first iteration of the `DqtReportingService`. In reality, we only use one: total updates processed. This PR removes the fine grained metrics to emit only one - `updates processed`. We issue one of those for each entity type, instead of one per tick of the timer.

Reduce DqtReportingService metrics to the one we actually use

---

QualifiedTeachersApi/src/QualifiedTeachersApi/Services/DqtReporting/Migrations/0006_Incident_msdyn_copilotengaged.sql

Somehow this column already exists in prod; I suspect it may be that the prod CRM instance had this column added before we turned off Data Export Service.

Fix migration in prod

---

QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Handlers/GetTeacherHandler.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Requests/GetTeacherRequest.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Responses/GetTeacherResponse.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/GetTeacherByTrnTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/GetTeacherTestBase.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/GetTeacherTests.cs

To be able to move to the v3 endpoints, Claim need HE qualifications to be returned.
Amend the `/v3/teacher` and `/v3/teachers/{trn}` endpoints to accept an additional `Includes` parameter - `HigherEducationQualifications`. When this is specified in the request, include an additional block in the response with the following schema:
```json
{
"higherEducationQualifications": [
{
"name": "",
"awarded": "YYYY-MM-DD",
"subjects": [
{
"code": "",
"name": ""
}
]
}
]
}
```
N.B. We don’t always have an awarded date, so the `awarded` property will have to be nullable.
Change to V3 endpoint + tests

Added HigherEducationQualifications section to V3 endpoints

---

QualifiedTeachersApi/src/QualifiedTeachersApi/Infrastructure/Logging/WebApplicationBuilderExtensions.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Program.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/appsettings.Development.json
QualifiedTeachersApi/src/QualifiedTeachersApi/appsettings.Testing.json
terraform/api-app.tf

- Rename `paasEnvironmentName` to `platformEnvironmentName`.
- Don't host a metrics endpoint unless we're running on PAAS.

Initial changes to support running on AKS

---

QualifiedTeachersApi/src/QualifiedTeachersApi/Infrastructure/OpenApi/OpenApiEndpointsStartupFilter.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Controllers/CertificatesController.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Handlers/GetNpqCertificateHandler.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Requests/GetNpqCertificateRequest.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/wwwroot/docs/swagger-custom.js
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/GetNpqCertificateTests.cs

The endpoint that returns a NPQ certificate takes a qualification ID parameter (since a teacher can have multiple). We don’t currently check that the current user owns the qualification specified which could allow a teacher to get a certificate for a qualification that isn’t their own.
Add an additional check to the GetNpqCertificateHandler that the qualification specified belongs to the currently authenticated teacher. If it does not, return null from the handler.
N/A

Added check to get NPQ certificate that the qualification Id is associated with the authenticated user

---

QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/CreateTeacherCommand.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/IDataverseAdapter.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/Models/AttributeConstraints.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Properties/StringResources.Designer.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/Properties/StringResources.resx
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Handlers/GetOrCreateTrnRequestHandler.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Handlers/GetTrnRequestHandler.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Requests/GetOrCreateTrnRequest.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Responses/TrnRequestInfo.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Validators/GetOrCreateTrnRequestValidator.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/CreateTeacherTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/GetTeachersByInitialTeacherTrainingSlugIdTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V2/Operations/GetOrCreateTrnRequestTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V2/Operations/GetTrnRequestTests.cs

SlugId is required to be passed to the create endpoint so that register can do a 1-2-1 lookup of a record on the dqt api, rather than doing a dob match. This PR adds slugid to the body of the create request for contact & Initial Teacher Training.
https://trello.com/c/cawVJEpO/5523-add-slugid-to-create-dqt-api-getorcreateteacher-endpoint
- Add SlugId to body of request.
- Update tests
- Make sure that a duplicate task is created when slugid is used by another contact.
- Include SlugId on the GetTeacherRequest
- Include SlugId on the GetOrCreateTeacher response if a duplicate is detected.
- Add Validation so that slugid is required if teachertype is traineeteacher.
- …

Add slugid getorcreatetrnrequest

---

QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Handlers/FindTeachersHandler.cs
QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Responses/FindTeacherResult.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/GetTeachersByInitialTeacherTrainingSlugIdTests.cs
QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V2/Operations/FindTeachersTests.cs

ID needs a teacher’s middle name to be able to use it for the created ID account without an additional API call.
Add MiddleName to each result on the V2 find endpoint’s response.

Add middle name to V2 find teachers response

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/Services/DqtReporting/DqtReportingService.cs

We see SQL timeout exceptions from time to time from the reporting service and they're not currently treated as transient (meaning they're logged as errors and the service shuts down). This change is to treat those errors as transient. There doesn't seem to be a nicer way of checking these other than matching on the exception's `Message`.

Treat SQL timeout exceptions as transient

---

terraform/aks/app.tf
terraform/paas/app.tf

`ReadOnlyMode` is a mode the API can run in where the endpoints that require a local database are disabled. This is done so that we can migrate from PAAS to AKS with only partial unavailability. This change sets the flag for AKS environments to `true` in preparation for that move. I've also set it explicitly for PAAS environments to `false` so it's easy to see where to flip the values when the time comes.

Add ReadOnlyMode config value for AKS and PAAS environments

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/GetEytsCertificateHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/GetNpqCertificateHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/GetQtsCertificateHandler.cs

When executing in different environments date on certificates is in different (longer format).
Amend so that date is always in the same format independent of current culture.
N/A

Amended to make format of dates on certificates independent of current culture

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/DataStore/Crm/DataverseAdapter.SetIttResultForTeacher.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/DataStore/Crm/DateTimeExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/DateOnlyExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Handlers/GetOrCreateTrnRequestHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Handlers/GetTeacherHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Handlers/GetTrnRequestHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Validators/SetNpqQualificationValidator.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Endpoints/FindTeachersEndpoint.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/GetEytsCertificateHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/GetInductionCertificateHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/GetNpqCertificateHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/GetQtsCertificateHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/GetTeacherHandler.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/DataverseIntegration/CreateDateOfBirthChangeIncidentTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/CreateDateOfBirthChangeTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetTeacherTestBase.cs

Most custom fields in DQT have incorrectly been set up as local instead of UTC. This change applies a correction before we truncate the `DateTime` to a `DateOnly`.

Fix DQT dates for BST

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/DataStore/Crm/DataverseAdapter.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/DataStore/Crm/IDataverseAdapter.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Infrastructure/Json/JsonSerializerOptionsExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Services/GetAnIdentity/WebHooks/GetAnIdentityEndpoints.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Services/GetAnIdentity/WebHooks/UserUpdatedHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Services/GetAnIdentity/WebHooks/UserUpdatedMessage.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Services/GetAnIdentity/WebHooks/UserUpdatedRequest.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/DataverseIntegration/ClearTeacherIdentityInfoTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/Services/GetAnIdentity/WebHooks/GetAnIdentityEndpointsTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TeachingRecordSystem.TestCommon.csproj

If a TRN is unlinked from an ID account then remove the link in DQT too. The fields that were synchronised are left untouched.
Also separated webhook-specific serializer configuration out from the main API serializer settings as they may well need to vary. Amended tests to avoid double serialization too.

Handle a removed TRN in ID webhook

---

.github/workflows/actions/deploy-aks-environment/action.yml
.github/workflows/deploy-dev.yml
.github/workflows/package.yml
.github/workflows/pr.yml
TeachingRecordSystem/src/TeachingRecordSystem.Cli/Dockerfile
justfile
terraform/aks/app.tf
terraform/aks/variables.tf

This uses a kubernetes job that invokes the `trscli`. The API and UI deployments are made dependent on this job so that they're not deployed until the job completes successfully.

Deploy DB migrations to k8s environments

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/DataStore/Crm/DataverseAdapter.UpdateTeacher.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Properties/StringResources.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Properties/StringResources.resx

ITT records that do not have a programme type causes a NRE. This PR fixes it.
- stop NRE
- Fixed StringResources typo.

Fix NRE for programmetype on update endpoint

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/DataStore/Crm/DataverseAdapter.GetInternationalQtsAwardeesForDateRange.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/DataStore/Crm/DataverseAdapter.GetQtsAwardeesForDateRange.cs

This gives us symmetry with how we're finding the statuses in the Set ITT outcome endpoint.

Use teacher status values instead of names in queries

---

.github/workflows/pr.yml
README.md
TeachingRecordSystem/.config/dotnet-tools.json
TeachingRecordSystem/TeachingRecordSystem.sln
TeachingRecordSystem/nuget.config
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/Certificates/CertificateGeneratorTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/TeachingRecordSystem.Core.Tests.csproj
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/TestProject.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/TestStartup.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Usings.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestFramework/GitHubReport.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestFramework/TestConfigurationExtensions.cs
justfile

Also adds fixie and dotnet-format to a tool manifest and adds a just recipe to install them.

Migrate Core.Tests project to new TestFramework

---

.github/workflows/pr.yml

This means we can avoid Azure sign in, Key Vault read, and an `mssql` container (which takes ~ 1.5 minutes by itself) when we don't need it.

Split DQT tests into their own job

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/GetTeacherHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Responses/GetTeacherResponse.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetTeacherTestBase.cs

The ID support console needs to display the DQT email before a TRN is assigned. This adds an `Email` property to the response object.

Add Email to v3 Teacher responses

---

TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/TeachingRecordSystem.Core.Tests.csproj
TeachingRecordSystem/tests/TeachingRecordSystem.TestFramework/Execution.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestFramework/InlineDataAttribute.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestFramework/MemberDataAttribute.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestFramework/TestArguments.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestFramework/TrsTestFrameworkException.cs

Similar to xUnit, we have `[InlineData]` and `[MemberData]`. I've kept the same `[Test]` attribute we use for parameter-less tests.

Add support for data-driven tests to TestFramework

---

.github/workflows/deploy-preprod.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-test.yml

The `concurrency` elements for test, pre-prod and prod weren't moved up to the workflow level when we added AKS environments, this fixes that.
In addition, adds the `package` dependency for the pre-prod AKS deployment so that manual workflow runs work correctly.

Fix up environment deployment concurrency

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/Jobs/BatchSendEytsAwardedEmailsJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Jobs/BatchSendInductionCompletedEmailsJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Jobs/BatchSendInternationalQtsAwardedEmailsJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Jobs/BatchSendQtsAwardedEmailsJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/EytsAwardedEmailsJobItemMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/InductionCompletedEmailsJobItemMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/InternationalQtsAwardedEmailsJobItemMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/QtsAwardedEmailsJobItemMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20230726141836_EmailJobTrnUniqueConstraints.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20230726141836_EmailJobTrnUniqueConstraints.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/EytsAwardedEmailsJobItem.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/InductionCompletedEmailsJobItem.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/InternationalQtsAwardedEmailsJobItem.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/QtsAwardedEmailsJobItem.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/Jobs/EytsAwardedEmailJobDispatcherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/Jobs/InductionCompletedEmailJobDispatcherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/Jobs/InternationalQtsAwardedEmailJobDispatcherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/Jobs/QtsAwardedEmailJobDispatcherTests.cs

Adds a unique constraint on `TRN` for each email job plus an explicit check. It would have been nice to have some kind of `TryAdd()` method on the `DbSet` but EF doesn't have one and adding one proved to be non-trivial.

Ensure we don't send emails to a given user more than once

---

TeachingRecordSystem/src/TeachingRecordSystem.Dqt/DataverseAdapter.SetIttResultForTeacher.cs
TeachingRecordSystem/src/TeachingRecordSystem.Dqt/DataverseAdapter.UpdateTeacher.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Dqt.Tests/DataverseAdapterTests/SetIttOutcomeForTeacherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Dqt.Tests/DataverseAdapterTests/UpdateTeacherTests.cs

This bugfix addresses problems with dead jobs that register received last night after they implemented the slugid changes. This PR introduces a fallback so that when slugid is passed and there isn't a match, it drops back to what it was doing previously before the slugid changes.
- updated tests.
- updated datavers method.

Bugfix for slugid fallback

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/EytsAwardedEmailsJobItemMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/InductionCompletedEmailsJobItemMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/InternationalQtsAwardedEmailsJobItemMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/QtsAwardedEmailsJobItemMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20230727111104_RemoveEmailJobTrnUniqueConstraints.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20230727111104_RemoveEmailJobTrnUniqueConstraints.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/EytsAwardedEmailsJobItem.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/InductionCompletedEmailsJobItem.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/InternationalQtsAwardedEmailsJobItem.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/QtsAwardedEmailsJobItem.cs

We'll rely on the explicit checks in the jobs instead.

Remove unique constraints - existing data means we can't apply them

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/GetTeacherHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/DataverseAdapter.DetailChangeIncidents.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/DataverseAdapter.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/IDataverseAdapter.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetTeacherTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/DataverseAdapterTests/GetSubjectByTitleTests.cs

We're caching this entity so need to ensure we're retrieving all columns.

Remove the columnNames parameter from GetSubjectByTitle

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Services/DqtReporting/Migrations/0007_ContactAllowpiiUpdatesFromRegister.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj

CRM is going to be changed to include a new field - dfeta_allowpiiupdatesfromregister, therefore the reporting database needs to be updated to include the new field.
https://trello.com/c/q1cEHrN5/1132-ensure-pii-updates-are-not-overwritten

Add [dfeta_allowpiiupdatesfromregister] field to reporting database

---

scripts/Generate-CrmModels.ps1

Running .\gEnerate-CrmModels.ps1 creates a new generated code different to where the GeneratedCode.cs is currently. This PR fixes the namespace to where GeneratedCode is now.

changed script to change namespace of generatedcode to match where it's stored

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Handlers/GetOrCreateTrnRequestHandler.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V2/Operations/GetOrCreateTrnRequestTests.cs

Consume when a qualification is not found and stop endpoint from throwing an exception.
- Added code to consume error.
- Added test to handle when the createteacher returning QualificationNotFound
- changed existing test because it was invalid. It errors for a different reason - before getting to the createteacher code (json could not be convertered to type e.g.
```
"errors": {
"$.qualification.heQualificationType": [
"The JSON value could not be converted to System.Nullable`1[TeachingRecordSystem.Api.V2.ApiModels.HeQualificationType]. Path: $.qualification.heQualificationType | LineNumber: 35 | BytePositionInLine: 32."
] 
```
-   [] …

Consume qualification not found error

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/GetTeacherHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Models/ContactExtensions.cs

We've previously assumed that `contact` records will always have a first and last name but it turns out that's not always true. This amends our name resolution methods to not throw when first and/or last name is missing.
I've also updated one call site to use the helper methods where it wasn't before.

Handle missing first/last names in v3 endpoints

---

TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/FakeServiceClient.cs

This is the first iteration of a fake, in-memory implementation of CRM's `IOrganizationService{Async}`. For now it has limited support for simple CRUD operations and `RetrieveMultiple` queries (that don't contain joins). This will be added to over time.
The intention is that we move away from mocks and calling the real CRM where we can both to improve developer productivity and test run times.

Beginnings of in-memory fake of ServiceClient

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/CrmQueryDispatcher.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/ICrmQueryDispatcher.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/ICrmQueryHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/GetContactByTrnHandler.cs

There's really no safe way to use `RequestBuilder` with these new handlers.

Remove RequestBuilder from CRM query handler interface

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/UserActivationEventChanges.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/UserDeactivatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/EditUserTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateUser.cs

We need to be able to deactivate users who should no longer have access to the TRS Support Console.
- added changes to deactivate a user
- added relevant test
I've had to use the prefix `OnPost` as per the [MS Docs](https://learn.microsoft.com/en-gb/aspnet/core/razor-pages/?view=aspnetcore-7.0&tabs=visual-studio#multiple-handlers-per-page) for the new method (`OnPostDeactivate`). Also made use of `asp-page-handler` which will render as `formaction` in the markup
-   [#1180] Attach to Trello card

added functionality to deactivate a user

---

TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/DataverseAdapterTests/GetActiveIncidentsTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/CrmTestData.CreateDateOfBirthChangeIncident.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/CrmTestData.CreateNameChangeIncident.cs

Also amended the builders to take in an existing contact ID rather than creating one. This is so that the `TestData` methods are easier to use together.
The `With*` methods are also amended to throw if the property they're setting has already been set (to something different). This is a useful pattern so that the builders can more-easily ensure the state they're setting up is valid, and it's consistent with what we're doing in `TestData.CreatePerson()`.

Return TicketNumber from TestData.CreateIncident* methods

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Services/CrmEntityChanges/CrmEntityChangesService.cs

We have a Sentry error caused by an `InsufficientMemoryException` retrieving entity changes for the reporting service. This adds additional error handling for that exception by reducing the page size and retrying the query.

Retry with a smaller page size on InsufficientMemoryException

---

terraform/aks/app.tf
terraform/aks/variables.tf
terraform/aks/workspace_variables/dev.tfvars.json
terraform/aks/workspace_variables/pre-production.tfvars.json
terraform/aks/workspace_variables/production.tfvars.json
terraform/aks/workspace_variables/test.tfvars.json
terraform/paas/app.tf
terraform/paas/variables.tf
terraform/paas/workspace_variables/dev.tfvars.json
terraform/paas/workspace_variables/pre-production.tfvars.json
terraform/paas/workspace_variables/production.tfvars.json
terraform/paas/workspace_variables/test.tfvars.json

When we're switching from PAAS to AKS for a particular environment we need to flip the platform that's running DQT Reporting Service, recurring jobs and in read only mode. This change exposes the three config values that control those things as tfvars for both AKS and PAAS environments.

Expose configuration for migrating from PAAS to AKS as tfvars

---

terraform/paas/workspace_variables/test.tfvars.json

We don't have schedule configuration defined here so the service is blowing up on startup.

Disable background jobs on test environment

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/CancelIncidentQuery.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/RejectIncidentQuery.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/CancelIncidentHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/RejectIncidentHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/EnumExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Cases/EditCase/Reject.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Cases/EditCase/Reject.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/QueryTests/CancelIncidentTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/QueryTests/RejectIncidentTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Cases/EditCase/RejectTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/Infrastructure/FakeXrmEasy/FakeMessageExecutors/WorkaroundCloseIncidentRequestExecutor.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/ServiceCollectionExtensions.cs

We’re moving the view/approve/decline change of name & DOB processes into the new TRS Support Console.
Add the /cases/{id}/reject page following the designs in Figma.
The back link should go to /cases/{id}.
If the specified case does not exist, return a 404.
If the specified case’s state is not Active, return a 400.
Show a selection of radio buttons with rejection reasons, as per the designs. If Confirm is clicked without an option being selected, show an error ‘Select the reason for rejecting this change’.
When Confirm is clicked, set the case’s status to Rejected with an incident resolution status matching the selected rejected reason, and redirect to /cases with a success notification banner, as shown in the designs.
Change no longer required is a special case which should cause the …

Reject change of dob or name page

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/ApproveIncidentQuery.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/ApproveIncidentHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Cases/EditCase/Accept.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Cases/EditCase/Accept.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/QueryTests/ApproveIncidentTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Cases/EditCase/AcceptTests.cs

We’re moving the view/approve/decline change of name & DOB processes into the new TRS Support Console.
Add the /cases/{id}/accept page following the designs in Figma .
The back link should go to /cases/{id}.
If the specified case does not exist, return a 404.
If the specified case’s state is not Active, return a 400.
Show a summary list with the current and requested names or DOBs, as appropriate.
When Confirm is clicked, set the case’s status to Approved with an incident resolution status of Approvedand redirect to /cases with a success notification banner, as shown in the designs.
UI + CRM query + tests.

Accept change of dob or name page

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/ApiModels/SanctionInfo.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Constants.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/FindTeachersHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/GetTeacherHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Responses/FindTeachersResponse.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Responses/GetTeacherResponse.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/FindTeachersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/CrmTestData.CreatePerson.cs

This makes the `sanctions` property consistent with the detail endpoint. Also fixes and issue where we were returning sanction codes that we shouldn't have been.
I've started to move over collection types to `ImmutableArray<T>` too as discussed separately.

Expose more sanction details on Find endpoint

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Models/ContactDetail.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Models/ContactExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/GetContactDetailByIdQuery.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/GetContactDetailByIdHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/GetContactsByLastNameAndDateOfBirthHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/QueryTests/GetContactByTrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/QueryTests/GetContactDetailByIdTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/CrmTestData.CreatePerson.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/CrmTestData.cs

We need a way for support staff to view a person’s record in TRS.
Add a new page at /persons/{personId}.
Within the General tab, show the name (first, middle & last), date of birth, TRN, email address and mobile number. For any empty fields, show ‘Not provided’. Change links are out of scope of this ticket.
The back link should go to /persons (a stub page).
If there is no contact in DQT with the specified personId (personId == DQT contact ID) return a 404.
The Alerts and Change log tabs are out of scope of this ticket.
For now, every user can access this page.
Crm Query + UI + tests

Initial iteration of person view

---

README.md
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/.gitignore
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_Layout.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TeachingRecordSystem.SupportUi.csproj
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/libman.json
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/wwwroot/Styles/site.css
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/wwwroot/Styles/site.scss
justfile

We need a way to define styles that can use variables from the base GDS library as well as, potentially, importing components from other design systems e.g. MOJ.
Add SASS to the SupportUi in the same way it’s set up in [GitHub - DFE-Digital/get-an-identity](https://github.com/DFE-Digital/get-an-identity)
The project file, build workflow, docs will all need updating. Use libman to reference the GDS library.
N/A

Added SASS to the UI and build workflow

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TeachingRecordSystem.SupportUi.csproj
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/libman.json
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/wwwroot/Styles/site.scss

The designs use the ‘sub navigation’ component from MOJ styles rather than the stock GDS Tabs component. Now that we have SASS setup, we can add these component styles and update the UI.
Add the relevant styles from https://design-patterns.service.justice.gov.uk/components/sub-navigation/  and update the Person view page to use them.
Simplish change

Update tab styles on Person view page

---

terraform/domains/environment_domains/config/dev.tfvars.json

Migration of dev environment to AKS
Update the custom domain configuration
This was deployed manually already: https://dev.teacher-qualifications-api.education.gov.uk/health

[635] Point dev domain at the AKS environment

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/Program.cs

When we're migrating environments from PAAS to AKS and flipping read-only mode on and off it would be useful to be able to query whether a particular environment is in read-only mode. This adds a `/_readonlymode` endpoint which outputs `true` or `false`, as appropriate.

Add a /_readonlymode endpoint

---

terraform/domains/environment_domains/config/pre-production.tfvars.json

Migration of the preproduction environment
Point preprod.teacher-qualifications-api.education.gov.uk at AKS
Access https://preprod.teacher-qualifications-api.education.gov.uk/health

[636] Migrate preproduction domain from PaaS to AKS

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Services/DqtReporting/Migrations/0009_EvergreenMissingColumns2.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj

Evergreen update has added new columns to the contact entity, this PR adds the missing columns to the reporting database.
https://trello.com/c/yKx8t0Mu/1221-microsoft-dynamics-wave-2-2023-updates-evergreen-updates

Add evergreen missing columns to contact

---

TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/CaseTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PageExtensions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/TestBase.cs

Now that have we have all the pages implemented for the change of name/DOB cases resolution process we should add some e2e tests.
Add e2e tests that cover accepting, rejecting and cancelling a change of DOB/name case, starting from the case list screen.
N/A

Add e2e tests for accepting rejecting cancelling cases

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Models/ContactSearchSortByOption.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/GetContactsByDateOfBirthQuery.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/GetContactsByNameQuery.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/GetContactsByDateOfBirthHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/GetContactsByNameHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/QueryTests/GetContactsByDateOfBirthTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/QueryTests/GetContactsByNameTests.cs

Users need to be able to sort person search results so that they can more quickly identify the person they’re looking for.
Add a ‘Sort by’ drop down following the designs in Figma.
Add the following options:
Last name (A-Z)
Last name (Z-A)
First name (A-Z)
First name (Z-A)
Date of birth (ascending)
Date of birth (descending)
Update the queries to honour the requested sort by option. The chosen option should be passed around as a query parameter.
‘Last name (A-Z)' should be the default option.
CRM Query changes + UI + tests

Added ability to specify sort order for person/contact search results

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TagHelpers/UseEmptyFallbackTagHelper.cs

When there are null or empty values for fields in the UI we want a common approach to what gets displayed.
Add a tag helper which can replace empty strings with a grey hyphen.
Simple change.

Add tag helper to render empty content as a hyphen

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Models/ContactDetail.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Models/ContactExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/GetContactDetailByIdHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Alerts.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/appsettings.Testing.json
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/appsettings.json
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/wwwroot/Styles/site.scss
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/QueryTests/GetContactDetailByIdTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/IndexTests.cs

Users of the support desk need gender and NINO to help identify the correct record.
Add NINO, Gender and previous name(s) to the summary list on the person view, as per the designs.
CRM query changes + tests

Added previous names, nino and gender to person view

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/UpdateSanctionStateQuery.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/UpdateSanctionStateHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/Alert/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/Alert/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Common/AlertInfo.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Common/AlertStatus.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Alerts.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Alerts.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TagHelpers/MultiLineTextTagHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/QueryTests/CloseSanctionTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/QueryTests/UpdateSanctionStateTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/AlertTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PageExtensions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/Alert/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/CloseAlert/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/CrmTestData.CreatePerson.cs

Users of the TRS Console need to be able to view details of alerts.
Populate the /alerts/{alertId} page following the designs within the ‘Closed alert’ section ofthe Figma design (note that active alerts should be visible here too).
If no alert exists with the specified alertId return a 404.
The back link should go back to /persons/{personId}/alerts where {personId} is the ID of the person linked to the current alert.
CRM queries + UI + tests
Excluding detaillink functionality at the moment until CRM changes are done.

Alert detail page

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Services/DqtReporting/Migrations/0010_SanctionDetailsLink.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj

A new field dfeta_detailslink has been added to the dfeta_sanction table in CRM but not in the reporting database.
Add a migration script to add the missing column to the reporting DB.
simple change.

Added migration script to add dfeta_detailslink to dfeta_sanction in reporting DB

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Services/DqtReporting/Migrations/0011_AddHighProfileProgrammeType.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj

When High potential ITT programme type was added in august, it wasn't added to the reporting database. This is to add the label to the reporting db so that it can be reported on.
-   [] Attach to Trello card

Add script to add missing metadata for High Potential ITT to reporting db

---

.github/workflows/pr.yml

Previously were waiting until the main build & test job was completed before packaging. There's no need to do this; packaging is an independent process that has no dependency on the build job. This effectively shaves off ~ 3 minutes from our PR workflows.

Don't wait for build & tests to complete before packaging

---

.github/workflows/main.yml

The script that checks for non-main deployments on pre-prod hasn't been updated following the AKS move; this fixes it.

Fix pre-production environment name

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/SanctionTextLookup.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Common/AlertType.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Program.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/AlertTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PageExtensions.cs

For some alert types, users have been copy/pasting default text into the details attribute. We should auto-populate the details field for these alert types.
When creating an alert, when the alert type is changed, if the Details textbox is empty (or contains pre-populated text for the existing alert type) overwrite the Details textbox with the value from column F in the spreadsheet in the trello card for the selected alert type.
Helper for static data + UI + tests

Auto populate alert details by sanction type

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/ApiModels/AlertInfo.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/ApiModels/AlertType.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Constants.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/GetTeacherHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Requests/GetTeacherRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Responses/GetTeacherResponse.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetTeacherByTrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetTeacherTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetTeacherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/SeedCrmReferenceData.cs

ID needs to know what teachers have prohibitions so it can block access to some services. This adds an `alerts` property to the v3 teacher response which contains prohibition-level alerts only (for now).

Add Prohibition Alerts to v3 teacher response

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/UpdateContactNameQuery.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/UpdateContactNameHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Filters/CheckPersonExistsFilter.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/JourneyNames.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/Confirm.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Alerts.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditName/Confirm.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditName/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditName/EditNameState.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditName/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditName/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/QueryTests/UpdateContactNameTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PageExtensions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PersonTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditName/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditName/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/CrmTestData.cs

Support agents need a way to change a person’s name when the request has not come via a Change of name request.
Create new pages at /persons/{personId}/edit-name and /persons/{personId}/edit-name/confirm following the designs in Figma
If no active person exists with {personId} return a 404. The initial field values should be the existing first, middle and last names.
If first name is not specified, show an error ‘Enter a first name’.
If last name is not specified, show an error ‘Enter a last name’.
If first/middle/last name is greater than 100 characters, show an error ‘First/Middle/Last name must be 100 characters or less’.
After the record has been updated, redirect to /persons/{personId} with a flash message ‘Record has been updated’
Include any useful information needed to review this …

Change person name from detail person view

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/ExceptionExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Services/CrmEntityChanges/CrmEntityChangesService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Services/DqtReporting/DqtReportingService.cs

This logic should be in `CrmEntityChangesService` itself rather than being duplicated in consumers.

Move handling of CRM rate limit exceptions into CrmEntityChangesService

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/Program.cs

While looking at the production environment I noticed our API pods had restarted. I suspect this is due to some Redis timeouts that mean the health check has failed. This change disables rate limiting any unauthenticated endpoints.

Disable rate limiting for unauthenticated endpoints

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Services/CrmEntityChanges/CrmEntityChangesService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Services/CrmEntityChanges/ICrmEntityChangesService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Services/DqtReporting/DqtReportingService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Services/TrsDataSync/TrsDataSyncService.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/Services/TestableCrmEntityChangesService.cs

Adds a `modifiedSince` parameter to the `ICrmEntityChangesService`.`GetEntityChanges` method so that a caller can specify the `modifiedon` of the last record it processed and have records before that filtered out.
There are two drivers for this. The first is full resyncs; when we do a full resync (because our data token is invalidated due to a schema change) we end up going all the way back to the beginning of the change log and replaying everything, even though we've already processed it 99% of the data. With this new change, we can skip that redundant processing.
The second reason is to work better with back-fill jobs. When we run a back-fill job then enable the continuous updates we don't want to re-process records that the back-fill job has already populated.

Filter out entity changes that have already been processed

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/Endpoints/IdentityWebHooks/Messages/UserMergedMessage.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Endpoints/IdentityWebHooks/NotificationEnvelopeConverter.cs

We've used the user merge feature on ID for the first time so we're seeing messages we haven't had to handle before.

Handle, but ignore, UserMergedMessages

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/appsettings.Production.json
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Services/TrsDataSync/ServiceCollectionExtensions.cs

We need the service client to run the back-fill job, but we don't want the service that captures changes running until after the back-fill job is done.

Add config to register TrsDataSync ServiceClient without running service

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/DataverseAdapter.SetIttResultForTeacher.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/DataverseAdapterTests/SetIttOutcomeForTeacherTests.cs

With the endpoint being idempotent, when calling the endpoint with a pass result - a change should not have been creating a new induction result every time it was called. This change only creates a new induction record when the teacher does not already have qts (no dfeta_qtsdate set).

Fix to stop induction records from being created when not required

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/GetTeacherHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Responses/GetTeacherResponse.cs

We've got an error in Sentry caused by an induction record having a `null` appropriate body.

Handle induction records without an AB

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SyncAllContactsFromCrmJob.cs

We discard any records without a TRN when syncing to the TRS DB. It's much more efficient for the backfill jobs to have the CRM DB do that filtering for us.
This also removes `nolock` from the query; we don't want to sync changes that were uncommitted.

Filter out records without a TRN for backfill

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/ApiModels/NameInfo.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/GetTeacherHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Requests/GetTeacherRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Responses/GetTeacherResponse.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/appsettings.Testing.json
TeachingRecordSystem/src/TeachingRecordSystem.Api/appsettings.json
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/GetAllEarlyYearsStatusesQuery.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/GetContactDetailByTrnQuery.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/GetAllEarlyYearsStatusesHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/GetContactDetailByTrnHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/ReferenceDataCache.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetTeacherByTrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetTeacherTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetTeacherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/QueryTests/GetAllEarlyYearsStatusesTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/QueryTests/GetContactDetailByTrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/Usings.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/CrmTestData.CreatePerson.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/CrmTestData.UpdatePerson.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/Infrastructure/FakeXrmEasy/Plugins/QtsRegistrationUpdatedPlugin.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/SeedCrmReferenceData.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/ServiceCollectionExtensions.cs

Check want to show previous names so that it’s clear how they were found when they were found with a previous name.
Amend the /v3/teachers/<trn> endpoint to add a new GetTeacherRequestIncludes entry - PreviousNames. When this is specified, populate a PreviousNames array at the root of the response that contains the previous names. Each entry in the array should have a FirstName, MiddleName and LastName property. Any null MiddleNames should be normalised to an empty string. Entries should be sorted such that the most recent name change is first.
We should apply the same logic when grouping dfeta_previousname records as we do for the TRS Support Console UI.
CRM + API + Tests

Added previous names to v3 endpoint including tests

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/Infrastructure/Security/ApiKeyAuthenticationHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/appsettings.Testing.json
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/ApiFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/ApiTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/Infrastructure/Security/TestAuthentication.cs

Until now we've used a single fixed API client ID (and key) in our API tests. Now we're adding roles (and want to use various role combinations in tests) we need a more dynamic mechanism.
This introduces a `TestAuthenticationHandler` similar to what we use in other test projects. There's a singleton `CurrentApiClientProvider` that's shared by the server and tests that allows setting the current user ID. (It's an `AsyncLocal` to allow concurrent tests to set their own user independently.) 
Given we have two authentication schemes in the API - the API key plus an ID access token - we have to know when our test handler should run vs when it shouldn't (we don't want this `TestAuthenticationHandler` kicking in when we're testing endpoints that require an ID access token). To do that, I've …

Dynamic API client for tests

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/GetAnIdentity/GetAnIdentityOptions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/ApiFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/ApiTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/Endpoints/IdentityWebHooks/GetAnIdentityEndpointsTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/TestScopedServices.cs

The endpoint used to process webhooks effectively had a non-scoped reference to `IOptions<GetAnIdentityOptions>` which was causing the host to startup and configure itself multiple times. This in turn was causing the DB schema to be regenerated multiple times (clearing out data too) and leading to flakiness.

Fix flaky API tests

---

terraform/aks/workspace_variables/production.tfvars.json

We made this so high believing that the `DqtReportingService` that lives here was the cause of memory issues. We've since found out that's not the case so we can drop this back down again.

Reduce production worker memory

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/UserMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20231207135313_SourceUserIdEventSchema.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20231207135313_SourceUserIdEventSchema.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/User.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/EventBase.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/EytsAwardedEmailSentEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/IEventWithPersonId.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/InductionCompletedEmailSentEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/InternationalQtsAwardedEmailSentEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/QtsAwardedEmailSentEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/UserActivatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/UserAddedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/UserDeactivatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/UserUpdatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SendEytsAwardedEmailJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SendInductionCompletedEmailJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SendInternationalQtsAwardedEmailJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SendQtsAwardedEmailJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/AddUser/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Events/Processing/PublishEventsBackgroundServiceTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/AddUser/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/EditUserTests.cs

We need to be able to efficiently query all events for a given `person ID`. This introduces an interface - `IEventWithPersonId` - to ensure that we consistently name the `person ID` property the same way so we can easily do that query.
In addition this adds a `SourceUserId` property to `EventBase` so we're always tracking the ID of the user who generated the event consistently. This is for the same reason as above; in our event queries we want to join to the `users` table so we can pull back the information of the user who caused the event and that's more-easily done if it's always named the same thing.

Amend Event schema to more easily track PersonId and source UserId

---

TeachingRecordSystem/Directory.Build.props
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Event.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/EventInfo.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/EventInfoTests.cs

We have a need to store some events in CRM and subsequently sync them rather than writing them directly to our DB (since we can't write to CRM and our DB atomically). We can't directly serialize the event by itself because we have to know its type when we deserialize it later. We also can't serialize the EF `Event` model since that has some properties on that we can't populate yet (like the `EventId` and `Published` etc.).
This adds a wrapper type - `EventInfo` - that takes an event and provides `Serialize()` and `Deserialize()` methods for it.

Add EventInfo wrapper type for serializing events

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/ServiceCollectionExtensions.cs

The `CrmQueryDispatcher` and `ICrmQueryHandler<,>` registrations were all `Singleton`, but they rely on a transient `IOrganizationServiceAsync`. `IOrganizationServiceAsync` ends up coming from the root `IServiceProvider` and never gets disposed.

Fix lifetime of CrmQueryDispatcher and query handlers

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Requests/SetNpqQualificationRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Cli/Commands.CreateAdmin.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/MandatoryQualificationMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/QualificationMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20231208121135_MqQualifications.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20231208121135_MqQualifications.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/MandatoryQualification.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Qualification.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/TrsDbContext.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/EnumExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/MandatoryQualificationSpecialism.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/MandatoryQualificationStatus.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/QualificationType.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/UserType.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Usings.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Usings.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V2/Operations/SetNpqQualificationTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/EventInfoTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/TestUsers.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/Usings.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateUser.cs

This adds a base `Qualification` entity plus a derived `MandatoryQualification` entity. Properties for both are mapped to a single `qualifications` table in Postgres. I've omitted the MQ Provider property for now until we know more about how it will be modelled.
As part of this I've introduced a top-level `Models` namespace within the `Core` project for enums to live. From there we can re-use them in EF Models, Events, API responses etc.
I've also removed the EF convention that automatically creates indexes for FKs; that results in too many un-needed indexes particularly on the `{Created|Updated|Deleted}ByUserId` columns.

Add DB schema for MQs

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Services/CrmEntityChanges/CrmEntityChangesService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Services/CrmEntityChanges/ICrmEntityChangesService.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/Services/DqtReporting/DqtReportingFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/Services/DqtReporting/DqtReportingServiceTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/Services/TestableCrmEntityChangesService.cs

Neither the `TrsDataSyncHelper` nor `DqtReportingService` can handle receiving multiple updates for the same record in a batch. Incredibly this hasn't happened yet but it's feasible that it could, especially with how chatty some of the old integration jobs are.
This change adds a `rollUpChanges` parameter to the `CrmEntityChangesService`. When this is set, it will only return the most recent update for given record to the consumer.
I've made this a parameter rather than having it happen all the time as it's possible we will have future consumers that want to see every change (e.g. if we're creating a log of changes). In such cases we don't want this roll up behaviour.

Handle multiple updates for the same record in a change batch

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Event.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/EventInfo.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/EventBase.cs

Serializer options make more sense on `EventBase` than on the EF model.

Move event serializer options onto EventBase

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Filters/CheckUserExistsFilter.cs

The filter that shows the 'You have no roles' message is preventing people from signing out.

Fix sign out when user has no roles

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/DeleteQualificationQuery.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/DeleteQualificationHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/JourneyNames.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/DeleteMq/Confirm.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/DeleteMq/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/DeleteMq/DeleteMqState.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/DeleteMq/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/DeleteMq/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/DeleteMq/MqDeletionReasonOption.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Qualifications.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/QueryTests/DeleteQualificationTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/MqTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PageExtensions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/DeleteMq/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/DeleteMq/IndexTests.cs

We need a way for users to remove an MQ from a person’s record.
Following the designs in Figma to implement the Delete MQ journey.
The page URL should be /mqs/{qualificationId}/delete
If no reason is selected, show an error ‘Select a reason for deleting’.
The Upload evidence file upload is out of scope of this ticket. Adding the audit trail entry is also out of scope.
The Delete button should deactivate the CRM record and populate the dfeta_trsdeletedevent with a JSON-serialized event (contents TBC) - to be implemented as a single transaction.
CRM query + UI + tests

Delete MQ CRM query changes, UI and tests

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/QualificationMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20231212184014_RemoveUserFksOnQualification.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20231212184014_RemoveUserFksOnQualification.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Qualification.cs

Migrated data can't have {Created|Updated|Deleted}ByUserId columns populated unless we also migrate all user accounts from CRM (because foreign keys). We'll use audit records instead if we need to look up the user who performed a particular action.

Remove the {Created|Updated|Deleted}ByUserId columns from Qualification

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/HostApplicationBuilderExtensions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/ApiFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetTeacherTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/CrmClientFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/DeleteMq/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Provider/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Provider/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Result/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Result/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Specialism/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Specialism/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/StartDate/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/StartDate/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.cs

A pre-requisite for syncing MQs to TRS is syncing persons. This amends `TestData` to support syncing generally and updates the `CreatePerson` method to sync the created `contact` record.
For CRM integration tests we don't need syncing and enabling it will slow down already very slow tests. As such, whether we sync by default is configurable by passing in a parameter to `TestData`'s constructor. This can also be overridden on a per call basis - `TestData.CreatePerson(b => b.WithSyncOverride(false))`.

Amend TestData.CreatePerson to sync to TRS DB

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/EventBase.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SendEytsAwardedEmailJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SendInductionCompletedEmailJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SendInternationalQtsAwardedEmailJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SendQtsAwardedEmailJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/AddUser/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/EventInfoTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Events/Processing/PublishEventsBackgroundServiceTests.cs

Part 1 of N of adding an `EventId` property to `EventBase` (so the serialized event always has an ID in it and that ID can be generated outside of the DB).
Adding a `required` property here is safe as we don't read back events anywhere yet.

Add EventId property to EventBase

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/StartupTasks.cs

Examining `ServiceDescriptor.ImplementationType` can now throw (for keyed `ServiceDescriptor`s).

Fix AddStartupTask() for .NET 8

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/Infrastructure/CaptureEventObserver.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/TestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/TestScopedServices.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TeachingRecordSystem.TestCommon.csproj

Normally events are created via EF and we use an interceptor to capture the events that were created during the running of a particular test to later assert on. The TrsDataSyncHelper doesn't use EF to sync events, however, so this interceptor doesn't ever see the events.
This change amends TrsDataSyncHelper to provide an IObservable that emits synced models. In our test base class we subscribe to that and push events onto the CaptureEventObserver for the corresponding test.

Fix EventObserver.AssertEventsSaved to work with synced events

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.MandatoryQualification.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.Person.cs

With on-demand syncing now being used, it's possible that a record is synced with the latest version then the background service receives an older version of the same record. We don't want to clobber the newer version with the older one. This change ensures that we only ever process changes that are newer than the previous version of the record.

Ensure sync doesn't overwrite newer changes

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/ReferenceDataCache.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/ServiceCollectionExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/StartupTasks.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/ServiceCollectionExtensions.cs

We see some timeouts from ID talking to this API after it's just been deployed. It's possible that the cold `ReferenceDataCache` is enough to slow down requests sufficiently for these timeouts to trip. This adds a start-up task to populate the entire `ReferenceDataCache`.

Pre-warm the ReferenceDataCache

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Controllers/TrnRequestsController.cs

Adds just enough so we can get a complete API spec from the generated swagger doc.
[Design doc](docs/api-designs/trn.md)

Add TRN API skeleton

---

terraform/aks/monitoring.tf

This was changed during the front door errors investigation
Revert to default StatusCake confirmations to eliminate false alarms
Check default

[775] Reduce StatusCake sensitivity

---

justfile
scripts/Remove-TestsSchemaCache.ps1

When a test project deploys the DB, it stashes away a hash of the current schema definition in an AppData folder. The next time the tests are run, the hash is re-calculated and if it matches what's in the AppData file we know the schema hasn't changed and we can skip re-deploying the DB.
Occasionally something goes wrong and we want to force re-deploying the DB. This script is a helpful shortcut for doing that.

Add a script and just recipe to clear schema cache

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/MandatoryQualificationMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/MandatoryQualificationProviderMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20231219171728_MqProviders.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20231219171728_MqProviders.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/MandatoryQualification.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/MandatoryQualificationProvider.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Models/MandatoryQualification.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/DeleteMq/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/DeleteMq/DeleteMqState.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/DeleteMq/Index.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/DataStore/Postgres/Models/MandatoryQualificationProviderTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/EventInfoTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.MandatoryQualification.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/DeleteMq/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/DbHelper.cs

Also updates the MQ model for events to capture provider. We allow for specifying a DQT provider name in these events as the conversion from DQT MQ establishments to TRS MQ providers is lossy.

Add MQ Provider to DB

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/AddMq/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/AddMq/Provider.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/AddMq/IndexTests.cs

We typically activate journeys on the Index page but for Add MQ we've done it on the provider page. This moves the activation to Index.

Activate Add MQ journey from Index page

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/GetAllSpecialismsHandler.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/GetQualificationsByContactIdTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/UpdateMandatoryQualificationEstablishmentTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/UpdateMandatoryQualificationSpecialismTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/UpdateMandatoryQualificationStartDateTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/UpdateMandatoryQualificationStatusTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/MqTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/DeleteMq/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Provider/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Provider/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Specialism/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Specialism/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/StartDate/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/StartDate/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Status/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Status/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/QualificationsTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/SeedCrmReferenceData.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.cs

Our `TestData` methods are intended to create fully-populated, sane-looking data by default with options to override specific attributes, where required. Our current method for MQs creates an empty MQ however.
This change moves to a builder-style approach for adding MQs and will create a fully-populated MQ by default. Fields can be removed by calling the appropriate `With*` method and passing a `null` argument.

Create populated MQ by default in tests

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/MandatoryQualificationProvider.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/AddMq/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Provider/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Specialism/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/StartDate/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Status/Confirm.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/DataStore/Postgres/Models/MandatoryQualificationProviderTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/AddMq/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Provider/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Specialism/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/StartDate/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Status/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs

Previously the tests for adding and editing MQs have not actually checked that the adds or edits have been done. This changes that by adding an on-demand sync as part of the POSTs and asserting against the TRS DB.

Check that MQs have actually been added/edited

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/GetTeacherHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Responses/GetTeacherResponse.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Models/GeneratedCode.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/ReferenceDataCache.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetTeacherByTrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetTeacherTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetTeacherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/CreateMandatoryQualificationTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/GetQualificationByIdTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/GetQualificationsByContactIdTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/UpdateMandatoryQualificationEstablishmentTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/UpdateMandatoryQualificationSpecialismTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/UpdateMandatoryQualificationStartDateTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/UpdateMandatoryQualificationStatusTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/MqTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/AddMq/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/AddMq/ProviderTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/AddMq/SpecialismTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/AddMq/StartDateTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/AddMq/StatusTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/QualificationsTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/SeedCrmReferenceData.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs
crm_attributes.json

Add a StatusDescription property to both the Qts and Eyts blocks on the API.
https://trello.com/c/WbNK62Jp/342-add-teacher-status-and-eyts-status-to-api

Add StatusDescription to api Endpoint

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/GetAllTeacherStatusesHandler.cs

The previous PR that added status description to the v3 teachers endpoint gets status descriptions and caches them. It was noticed that a teacher has a qts with an inactive teacherstatusid - therefore Single() errors because the query was filtering out inactive ones. This PR allows the inactive teacher statuses to be returned.

Include Inactive teacher statuses

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/GetTeacherHandler.cs

fix status description for unknown qts statuses.

fix status description for unknown qts statuses

---

.github/workflows/pr.yml

Since CRM integration tests are so slow, we already skip them unless something around CRM integration has been changed. The most expensive tests are in the now-legacy `DataverseAdapter`; it would be good if we could avoid running these more often when building new integrations.
This change adds an additional filter to the `dotnet test` command to skip any `DataverseAdapter` tests, unless a `DataverseAdapter`-related file or test has been changed in the PR.

Skip DataverseAdapter tests unless DataverseAdapter has been changed

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/GetTeacherHandler.cs

Not all statuses have : in, so the pattern matching fails for qts status description. This PR removes the ':' in the pattern matching for Qualified teacher.

Remove : from pattern matching for qualified teacher

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/DqtReportingService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncService.cs

We have a few errors in Sentry caused by `OperationCanceledException`s in `TrsDataSyncService` when the app is shutting down. This change prevents wrapping those exceptions so that they are correctly handled (and not logged).
While the Sentry logs have only been for `TrsDataSyncService` I've made the same change to `DqtReportingService` too, since it's near-identical in its error handling and could see the same problem.

Don't raise error when shutting down sync services

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/EventMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20231221141110_EventInserted.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20231221141110_EventInserted.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Event.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/TrsDbContext.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Processing/PublishEventsBackgroundService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Events/Processing/PublishEventsBackgroundServiceTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/DbFixture.cs

With syncing events from DQT it's possible to see events out-of-order (w.r.t. their Created time) when publishing. This adds an Inserted time and amends the publishing service to use that when looking for new events.

Fix event processing for synced events

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/GetAllMqEstablishmentsHandler.cs

We have some existing active MQs linked to an inactive provider. This amends our query that gets all providers to return inactive too.
This will give us a larger than ideal list of providers for creating a new MQ too; the data move to TRS and provider rationalisation will sort that out.

Handle MQs with a deactivated provider

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Event.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/EventBase.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ChangeRequests/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/ChangeLog.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/ChangeLog.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/DqtUser.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/MandatoryQualificationDeletedEvent.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/RaisedByUser.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/TimelineEvent.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/ChangeRequests/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/ChangeLogTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.UpdateQualification.cs

Users need to be able to see that an MQ has been deleted from a teaching record and the details of that MQ.
Update the change log to query MandatoryQualifictionDeletedEvents for the current person and render each entry within the timeline according to the Figma designs.
Changes to UI + tests

Added support for showing MQ deleted events in change log

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/MandatoryQualificationDqtDeactivatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/ChangeLog.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/MandatoryQualificationDqtDeactivatedEvent.cshtml
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/ChangeLogTests.cs

We’re not migrating deactivated MQs to TRS but we want to show MQs that were previously deactivated in DQT.
Render an entry on the change log for every MandatoryQualificationDqtDeactivatedEvent as per the Figma designs.
New event + UI + tests

Add MQ deactivated event to change log

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Constants.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/FindTeachersHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/GetTeacherHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Responses/FindTeachersResponse.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Responses/GetTeacherResponse.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/EnumerableExtensions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/FindTeachersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/AlertsTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/ChangeLogTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs

We've previously (partially) moved to `ImmutableArray<>` as our preferred collection type, largely because it's immutable but you can concisely add or remove elements (and get a new collection back). With C# 12's collection expressions and spread operator it's now easy to do the same thing with all collection types.
This change moves to `IReadOnlyCollection<T>` on the API request & response types.

Prefer IReadOnlyCollection<T>

---

TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/Endpoints/IdentityWebHooks/GetAnIdentityEndpointsTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/Filters/CrmServiceProtectionFaultExceptionFilterTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/Startup.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/TestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V1/Operations/GetTeacherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V1/SwaggerTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V2/Operations/FindTeachersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V2/Operations/GetIttProvidersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V2/Operations/GetOrCreateTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V2/Operations/GetTeacherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V2/Operations/GetTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V2/Operations/SetIttOutcomeTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V2/Operations/SetNpqQualificationTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V2/Operations/UnlockTeacherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V2/Operations/UpdateTeacherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V2/SwaggerTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/CreateDateOfBirthChangeTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/CreateNameChangeTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/FindTeachersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetEytsCertificateTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetInductionCertificateTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetNpqCertificateTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetQtsCertificateTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetTeacherByTrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetTeacherTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetTeacherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/SwaggerTests.cs

Other test projects have `HostFixture` and `TestBase`; the API test project has `ApiFixture` and `ApiTestBase` instead. This fixes the inconsistency.

Rename test fixture and base class

---

TeachingRecordSystem/src/TeachingRecordSystem.Cli/Commands.CreateAdmin.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/UserMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240115115428_SplitUserTypes.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240115115428_SplitUserTypes.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/User.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/TrsDbContext.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/UserType.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/ChangeLog.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/MandatoryQualificationDeletedEvent.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/MandatoryQualificationDqtDeactivatedEvent.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/RaisedByUser.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/RaisedByUserInfo.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/TimelineEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/AddUser/Confirm.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/TestUsers.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/TestUsers.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateUser.cs

Currently we have a single `User` model for both `Application` users and `Person` users. This change introduces a hierarchy so that we have different types for both, with a common `UserBase` base type. API clients are going to become Application users, as are ID clients so it's neater to keep that away from person user-level roles etc. I've also added a third type - `System` - for the single special `System` user since it's not really either an `Application` user or `Person` user.
I went with `User` for the `Person` user type since `PersonUser` is similar to `Person`, and that's something else entirely.

Add a model hierarchy for user types

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/AddMq/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/DeleteMq/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Provider/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Specialism/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/StartDate/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Status/Confirm.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.MandatoryQualification.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/AddMq/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/DeleteMq/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Provider/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Specialism/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/StartDate/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Status/ConfirmTests.cs

Events that pre-date MQ migration to TRS should not have any migration-time mappings applied, otherwise a misleading audit trail is created.

Don't map MQ Provider until we've migrated data

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/EventMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240116112546_EventKey.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240116112546_EventKey.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Event.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/IEventWithKey.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/MandatoryQualificationCreatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/MandatoryQualificationDqtDeactivatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/MandatoryQualificationDqtImportedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/MandatoryQualificationDqtReactivatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/MandatoryQualificationUpdatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs

Until now we've borrowed the GUIDs from CRM's audit events to use as an `EventId` so that we can safely sync multiple times without creating duplicate events. However, for the forthcoming 'migrated' events, we won't have an external ID to use nor will we have a way to create a deterministic ID ourselves. Also, we should really be in control of our own ID generation.
This change adds an optional `key` column to the `events` table. If specified, it must be unique. The sync process is updated to handle collisions on keys. An interface - `IEventWithKey` - is used for specifying a key on a given event.

Add a Key to Event for deduplication

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs

When running the sync job on production we've had a `KeyNotFoundException`.

Handle missing attribute when comparing versions

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/ExceptionExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs

When sending a batch request we can get a rate limit error within an inner response.

Handle rate limit error in inner fault

---

.github/workflows/pr.yml
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/MandatoryQualification.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/MandatoryQualificationMigratedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SyncAllMqsFromCrmJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.MandatoryQualification.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/AddMq/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.cs

We're adding an additional event at migration time for MQs so we have a place to record data changes (e.g. provider mappings). This adds the relevant logic for creating that event.

Add a Migrated event for MQ records

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SyncAllMqsFromCrmJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SyncAllPersonsFromCrmJob.cs

A full person sync in pre-prod has missed around 1/3 of records for some reason. The docs on paged queries say to use unique values for the 'order by' clause so I've changed our queries to use the primary key.

Use the primary key for ordering in SyncAll* jobs

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/DeleteMq/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Status/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Status/EditMqStatusState.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Qualifications.cshtml.cs

Existing Mandatory Qualifications in CRM will not have a status set so when trying to Edit them in TRS there would not be an existing status.
However if an MQ has an end date then it implicitly indicates that it is Passed.
Amend the view MQ and edit MQ status UI to show an MQ as Passed if dfeta_MQ_Status is null and dfeta_MQ_Date is not null.
Simplish change

Amended MQ UI to treat MQ with end date as Passed

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccessToATeacherRecord/AuthorizeAccessLinkGenerator.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccessToATeacherRecord/Infrastructure/FormFlow/DummyCurrentUserIdProvider.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccessToATeacherRecord/Infrastructure/FormFlow/FormFlowHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccessToATeacherRecord/Infrastructure/Security/AuthenticationSchemes.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccessToATeacherRecord/Infrastructure/Security/FormFlowJourneySignInHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccessToATeacherRecord/Infrastructure/Security/MatchToTeachingRecordAuthenticationHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccessToATeacherRecord/Pages/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccessToATeacherRecord/Pages/Nino.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccessToATeacherRecord/Pages/Nino.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccessToATeacherRecord/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccessToATeacherRecord/SignInJourneyState.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccessToATeacherRecord/TeachingRecordSystem.AuthorizeAccessToATeacherRecord.csproj
TeachingRecordSystem/src/TeachingRecordSystem.FormFlow/JourneyInstanceId.cs
TeachingRecordSystem/tests/TeachingRecordSystem.FormFlow.Tests/JourneyInstanceIdTests.cs

This sets up most of the structure for the two-phase authentication for Authorize access.
The OneLogin handler takes a fixed set of credentials but we will have a different set per client. Accordingly, we will have a OneLogin scheme for every one of our clients. (A future PR will wire this up.)
The OneLogin handler needs a 'sign in scheme' that can persist the AuthenticationTicket over multiple requests. Typically this is Cookies but here we're using FormFlow state instead. The thinking behind is that we want to support multiple concurrent sign ins for different clients and each of those needs its own state. If we used cookies it would mean a cookie-per-client, which could be a lot of cookies (and a messy Cookies page). This is the `FormFlowJourneySignInHandler` type and there only needs …

Skeleton authentication scheme setup for Authorize project

---

TeachingRecordSystem/Directory.Packages.props
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/DqtReportingService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj

We see intermittent errors talking to CRM and our 'fail fast' policy for sync-related services means these services are shutting down. This adds simple retries with an exponential backoff that should hopefully be enough to weather CRM flakiness.

Add retries to TrsDataSyncService and DqtReportingService

---

.github/workflows/actions/deploy-aks-environment/action.yml
.github/workflows/backup-db.yml
Makefile
terraform/aks/.terraform.lock.hcl
terraform/aks/provider.tf

Enable azure RBAC deployments on all services
- Replace get-credentials with make get-cluster-credentials
- Add get-cluster-credentials: kubelogin convert-kubeconfig -l $(if ${GITHUB_ACTIONS},spn,azurecli) to get-cluster-credentials
- Update kubernetes Provider
Access https://dev.teacher-qualifications-api.education.gov.uk/health, ensure status returns "OK"
Merge after https://github.com/DFE-Digital/terraform-modules/releases/tag/v0.23.0 is releases

Enable azure RBAC deployments on all services

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/UserMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240129115405_ApplicationUserOneLoginClientIdAndPem.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240129115405_ApplicationUserOneLoginClientIdAndPem.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/User.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/ApplicationUserUpdatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Models/ApplicationUser.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ApplicationUsers/EditApplicationUser.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ApplicationUsers/EditApplicationUser.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ApplicationUsers/Index.cshtml
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/ApplicationUserTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PageExtensions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/TestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/ApplicationUsers/EditApplicationUserTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateApplicationUser.cs

We need to store a separate set of credentials for One Login for every TRS Application User.
Add OneLoginClientId and OneLoginPrivateKeyPem properties to the ApplicationUser model.
Add a One Login section to the Edit Application User page with optional fields for each of the new fields (use a textarea for the OneLoginPrivateKeyPem field and validate it using ImportFromPem on RSA).
UI + tests + end to end tests

Add One Login config to Edit Application User UI + tests

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/AuthorizeAccessLinkGenerator.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/AuthorizeAccessOptions.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Infrastructure/Conventions/BindJourneyInstancePropertiesConvention.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/PageModelExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/DebugIdentity.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/DebugIdentity.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/_ViewImports.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/SignInJourneyHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/SignInJourneyState.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/TagHelpers/FormTagHelperInitializer.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/appsettings.Development.json
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/SignInJourneyHelperTests.cs

We need to be able to override the identity information we get from One Login for testing in non-production environments. This adds a debug page into the start of the journey where we can override that information and detach a `Person`, if one is already assigned.

Add a debug page for overriding user information

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/AuthorizeAccessLinkGenerator.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Infrastructure/Security/FormFlowJourneySignInHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Infrastructure/Security/MatchToTeachingRecordAuthenticationHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/DebugIdentity.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/SignInJourneyHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/GlobalUsings.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/SignInJourneyHelperTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/TestBase.cs

Sets up `SignInJourneyHelper` as the orchestrator of the sign in/registration journey via a new `GetNextPage` method.  Most of the scenarios are stubbed out for now.

Initial Authorize access journey orchestration

---

TeachingRecordSystem/Directory.Packages.props
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/NameSynonymsMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/PersonSearchAttributeMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240201153254_PersonSearchAttributeAndNameSynonyms.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240201153254_PersonSearchAttributeAndNameSynonyms.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/NameSynonyms.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/PersonSearchAttribute.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/TrsDbContext.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/PopulateAllPersonsSearchAttributesJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/PopulateNameSynonymsJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/PopulatePersonSearchAttributesJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/PersonSearchResult.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/PersonSearch/IPersonSearchService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/PersonSearch/PersonSearchService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/PersonSearch/ServiceCollectionExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/PersonSearch/PersonSearchServiceTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs

There are several places where we do a person search against DQT. Each of these searches has different matching criteria. We’ve been constrained by CRM on how smart we can make these searches since we don’t have access to the underlying DB. Now that we’re syncing person data to the TRS DB, we can do better.
This ticket is to begin a new search service that can be used with Authorize access only (initially).
Create a PersonSearchService with the following signature:
class PersonSearchService
{
Task<IReadOnlyCollection<PersonSearchResult>> Search(IEnumerable<string[]> name, IEnumerable<DateOnly> dateOfBirth, string? nino, string? trn);
}
Note that the name and dateOfBirth parameter take collections (since we can get multiple names and/or DOBs from One Login).
The method should return all …

Added person search service against TRS DB

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Handlers/GetTeacherHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Responses/GetTeacherResponse.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V2/Operations/GetTeacherTests.cs

There isn't a trello ticket for this. Register require a way of finding out if pii updates are permitted on the v2 **UpdateTeacher** endpoint so that they don't even attempt to send pii updates. Proposed change here is to return the **AllowPIIUpdates** on the **GetTeacher** endpoint.

Added AllowPIIUpdates to v2 getteacher endpoint to support register

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/MapErrorAttribute.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Controllers/IttOutcomeController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Controllers/NpqQualificationsController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Controllers/TeachersController.cs

Things in the `Infrastructure` namespace aren't meant to be referenced by 'regular' API code.

Move attribute to root namespace

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/AuthorizeAccessLinkGenerator.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/NationalInsuranceNumber.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/NationalInsuranceNumber.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/NotFound.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/NotFound.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Shared/_Layout.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Trn.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Trn.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/SignInJourneyHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/NotFoundTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/TrnTests.cs

Adds a TRN page and incorporates it into the lookup process.
Also adds a 'not found' error page, for cases where lookup failed and we've run out of questions to ask. The content is placeholder for now.

Add TRN page for teaching record lookup

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/UserMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240208134232_OneLoginAuthSchemeInfo.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240208134232_OneLoginAuthSchemeInfo.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/User.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/ApplicationUserUpdatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Models/ApplicationUser.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ApiKeys/AddApiKey.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ApiKeys/EditApiKey.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ApplicationUsers/EditApplicationUser.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ApplicationUsers/EditApplicationUser.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/wwwroot/Styles/site.scss
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/ApplicationUserTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/ApplicationUsers/EditApplicationUserTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateApplicationUser.cs

Adds redirect URI, post logout redirect URI and an authentication scheme name to `ApplicationUser` for One Login clients. Also adds an explicit `IsOidcClient` flag.
I've also hidden the private key by default (it's visible by clicking a 'Show key' checkbox).

Store redirect URIs for One Login clients

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_Layout.cshtml
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/IndexTests.cs

* Don't show 'Sort by' on initial person search page.
* Add a 'Sort' button next to 'Sort by' drop-down on results page.
* Change 'Find a record' to 'Records' in the nav.
I've also removed the anti-forgery token (which was added by mistake) and fixed some of the pagination links to retain the 'sort by' value.

Person search amends from snagging

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/MandatoryQualificationSpecialism.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/AddMq/CheckAnswers.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/AddMq/Provider.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/AddMq/Specialism.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/AddMq/Specialism.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/AddMq/StartDate.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/AddMq/Status.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/DeleteMq/Confirm.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/DeleteMq/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/DeleteMq/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Provider/Confirm.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Provider/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Provider/Reason.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Provider/Reason.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Specialism/Confirm.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Specialism/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Specialism/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Specialism/Reason.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Specialism/Reason.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/StartDate/Confirm.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/StartDate/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/StartDate/Reason.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/StartDate/Reason.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Status/Confirm.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Status/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Status/Reason.cshtml
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/AddMq/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/ChangeLogTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/SeedCrmReferenceData.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs

This makes the generated error summary appear above the heading and caption.
Also removes some MQ specialisms from the Add MQ journey; we don't want new records creating with legacy specialisms.

Fix more MQ journey snags

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/DebugIdentity.cshtml.cs

GB date parsing isn't working on deployed environments (likely because of the default `Culture`). This sets an explicit format to parse with.

Fix date parsing on deployed environments

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/SignInJourneyHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/NationalInsuranceNumberTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/TrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/TestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.UiTestCommon/Infrastructure/FormFlow/InMemoryInstanceStateProvider.cs

Also fixes our test state storage provider to behave more like a real, DB-backed provider (i.e. we can't just modify a state object directly and forget to persist it).

Fix sign in for known users

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/Infrastructure/Logging/RemoveRedactedUrlParametersEventProcessor.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Properties/StringResources.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Properties/StringResources.resx
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Validators/CreateTrnRequestRequestValidator.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/NationalInsuranceNumber.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/CreateContactHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/NationalInsuranceNumberHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Worker/Infrastructure/Logging/HostApplicationBuilderExtensions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/VNext/CreateTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/CreateTeacherTests.cs

Change v3 trn request endpoint to use a common nino validator.
https://trello.com/c/bauxANrV/1731-trn-api-post-endpoint

Nino validation for v3 trn request endpoint

---

.github/workflows/pr.yml

Dependency updates can affect lint results, since namespaces can move around (we had this recently with a Sentry upgrade). Amend the workflow that detects what to lint such that if a `csproj` file changes we lint the entire codebase.

Lint entire codebase if project files have changed

---

.github/workflows/pr.yml

Remove concurrency limitation for PR builds

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Program.cs

This will simplify updating configuration dynamically since we won't have to worry about having to dispose old RSA instances.

Remove long-lived RSA instance

---

TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/CreateMandatoryQualificationTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/GetQualificationByIdTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/GetQualificationsByContactIdTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/UpdateMandatoryQualificationEstablishmentTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/UpdateMandatoryQualificationSpecialismTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/UpdateMandatoryQualificationStartDateTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/UpdateMandatoryQualificationStatusTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/MqTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/AddMq/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/AddMq/ProviderTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/AddMq/SpecialismTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/AddMq/StartDateTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/AddMq/StatusTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/QualificationsTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs

I amended the signature of `WithQts()` too; we don't use it here any more but it'll be useful in future.

Remove unnecessary QTS assignment for adding an MQ in tests

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/MandatoryQualificationSpecialism.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs

We have some legacy providers where the specialism is 'baked in' to their name. This change applies the mappings so we can infer specialism correctly in cases where it's missing.

Map MQ specialism from providers on migration

---

terraform/aks/monitoring.tf
terraform/aks/variables.tf
terraform/aks/workspace_variables/production.tfvars.json

The SSL certificate expired without warning - we need to create monitoring alerts for this so we can renew before future expiries
Add ssl monitoring alerts to status cake

Add ssl statuscake alerts

---

TeachingRecordSystem/Directory.Packages.props
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/HttpResultActionResult.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Infrastructure/Security/FormFlowJourneySignInHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Infrastructure/Security/MatchToTeachingRecordAuthenticationHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/DebugIdentity.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/NationalInsuranceNumber.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/NotFound.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Trn.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/SignInJourneyHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/SignInJourneyState.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240216151724_RemoveOneLoginUserCoreIdentityVc.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240216151724_RemoveOneLoginUserCoreIdentityVc.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/OneLoginUser.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/NationalInsuranceNumberTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/NotFoundTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/NotVerifiedTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/TrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/SignInJourneyHelperTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/TestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateOneLoginUser.cs

Currently when we push users to One Login we ask for both authentication and identity verification up front. In some cases this means identity verification is being requested when it's not required (e.g. if we already know a user's TRN). This change moves to a two step process; authentication (only) then, if required, identity verification.

Only request identity verification if required

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/EventMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240307130427_EventPersonId.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240307130427_EventPersonId.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Event.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/ChangeHistory.cshtml.cs

Even with a GIN index on the `event` table's `payload` column querying by `person_id` is relatively slow. This adds a separate `person_id` column with an index to improve performance.

Add person_id column to Event with an index

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/NationalInsuranceNumberHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/TpsCsvExtractFileImporterTests.cs

During testing of the CSV extract we noticed that there were some National Insurance Numbers in the file which started with QQ and were seen as invalid using the existing Regex we have for NINO validation.
QQ is used for temporary NINOs and is valid so we should allow this everywhere we validate a NINO.
Amend the NINO validation helper to allow NINOs starting with QQ

Amended validation to allow NINOs starting with QQ

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/RefreshEstablishmentsJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Establishments/EstablishmentRefresher.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Establishments/ServiceCollectionExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/TpsCsvExtractProcessor.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/UpdatedPersonEmploymentEstablishment.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/Establishments/EstablishmentRefresherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/TpsCsvExtractProcessorTests.cs

Extended establishment refresh job to also upated person_employments table if the "most open" version of an establishment in GIAS has changed (e.g. when a school has become an academy).

Refresh workforce data with "most open" version of establishment

---

TeachingRecordSystem/Directory.Packages.props
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/ClaimTypes.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Controllers/OidcController.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Infrastructure/Security/OneLoginAuthenticationSchemeProvider.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Shared/_Layout.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/SignOut.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/SignOut.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/SignInJourneyHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/Infrastructure/Security/FakeOneLoginHandler.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/TestBase.cs

While adding an OIDC test app I noticed we hadn't built out support for sign out; this PR adds that. The subsequent PR with that test app will add end-to-end tests that verify all the OIDC parts are working, including this sign out.

Add OIDC sign out support

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Shared/_Layout.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_Layout.cshtml

We don't want either the Support Console or Authorize access to be appearing in search results.

Prevent search engine indexing

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/Infrastructure/OpenApi/AddWebHookMessagesDocumentFilter.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Infrastructure/OpenApi/OpenApiDocumentHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Infrastructure/OpenApi/ServiceCollectionExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/ApiModels/Alert.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/ApiModels/AlertCategoryInfo.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/ApiModels/AlertTypeInfo.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/WebHookMessages/AlertCreatedNotification.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/WebHookMessages/AlertDeletedNotification.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/WebHookMessages/AlertUpdatedNotification.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/WebHookMessages/PingNotification.cs
docs/api-designs/webhooks.md

This updates the draft webhook spec to use [The Webhook Standard](https://www.standardwebhooks.com/), include versioning and adds the message schemas to the Swagger docs.

Refresh webhook specs

---

.github/workflows/pr.yml
TeachingRecordSystem/.config/dotnet-tools.json
TeachingRecordSystem/Directory.Packages.props
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/TeachingRecordSystem.AuthorizeAccess.csproj
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TeachingRecordSystem.SupportUi.csproj
justfile

We've started to get sporadic LIB003 errors restoring client-side packages with libman's msbuild target. This change moves to an explicit `libman restore` in the build step, which seems to solve the problem.

Move libman restore into explicit step

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/AuthorizeAccessLinkGenerator.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Controllers/OidcController.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Infrastructure/Filters/AssignViewDataFromFormFlowJourneyResultFilter.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Infrastructure/Security/MatchToTeachingRecordAuthenticationHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Infrastructure/Security/OneLoginAuthenticationSchemeProvider.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Oidc/SignOut.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Oidc/SignOut.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Shared/GenericError.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Shared/NotFound.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Shared/_ErrorLayout.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Shared/_Layout.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/SignOut.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/SignOut.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Test.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Test.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/SignInJourneyHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/SignInJourneyState.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/wwwroot/Scripts/init-service-header.js
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/wwwroot/Scripts/service-header.js
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/wwwroot/Styles/service-header-no-imports.scss
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/wwwroot/Styles/site.scss
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/NationalInsuranceNumberTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/NotFoundTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/NotVerifiedTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/TrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/SignInJourneyHelperTests.cs

This also adds a separate sign out page that we can use during our matching journeys.

Add One Login header

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/EstablishmentMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/EstablishmentSourceMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/PersonEmploymentMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240405101844_EstablishmentSources.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240405101844_EstablishmentSources.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Establishment.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/EstablishmentSource.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/PersonEmployment.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Models/PersonEmployment.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/RefreshEstablishmentsJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Establishments/CsvDownloadEstablishmentMasterDataService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Establishments/EstablishmentRefresher.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/TpsCsvExtractProcessor.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/Establishments/EstablishmentRefresherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateEstablishment.cs

The TPS extract for workforce data contains Local Authority Code and Establishment Number combinations which do not map to GIAS establishments but DO map to other employers held internally in TPS tables.
Amend the existing TRS database schema to have an establishment source associated with an establishment.

Added support for multiple establishment sources

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/Infrastructure/Filters/AddTrnToSentryScopeResourceFilter.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Program.cs

For endpoints authorized with an ID access token we can't see the TRN in Sentry when errors occur (since it's not in the endpoint). This adds a tag with the TRN.

Add TRN to Sentry scope

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/appsettings.Development.json
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/appsettings.EndToEndTests.json

OpenIddict will use the incoming request to derive an issuer by default but it's better for us to be explicit since we'll be available on multiple domains and the API will need a specific issuer to check against.

Explicitly define the issuer for Authorize access

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/appsettings.Development.json
TeachingRecordSystem/src/TeachingRecordSystem.Api/appsettings.Testing.json
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/OidcTest/SignedIn.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/OidcTest/SignedIn.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/HostFixture.cs

The `/v3/teacher` endpoint currently only allows access via an access token issued by ID. This changes that to also allow an access token from Authorize access.

Allow API access with a token from Authorize access

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/HttpResultActionResult.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Infrastructure/Security/OneLoginAuthenticationSchemeProvider.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/DebugIdentity.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Found.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/NotVerified.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/SignInJourneyHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/OneLoginUserMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240410164157_OneLoginUserVerified.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240410164157_OneLoginUserVerified.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240411145144_VerifiedDetails.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240411145144_VerifiedDetails.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/OneLoginUser.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/OneLoginUserVerificationRoute.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/Infrastructure/Security/FakeOneLoginHandler.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/OidcTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/SignInTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/ConnectTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/FoundTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/NationalInsuranceNumberTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/NotFoundTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/NotVerifiedTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/TrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/SignInJourneyHelperTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/TestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateOneLoginUser.cs

This change persists verification metadata, specifically how, when and what name/DOB was verified.
Part of this change includes a refactor of `SignInJourneyHelper` to more-clearly split out the authenticate vs verify steps.
This also fixes the One Login verification failure scenario and skips verification for users who have already verified.

Store verification metadata against a One Login user

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Worker/appsettings.json

We've had a few instances on the dev environment where transient database errors have caused this service to stop. This change increases the retry attempts to hopefully mitigate that.
I've also decreased the poll interval from five minutes to one minute to reduce the lag.
`MandatoryQualification` sync is removed too since there are no MQ changes being made in DQT any more.

Tweak TrsDataSyncService config for more reliability

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/ClaimTypes.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Controllers/OAuth2Controller.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Infrastructure/Security/OneLoginAuthenticationSchemeProvider.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/SignInJourneyHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/TestAppConfiguration.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/OneLoginUserMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240416104642_LastCoreIdentityVc.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240416104642_LastCoreIdentityVc.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/OneLoginUser.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/OidcTests.cs

We need to show the user's verified info on the account page. This adds two new claims to the `userinfo` endpoint for verified names and birth dates, respectively. Both claims are formatted as JSON.

Return verified names & birthdates from userinfo endpoint

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/CheckAnswers.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Connect.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Found.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/NationalInsuranceNumber.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/NationalInsuranceNumber.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/NotFound.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/NotFound.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Trn.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Trn.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/wwwroot/Styles/site.scss
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/SignInTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/NotFoundTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/TrnTests.cs

The Figma designs differ from the prototype and are further ahead. This updates the journey we've built out so far to reflect those designs.

Align Teacher Auth journey with designs round 2

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/DataverseAdapter.CreateTeacher.cs

Sometimes we get cases where the contact we created via `DataverseAdapter.CreateTeacher` doesn't exist, even though it succeeded successfully. We explicitly specify an ID here so that we can create the `contact` and several things that relate to it in a single transaction. This is a bit of a mystery; it may be the case that CRM is ignoring the ID we're passing in these cases and using its own. This change modifies the method to return the ID that CRM itself returned rather than the one we're passing in. If this is indeed the problem, that should solve it.

Use the contact ID returned from CRM

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/AuthorizeAccessLinkGenerator.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/NotFound.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/SupportRequestSubmitted.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/SupportRequestSubmitted.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/SignInJourneyState.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/SupportTaskMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240417152506_SupportTasks.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240417152506_SupportTasks.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240425141449_SupportTaskCreatedOn.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240425141449_SupportTaskCreatedOn.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/SupportTask.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/TrsDbContext.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Models/SupportTask.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/SupportTaskCreatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/OneLoginUserVerificationRoute.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskData/ConnectOneLoginUserData.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskStatus.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskType.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/SignInTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/SupportRequestSubmittedTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/TestBase.cs

When automatic matching fails a support task needs to be raised for support to find the record and associate it with the One Login User. This adds the DB schema for support tasks and wires up the journey to create one when a user is verified but the matching fails.

Create a support task when automatic matching fails

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/EstablishmentMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/TpsEstablishmentMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/TpsEstablishmentTypeMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240426143546_TpsEstablishments.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240426143546_TpsEstablishments.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Establishment.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/TpsEstablishment.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/TpsEstablishmentType.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/TrsDbContext.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/RefreshEstablishmentsJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/TpsRefreshEstablishmentsJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Establishments/Gias/CsvDownloadEstablishmentMasterDataService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Establishments/Gias/EstablishmentCsvRow.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Establishments/Gias/EstablishmentRefresher.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Establishments/Gias/GiasOptions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Establishments/Gias/IEstablishmentMasterDataService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Establishments/ServiceCollectionExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Establishments/Tps/NewEstablishment.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Establishments/Tps/TpsEstablishmentCsvRow.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Establishments/Tps/TpsEstablishmentRefresher.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/BlobStorageTpsExtractStorageService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/ITpsExtractStorageService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/ServiceCollectionExtensions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/Establishments/Gias/EstablishmentRefresherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/Establishments/Tps/TpsEstablishmentRefresherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/DbHelper.cs

TPS includes establishments which are not in GIAS.
Capita have provided a spreadsheet which includes some additional mappings of local authority code / establishment number to establishment which we need to use as an additional source of establishments to GIAS.
Create an ad-hoc hangfire job to grab the TPS Establishments CSV from blob storage, parse it with CsvHelper and dump it into the tps_establishments table and then process the data in this table to populate additional data in the Establishments table with an establishment source of TPS.
Db changes + job & helper classes  + tests

Added job to refresh establishments sourced from TPS spreadsheet

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/SignInJourneyHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/OneLoginUserMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240501095154_OneLoginUserMatchRoute.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240501095154_OneLoginUserMatchRoute.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/OneLoginUser.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/OneLoginUserMatchRoute.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/OneLoginUserMatchedAttribute.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/PersonMatching/IPersonMatchingService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/PersonMatching/MatchResult.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/PersonMatching/PersonMatchingService.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/SignInJourneyHelperTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/PersonMatching/PersonMatchingServiceTests.cs

This adds a `OneLoginUserMatchRoute` so we can store how we've matched the user to a teaching record. In addition it stores the specific attributes and their values that we matched on; that's not something we have in ID and it would have helped in diagnosing issues. It will also help to inform how well our matching policy is working.

Store how the One Login user was matched

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/PersonDetailModel.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_PersonDetail.cshtml
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PageExtensions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PersonTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.UiTestCommon/AngleSharpExtensions.cs

The person detail summary list appears in the support pages for resolving One Login user matches. This moves it into a partial so we can re-use it.

Move person detail summary list into a partial

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/PersonEmploymentMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/TpsCsvExtractItemMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240507142027_PersonEmploymentsAgeing.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240507142027_PersonEmploymentsAgeing.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/PersonEmployment.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/TpsCsvExtractItem.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Models/PersonEmployment.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/PersonEmploymentUpdatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/ProcessEndedEmploymentsJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/EmploymentType.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/BlobStorageTpsExtractStorageService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/NewPersonEmployment.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/TpsCsvExtractFileImporter.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/TpsCsvExtractProcessor.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/UpdatedPersonEmploymentEndDate.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/UpdatedPersonEmploymentEstablishment.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/TpsCsvExtractFileImporterTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/TpsCsvExtractProcessorTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePersonEmployment.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateTpsCsvExtract.cs

Since the original job to import TPS extract data was written, we have discovered that the end date field is actually the "last known employed date".
To deduce an actual end date we need to use a combination of this date and the last extract date to see if this has stayed the same for over x months as an indication that this teacher is no longer working at this employed.
Also, now that we have imported establishments based on a spreadsheet + some range mappings provided by TPS, there is no longer the need to have certain fields be nullable.
DB changes, changes to the import process + an adhoc job to age the data (this maybe be removed at a later date if we don't believe the data is reliable enough) + test changes.
Not a huge amount of code changes in the end …

Workforce data extract support ageing and non gias establishments

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/DownloadEvidenceFilesFromBlobStorageHttpHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Program.cs

AYTQ cannot easily give us a blob URI with a SAS token. This adds support for retrieving evidence files using an authenticated `BlobClient` for pre-configured blob storage accounts. It uses a `DelegatingHandler` to intercept the request, check if it matches a known blob storage account URI then uses `BlobClient` (with a configured token) to download the file and create an `HttpResponseMessage`.

Add support for downloading evidence files from Blob Storage

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Handlers/GetOrCreateTrnRequestHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/DataverseAdapter.CreateTeacher.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V2/Operations/GetOrCreateTrnRequestTests.cs

This is the latest attempt to narrow down the issue we sometimes see where records created in a TRN request don't actually get created. This adds a simple check after the create to see if we can retrieve it.

Check created contact can be retrieved

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Shared/_Layout.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/AddMq/Provider.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Provider/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_Layout.cshtml

I noticed when we last deployed a CSS change that it required manually refreshing the page to get the latest version. This change adds `asp-append-version="true"` to all our script and style imports so that any changes will be seen by the browser without an explicit refresh.

Add version query param to style and script imports

---

Makefile
terraform/domains/infrastructure/config/trs.tfvars.json

The TRS costs are not reported correctly as the product is still the default Teacher Services Cloud
Update the product tag to "Teaching Record System"
The resource groups show the right tag

Update product tag

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/NpgsqlExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/NationalInsuranceNumberHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/NewPersonEmployment.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/TpsCsvExtractProcessor.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/UpdatedPersonEmployment.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/UpdatedPersonEmploymentEndDate.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/TpsCsvExtractFileImporterTests.cs

While running the job to import the 2nd months workforce data System.OutOfMemoryException was thrown.
Initial investigation has lead us to believe this is related the EF change tracking on a large number of entities (specifically all the Events that get raised as part of the processing).
Amended the SQL to update as much as possible in each call to the database.
Added transactions and improved events generation (removed need for EF change tracking).

Fix out of memory issue for workforce data import

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/SignInJourneyHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/OneLoginUserMatchedAttribute.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/PersonMatching/IPersonMatchingService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/PersonMatching/PersonMatchingService.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Filters/CheckSupportTaskExistsFilter.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/PageContextFeatures.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/PersonDetailViewModel.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_PersonDetail.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ConnectOneLoginUser/Connect.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ConnectOneLoginUser/Connect.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ConnectOneLoginUser/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ConnectOneLoginUser/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/wwwroot/Styles/site.scss
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/PersonMatching/PersonMatchingServiceTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/SupportTaskTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ConnectOneLoginUser/ConnectTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ConnectOneLoginUser/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs

This adds UI for successfully resolving support tasks to connect a One Login user to a teaching record. The verification and unhappy path will follow separately.
There are a few tweaks to the `GetSuggestedMatches` method on `PersonMatchingService` as well to consider first name when scoring results.

Add UI to resolve a Connect One Login user support task

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/CreateTrnRequestTaskQuery.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/CreateTrnRequestTaskHandler.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/CreateDateOfBirthChangeIncidentTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/CreateNameChangeIncidentTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/CreateTrnRequestTaskTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/GetActiveIncidentsTests.cs

We’re building a journey where NPQ participants who don’t have a TRN can request one using an online form. The data needs to go into a CRM Task so it can be processed.
Add a new command that creates a CRM Task with a subject - TRN request. The command should accept a file (like CreateNameChangeIncidentQuery) and a Description parameter.
Also improved some existing tests for commands which upload evidence.

Added new CRM command to create a TRN request task

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/AuthorizeAccessLinkGenerator.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Email.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Email.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/RequestTrnJourneyState.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/_Layout.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/appsettings.json
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/RequestTrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/TestBase.cs

Add a start page following the designs in Figma [Request a TRN] under /request-trn in the AuthorizeAccess project.
Create a new folder RequestTrn under Pages and define a new Layout.
The <head> should include <meta name="robots" content="noindex"> to prevent search engines crawling this journey.
This start page should initialise a new FormFlow journey.
Start now should redirect to /request-trn/email

Added initial code for Request a TRN journey including the start page

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/AuthorizeAccessLinkGenerator.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/DataAnnotations/EmailAddressAttribute.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Email.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Email.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Name.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Name.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/RequestTrnJourneyState.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/EmailAddress.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/RequestTrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/EmailTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/TestBase.cs

Add an email address page following the designs [Request a TRN] under /request-trn/email
When a valid email is entered and Continue is clicked, store the email address on the FormFlow instance and redirect to /request-trn/name (a new page).
If no email is entered show an error Enter your email address.
If the email isn’t valid (i.e. doesn’t contain an @) show an error Enter a valid email address.

Added email page to get a TRN journey + tests

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/AuthorizeAccessLinkGenerator.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/DataAnnotations/RequiredIfOtherPropertyEqualsAttribute.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/DateOfBirth.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/DateOfBirth.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Name.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Name.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/RequestTrnJourneyState.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/RequestTrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/NameTests.cs

Add a name page (following the Request a TRN designs in Figma) under /request-trn/name
When a non-empty full name is entered and Continue is clicked, store the name & previous name on the FormFlow instance and redirect to /request-trn/date-of-birth(a new page).
If no name is entered show an error Enter your name.
If the ‘Do you have a previous name’ question is not answered, show an error Tell us if you have a previous name.
If ‘Yes’ is answered to the ‘Do you have a previous name' but no previous name is entered, show an error 'Tell us your previous name’.
If the email question has not yet been answered, redirect to /request-trn/email.
new page in journey + tests
-   [x] Attach to Trello …

Added Name page to request a TRN journey

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/AuthorizeAccessLinkGenerator.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/DateOfBirth.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/DateOfBirth.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Identity.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Identity.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/RequestTrnJourneyState.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/PageExtensions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/RequestTrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/DateOfBirthTests.cs

If no DOB is entered show an error Enter your date of birth.
When a valid DOB is entered and Continue is clicked, store the DOB on the FormFlow instance and redirect to /request-trn/identity
If the name question has not yet been answered, redirect to /request-trn/name
Page + tests

Added DOB page for request a TRN journey

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/AuthorizeAccessLinkGenerator.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/DataAnnotations/EvidenceFileAttribute.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/DataAnnotations/FileExtensionsAttribute.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/DataAnnotations/FileSizeAttribute.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Identity.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Identity.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/NationalInsuranceNumber.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/NationalInsuranceNumber.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/RequestTrnJourneyState.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/TeachingRecordSystem.AuthorizeAccess.csproj
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/RequestTrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/IdentityTests.cs

Add an evidence page following the [Request a TRN] Figma designs under /request-trn/identity
Create a blob storage container (with no public access) for storing the files; generate a random name and upload the file to the container on form submission. Update the journey state with the file’s ID so it can be retrieved when the journey is completed then redirect to /request-trn/national-insurance-number
If the date of birth question has not yet been answered, redirect to /request-trn/date-of-birth.
Pages + tests

Add proof of identity page to request a TRN journey

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/DqtReportingService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncService.cs

The `TrsDataSyncService` is waiting too long between retries in some cases. This amends the backoff type to linear to hopefully solve that problem. I've mirrored the policy into `DqtReportingService` too.

Amend background service retry backoff type to linear

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/AuthorizeAccessLinkGenerator.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Address.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Address.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/CheckAnswers.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/NationalInsuranceNumber.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/NationalInsuranceNumber.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/RequestTrnJourneyState.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/RequestTrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/NationalInsuranceNumberTests.cs

Add a National Insurance number page (following the [Request a TRN] Figma designs) under /request-trn/national-insurance-number
If the question is not answered, show an error ‘Tell us if you have a National Insurance number’. If ‘Yes’ is answered but the entered NINO is empty, show an error ‘Enter your National Insurance number’. If the entered NINO is not valid, show an error ‘Enter a valid National Insurance number’.
When the form is valid and Continue is clicked, store the ‘has NINO’ and NINO on the FormFlow instance and redirect to /request-trn/address if no NINO was entered or /request-trn/check-answers otherwise.
If the evidence question has not yet …

Added NINO page to request a TRN journey

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/AuthorizeAccessLinkGenerator.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/DateOfBirth.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/DateOfBirth.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Email.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Name.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Name.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/NationalInsuranceNumber.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/PreviousName.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/PreviousName.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/RequestTrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/DateOfBirthTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/NameTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/PreviousNameTests.cs

We’re building an interim solution that replaces Galaxkey for requesting a TRN for NPQ participants. The name page has been split such that previous name is now in its own page.
Amend the name page following the changed [Request a TRN] designs in Figma.
Add a new page at /request-trn/previous-name.
If the ‘Have you ever changed your name?’ question is not answered, show an error ‘Tell us if you have ever changed your name’. If ‘Yes’ has been answered but ‘Previous full name’ is empty, show an error ‘Tell us your previous name’.
When the form is valid and Continue is clicked, store the ‘has previous name’ and previous name on the FormFlow instance and redirect to /request-trn/date-of-birth .
If the name question has not yet been answered, redirect to /request-trn/name.
Amend the date of …

Split previous name and name into separate pages in request a TRN journey

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Program.cs

We don't have anything at the root of AuthorizeAccess (it returns a 404 currently). This adds a config-driven redirect which will point to AYTQ for deployed environments.

Add root redirect to AuthorizeAccess

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/EmbeddedSqlHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Procedures/fn_update_person_search_attributes_v1.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Procedures/p_refresh_name_person_search_attributes_v1.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Procedures/p_refresh_person_search_attributes_v1.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Triggers/trg_update_person_search_attributes_v1.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj

We're starting to get more and more postgres triggers and procedures. This rearranges them such that each version of a trigger/procedure is in its own file. A couple of helper methods simplify adding them to migrations.

Move trigger and procedure definitions into their own files

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/appsettings.Production.json
TeachingRecordSystem/src/TeachingRecordSystem.Worker/Infrastructure/Logging/HostApplicationBuilderExtensions.cs

Also updates the Sentry config for the `AuthorizeAccess` project to (largely) mirror the API.

Fix Sentry logging in Worker

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/CreateDateOfBirthChangeIncidentHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/CreateNameChangeIncidentHandler.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/CreateDateOfBirthChangeIncidentTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/CreateNameChangeIncidentTests.cs

Currently a plugin sets this to `false` when PII is updated on the `contact` record (and that update hasn't come from the API). That's arguably too late. This change sets this value to `false` as soon as a change of name/DOB request is created.

Set AllowPiiUpdatesFromRegister  when creating name/DOB change requests

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Address.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Address.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/DateOfBirth.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/RequestTrnJourneyState.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/RequestTrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/AddressTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/DateOfBirthTests.cs

Add an address page following the [Request a TRN] designs inFigma under /request-trn/address
All fields are mandatory except address line 2. All fields should have a length limit of 200 except postcode which should have a limit of 50.
When the form is valid and Continue is clicked, store the address on the FormFlow instance and redirect to /request-trn/check-answers .
If the NINO question has not yet been answered, redirect to /request-trn/national-insurance-number.
Page + tests

Add address page to request a TRN journey

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/CreateTrnRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/FindPotentialDuplicateContactsQuery.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/FindPotentialDuplicateContactsHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/PopulateNameSynonymsJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/NameSynonyms/INameSynonymProvider.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/NameSynonyms/NameSynonymProvider.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/NameSynonyms/ServiceCollectionExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Worker/Program.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/FindPotentialDuplicateContactsTests.cs

This extends first name synonym application to the duplicate detection used in the v3 TRN request endpoint.
As part of this I've moved the synonym download code out of the existing job (that populates the TRS DB) into its own service.

Consider first name synonyms when checking for existing contact

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/DataAnnotations/EvidenceFileAttribute.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/DateOfBirth.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Email.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Identity.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Name.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/NationalInsuranceNumber.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/PreviousName.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/DateOfBirthTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/EmailTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/IdentityTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/NameTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/NationalInsuranceNumberTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/PreviousNameTests.cs

The initial content for error messages for the Get a TRN was lifted from other pages or guesstimated by us developers. We now have ‘proper’ content.
Update error message content to align with internal spreadsheet (checking in with content desginer for any additional scenarios).
Error messages on pages + tests

Aligned error messages for Request a TRN journey with final content design

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/GetQtls.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/SetQtls.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/ApiModels/QtlsInfo.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Controllers/PersonsController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Requests/SetQtlsRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Validators/SetQtlsRequestValidator.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/VNext/SetQtlsDateRequestTests.cs

While working on DTO versioning I noticed the QTLS endpoints are using an `ApiModel` from `Core` rather than a versioned one - this fixes that.
I've also fixed up some Swagger annotations on the endpoints and removed a TRN validation test - we've moved away from that in the v3 endpoints.

Add versioned ApiModel for QtlsInfo

---

CHANGELOG.md
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/FindPersons.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/GetPerson.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240101/Controllers/TeacherController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240101/Controllers/TeachersController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Controllers/PersonController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Controllers/PersonsController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Controllers/TeacherController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Controllers/TeachersController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Requests/CreateDateOfBirthChangeRequestRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Requests/CreateNameChangeRequestRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Requests/FindPersonsRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Requests/GetPersonRequestIncludes.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Responses/FindPersonsResponse.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Responses/GetPersonResponse.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Validators/CreateDateOfBirthChangeRequestValidator.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Validators/CreateNameChangeRequestValidator.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Validators/FindTeachersRequestValidator.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/TestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240606/CreateDateOfBirthChangeTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240606/CreateNameChangeTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240606/FindTeachersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240606/GetPersonByTrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240606/GetPersonTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240606/GetPersonTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240606/TestBase.cs

This moves all `/teacher` and `/teachers` endpoints to `/person` and `/persons`, respectively. The PR looks large but it's largely copy/paste.
I've also renamed `email` to `emailAddress`, to be consistent with what we're now doing on the TRN request endpoints.

Rename teacher endpoints to person

---

docs/workforce-data-import/monthly-process.md

There are a number of manual steps which need to be completed for the monthly TPS extract data to be imported into production.
Add a workforce-data-import folder and .md file to the [docs](https://github.com/DFE-Digital/teaching-record-system/tree/main/docs) folder in git which documents the steps needed to import the files each month.
Check how the markdown looks in github in the branch

Added documentation for workforce data monthly import

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/CheckAnswers.cshtml
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/CheckAnswersTests.cs

Tiny change to display the word "None" rather than "No" next to the label National Insurance number if a user has said that they don't have a NINO

Small content change to request a TRN journey check answers page

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Processing/PublishEventsBackgroundService.cs

Previously we would abort the transaction that marks events as published when cancellation is requested. This change instead breaks out of the publishing loop early but completes that transaction.

Tidy cancellation handling in PublishEventsBackgroundService

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrnGenerationApi/ServiceCollectionExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrnGenerationApi/TrnGenerationApiClient.cs

We've got a few timeout errors in Sentry that originate from `TrnGenerationApiClient.GenerateTrn()`. This adds retries and significantly reduces the request timeout from the default 100 seconds to 5.

Shorten timeout and add retries to TrnGenerationApiClient

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V1/Handlers/GetTeacherHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/GetPerson.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/DataCollectionExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/DataverseAdapter.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V1/UnitTests/GetTeacherHandlerTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240101/GetTeacherTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240606/GetPersonTestBase.cs

Update v1 & v3 getteacher endpoints to use contact.inductionstatus
https://trello.com/c/ek0fcrle/54-update-api-to-use-contact-level-induction-status

Change endpoints to return contact.inductionstatus

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/PersonEmploymentMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240611134629_PersonEmploymentsAddNinoAndPostcode.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240611134629_PersonEmploymentsAddNinoAndPostcode.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/PersonEmployment.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Procedures/fn_delete_person_employments_person_search_attributes_v1.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Procedures/fn_insert_person_employments_person_search_attributes_v1.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Procedures/fn_update_person_employments_person_search_attributes_v1.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Procedures/p_refresh_person_employments_person_search_attributes_v1.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Procedures/p_refresh_person_search_attributes_v3.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Triggers/trg_delete_person_employments_person_search_attributes_v1.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Triggers/trg_insert_person_employments_person_search_attributes_v1.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Triggers/trg_update_person_employments_person_search_attributes_v1.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Models/PersonEmployment.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/PersonEmploymentUpdatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/NewPersonEmployment.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/TpsCsvExtractProcessor.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/UpdatedPersonEmployment.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/UpdatedPersonEmploymentEndDate.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/UpdatedPersonEmploymentEstablishment.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/PersonMatching/PersonMatchingServiceTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/TpsCsvExtractProcessorTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePersonEmployment.cs

The current person search used by the One Login integration uses the NINO from DQT/TRS only. Now that we have NINO from workforce data to we should include this to improve the chances of matching using NINO. We may use the person’s postcode to match on in future as well so we should populate this too.
Amend the process that imports workforce data to populate person_search_attributes with the NINO and person’s postcode, where available.
N.B. a database trigger on the appropriate workforce data tables is probably the way to go for this, similar to what we’re doing with the person table.
DB migrations + code + tests

Add NINO and postcode from workforce data into person_search_attributes

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/BackfillNinoAndPersonPostcodeInEmploymentHistoryJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/TpsCsvExtractProcessor.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/UpdatedPersonEmploymentNationalInsuranceNumberAndPersonPostcode.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/TpsCsvExtractProcessorTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePersonEmployment.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateTpsCsvExtract.cs

We have added `national_insurance_number` and `person_postcode` fields to the `person_employments` table and amended the TPS import process to populated them (triggers on the table will also populate the `person_search_attributes` table with this attributes).
These fields need to be populated for existing records based on the last 3 months workforce data.
Add an ad hoc job in Hangfire which populates the `national_insurance_number` and `person_postcode` fields in all existing `person_employments` records using the data in the `tps_csv_extract_items` table for previous imports.

Added backfill job to populate person_employments nino and person postcode

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/TpsCsvExtractProcessor.cs

The ad hoc job in Hangfire which populates the `national_insurance_number` and `person_postcode` fields in all existing `person_employments` records using the data in the `tps_csv_extract_items` table for previous imports errors in production as it is trying to update all records in one go.
Amend the query in `BackfillNinoAndPersonPostcodeInEmploymentHistory` in `TpsCsvExtractProcessor` to include `LIMIT 1000` to only update 1000 records at a time.

Amended BackfillNinoAndPersonPostcodeInEmploymentHistory to update records 1000 rows at a time

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240617143745_PersonSearchAttributesAttributeValueIncreaseLength.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240617143745_PersonSearchAttributesAttributeValueIncreaseLength.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/PersonSearchAttribute.cs

The `attribute_value` field in the `person_search_attributes` table is currently set to 100 characters, however it can be used to populate concatenated first name and last name fields which themselves can be 100 characters max.
Give ourselves some headroom for any future use of the `attribute_value` field in the `person_search_attributes` table and increase the field length to 1000 characters.

Increase length of attribute_value field in person_search_attributes table to 1000 characters

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/appsettings.Development.json
TeachingRecordSystem/src/TeachingRecordSystem.Api/appsettings.Production.json
TeachingRecordSystem/src/TeachingRecordSystem.Api/appsettings.json
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/appsettings.Development.json
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/appsettings.Production.json
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/appsettings.Development.json
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/appsettings.Production.json

We're not getting many logs in logit currently because of the `Error` minimum log level. This ups the level to `Information`.

Increase the Console log level to Information

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Infrastructure/Security/FormFlowJourneySignInHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Test.cshtml.cs

We've got some Sentry errors from bots hitting `/debug` and `/test`. Both are valid endpoints in `AuthorizeAccess` but they need a particular query parameter specifying to work correctly; when that's missing we get unhandled exceptions.
This changes both endpoints to return a `400 Bad request` response if the query parameter is missing (or invalid).

Fix errors from bot traffic

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/DqtReportingService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/EntityTableMapping.cs

Currently whenever we (or Microsoft) add attributes to CRM entities we need to add a migration to add the corresponding columns to the reporting DB. This change catches the error caused when columns are missing and adds the columns automatically.

Automatically add missing columns into reporting DB

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Controllers/OAuth2Controller.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/DfeAnalyticsEventDataKeys.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Infrastructure/Middleware/AddAnalyticsDataMiddleware.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Program.cs

We need to know what the calling service is for analytics events coming from Teacher Auth so that we can get service-specific stats. This adds an `application_user_id` entry to each web request event's `data`.

Add calling application user ID to Teacher Auth analytics events

---

TeachingRecordSystem/Directory.Packages.props
TeachingRecordSystem/src/TeachingRecordSystem.ServiceDefaults/Extensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.ServiceDefaults/TeachingRecordSystem.ServiceDefaults.csproj

We removed this for the AKS migration but we're about to start collecting metrics again.

Restore metrics endpoint

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/RefreshEstablishmentsJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/TpsCsvExtractProcessor.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/UpdatedPersonEmploymentEstablishment.cs

We previously created a job to refresh the person_employments with the “most open” version of an establishment based on the establishments imported from GIAS.
However, this took ages to run in production so needs to be optimised.
Optimise the code in the `UpdateLatestEstablishmentVersions` method in the `TpsCsvExtractProcessor` class to do an update in the database returning current and changed values, limiting changes to max 1000 records at a time (in a similar way to the other methods in that class).
Simplish change in the end.

Optimize job which updates person employments with latest establishment version

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/NpgsqlExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/TpsCsvExtractProcessor.cs

The TPS extract import job for June took a number of retry attempts due to timeouts when saving batches of TRS events relating to the updates.
Add an optional timeout setting to the `SaveEvents` extension method in `NpgsqlExtensions` and set this to 120 seconds for within the calls in the `TpsCsvExtractProcessor` class.
Simple change.

Added optional timeout when saving batches of events

---

TeachingRecordSystem/Directory.Packages.props
TeachingRecordSystem/src/TeachingRecordSystem.Api/appsettings.Production.json
TeachingRecordSystem/src/TeachingRecordSystem.Api/appsettings.json
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/appsettings.Production.json
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/appsettings.json
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/appsettings.Production.json
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/appsettings.json
TeachingRecordSystem/src/TeachingRecordSystem.Worker/appsettings.json

We went a little too far with increasing the log levels in https://github.com/DFE-Digital/teaching-record-system/pull/1381. This changes the minimum log level back to `Error` but includes a single `Information` `Request finished` entry per request for the web apps.

Reduce the console logs

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Models/ContactExtensions.cs

The `stated` `name` attributes should either be completely set or completely empty. For reasons yet unknown we have some records that have `stated` name attributes partially set; in these cases we're returning a half-empty name over the API. This amends the check for stated names to check that both stated first name *and* stated last name have been set.

Workaround partial stated name attributes

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/HostApplicationBuilderExtensions.cs
terraform/aks/app.tf
terraform/aks/dqt-reporting.tf

For review apps we won't have a reporting DB around so the k8s job to deploy migrations won't work. This moves migrations into the Worker app, guarded by the `DqtReportingService:RunService` configuration option, which will be `false` for review apps.

Move reporting DB migrations into Worker start up

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Processing/IEventObserver.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Processing/IEventPublisher.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Processing/NoopEventObserver.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Processing/NoopEventPublisher.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Processing/PublishEventsBackgroundService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Processing/ServiceCollectionExtensions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/TestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/TestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/TestScopedServices.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Events/Processing/PublishEventsBackgroundServiceTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/ApiKeys/AddApiKeyTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/ApiKeys/EditApiKeyTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/ApplicationUsers/AddApplicationUserTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/ApplicationUsers/EditApplicationUserTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/AddMq/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/DeleteMq/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Provider/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Specialism/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/StartDate/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Status/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/AddUser/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/EditUserTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/TestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/TestScopedServices.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/CaptureEventPublisher.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/Infrastructure/PublishEventsDbCommandInterceptor.cs

`OnEventSaved` is a bit of a misnomer as we don't call this when an event is saved, we call it to publish the event. As such rename the type to `IEventPublisher` and its method to `PublishEvent`.

Rename IEventObserver and its method

---

TeachingRecordSystem/Directory.Build.props
TeachingRecordSystem/src/TeachingRecordSystem.Core/CoreConstants.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/Index.cshtml.cs

Parsing a `dd/MM/yyyy`-style doesn't work on deployed environments since the culture is not set to en-gb. This explicitly passes that culture to the `Parse` method for the person search.

Fix date parsing on person search for deployment environments

---

docs/adr/data-model-decisions.md

Need a simple way to record data model decisions to support DQT to TRS migration
Simple file that should be included in the "Done When..." section of upcoming ERD related tickets.

added new data model decision record to support ERD changes

---

TeachingRecordSystem/Directory.Packages.props
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/TrsDbContext.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/TrsDesignTimeDbContextFactory.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Extensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/Establishments/Gias/EstablishmentRefresherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/Establishments/Tps/TpsEstablishmentRefresherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/PersonMatching/PersonMatchingServiceTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncServiceFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/TpsCsvExtractProcessorTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/DbFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/DbHelper.cs

The `/metrics` endpoint published database-related metrics with a `pool-name` that matches the connection string (minus the password). We don't really want to be exposing that. This PR moves to using `NpgsqlDataSource` with a `Name` of `TrsDb`; this changes the `pool-name` on the metrics to `TrsDb`.
It turns out `NpgsqlDataSource` is quite a nice thing to be passing around so I've updated a few places to use it over `IDbContextFactory<TrsDbContext>` (or the plain connection string).

Use NpgsqlDataSource

---

TeachingRecordSystem/src/TeachingRecordSystem.ServiceDefaults/Extensions.cs

The /metrics endpoint published database-related metrics with a pool-name that matches the connection string (minus the password).
James has done some work to fix this but it seems that something is still exposing the connection string minus password in the metrics.
The issue was tracked down to the DB health checks using a connection string

Amended DB health checks to use NpgsqlDataSource

---

.github/workflows/pr.yml

https://github.com/microsoft/mssql-docker/issues/892

Fix path to sqlcmd for DQT integration tests

---

terraform/aks/workspace_variables/dev.tfvars.json
terraform/aks/workspace_variables/pre-production.tfvars.json
terraform/aks/workspace_variables/test.tfvars.json

For syncing data from TRS into the DQT reporting DB we're relying on postgres' replication feature but that's not available in Burstable SKUs. This moves to the smallest General Purpose SKU.
Once data has been fully migrated from DQT these instances can be reverted to the Burstable SKU.

Amend non-prod postgres instances to support replication

---

terraform/aks/databases.tf

This is required for setting up the replication slot for syncing TRS changes into the DQT reporting DB.

Set postgres wal_level to logical

---

terraform/aks/app.tf

The `backoff_limit` of `1` means the migrations job will be retried once. We don't want to retry at all; if it fails the first time it will fail again.

Don't retry migrations job

---

TeachingRecordSystem/src/TeachingRecordSystem.Cli/Commands.MigrateDb.cs
terraform/aks/app.tf

Doing multiple commands from the k8s job wasn't working correctly. This puts the `alter user` in the CLI command itself and reverts the job to simply invoke that.

Fix applying migrations

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/AuthorizeAccessLinkGenerator.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Email.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/NotEligible.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/NotEligible.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/NpqCheck.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/NpqCheck.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/RequestTrnJourneyState.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/RequestTrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/NotEligibleTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/NpqCheckTests.cs

Some people are using the request TRN journey even though they’re not registering for an NPQ.
Add the ‘Do you plan on taking a national professional qualification (NPQ)?’ question to the beginning of the journey as shown in the Request a TRN Figma designs.
If ‘No’ is selected then show an error as per the designs.
If ‘Yes’ is selected, proceed to the email address page.
If no option is selected, show an error ‘Tell us whether you plan on taking a national professional qualification (NPQ)’.
Page changes + tests

Add check to see if user requesting a TRN is intending to do an NPQ

---

TeachingRecordSystem/Directory.Build.props
TeachingRecordSystem/TeachingRecordSystem.sln
TeachingRecordSystem/gen/TeachingRecordSystem.Api.Generator/TeachingRecordSystem.Api.Generator.csproj
TeachingRecordSystem/gen/TeachingRecordSystem.Api.Generator/VersionedDtoGenerator.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/TeachingRecordSystem.Api.csproj
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/GenerateVersionedDtoAttribute.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240101/Responses/FindTeachersResponse.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240416/Controllers/TeacherController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240416/Requests/GetTeacherRequestIncludes.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240416/Responses/GetTeacherResponse.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Controllers/PersonController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Responses/CreateDateOfBirthChangeResponse.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Responses/CreateNameChangeResponse.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Responses/FindPersonResponse.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Responses/GetPersonResponse.cs

In working on a new version of an API endpoint I've run into issues with API model duplication. Amending a type in the new version that's re-used across multiple endpoints requires redefining every controller action, request, response and API model type that is in the dependency graph to keep schema generation happy - this is too much pain.
This PR resurrects and tidies up an old source generation POC I did some time ago. With it you can annotate a type with `[GenerateVersionedDto(<some type>)]` and a partial declaration will be generated with all the members of the referenced type. Other referenced types will be generated recursively. This means you can have a stub type like:
```cs
[GenerateVersionedDto(typeof(SomeOldVersion.Responses.GetPersonResponse))]
public partial record …
```

Add a source generator to generate versioned DTOs

---

terraform/aks/databases.tf

From the Azure docs:
> The PG Failover Slots extension enhances Azure Database for PostgreSQL flexible server when operating with both logical replication and high availability enabled servers. It effectively addresses the challenge within the standard PostgreSQL engine that doesn't preserve logical replication slots after a failover. Maintaining these slots is critical to prevent replication pauses or data mismatches during primary server role changes, ensuring operational continuity and data integrity.

Add pg_failover_slots extension to postgres

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DistributedLockKeys.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/HostApplicationBuilderExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Worker/Program.cs

In production we have multiple worker instances and they're all trying to apply migrations at the same time. This adds a distributed lock check around applying migrations so that only once instance will run migrations.
I've also restored the default behaviour of stopping the app if a hosted service throws; we'd turned this off because of some early instability in `DqtReportingService` that's since been solved. Also, we definitely want the app to stop if any startup tasks fail (which are done via a hosted service) since important things (like these migrations) are done there.

Add a lock around applying migrations to reporting DB

---

terraform/aks/databases.tf
terraform/aks/variables.tf
terraform/aks/workspace_variables/production.tfvars.json

We're nearing capacity on our production postgres DB's storage. This doubles the size to 64GB.

Increase production postgres DB size to 64GB

---

TeachingRecordSystem/Dockerfile
terraform/aks/app.tf

We have a security recommendation to use a non-privileged port; this changes our web apps to use port 3000 instead of 80.

Use a non-privileged port

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Extensions.cs

We have a few jobs that run for longer than 30 minutes that are getting rescheduled even though they're still running. This change enables 'sliding invisibility timeout' which should fix that problem

Better handle long-running Hangfire jobs

---

TeachingRecordSystem/Directory.Packages.props
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/ExportWorkforceDataJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/Google/IStorageClientProvider.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/Google/OptionsStorageClientProvider.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/ServiceCollectionExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/WorkforceDataExportConfigureOptions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/WorkforceDataExportItem.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/WorkforceDataExportOptions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/WorkforceDataExporter.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/TpsCsvExtractProcessorTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/WorkforceDataExporterTests.cs

We want to get workforce data into BigQuery but we don’t yet have support for database syncs in the .NET DfE Analytics port. We’ve agreed to push a file into BQ for the D&I team to consume for now.
Create a job that pushes an Avro or Parquet file containing the contents of our tps_employments table into an encrypted GCS bucket (details TBD).

Added job to export Workforce Data to GCS

---

TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/TpsCsvExtractFileImporterTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/TpsCsvExtractProcessorTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/WorkforceDataExporterTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/WorkforceDataTestCollection.cs

The workforce data tests can clash with each other as they are writing and deleting from the same tables in the database.
This ensures they run separately.

Amended so that workforce data tests run don't clash with each other

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/DqtReportingService.cs

The `key` column in `trs_tps_employments` is causing things to blow up currently as it's not being escaped.

Handle reserved column names in TRS reporting sync

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/IdDbContext.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/SignInJourneyHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/OneLoginUserMatchRoute.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/SignInTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/SignInJourneyHelperTests.cs

When we migrate from ID to One Login and ‘Teacher auth’ for AYTQ, users will have to set up a new account. For those who were not matched automatically in ID and had to raise a support ticket there’s a fair chance they will have the same problem with Teacher auth. We’d like to relax the matching rules slightly for users who are coming from ID to reduce the chances of them needing to raise another support ticket.
Modify the matching process in Teacher Auth to look for an existing user in ID that has the same email address as the One Login user and a TRN linked to their account with verification level `Medium`. If there is a match, check that the verified last name and DOB match the last name and DOB on the teaching record linked to the ID TRN. If they match, assign the TRN to the Teacher …

Try and match one login user to id user based on email and TRN

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/Infrastructure/OpenApi/AddSecuritySchemeOperationFilter.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Infrastructure/Security/AuthorizationPolicies.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Controllers/IttOutcomeController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Controllers/NpqQualificationsController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Controllers/TeachersController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Controllers/TrnRequestsController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Controllers/UnlockTeacherController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240101/Controllers/TeachersController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240307/Controllers/TrnRequestsController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240416/Controllers/TeachersController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Controllers/PersonsController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Controllers/TrnRequestsController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240814/Controllers/PersonsController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Controllers/PersonsController.cs

Until now we've used authorization policies exclusively to add security to API endpoints. In practice we've ended up with a policy-per-role. This change moves to using roles; we keep two policies, one for each authentication mechanism (API key vs ID/Authorize access token). This simplifies the setup and makes imminent changes for new roles easier to implement.

Simplify authorization policies & use roles

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/MandatoryQualification.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/AlertCreatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/IEventWithAlert.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Models/Alert.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/ReferenceDataCache.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/CrmClientFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/Establishments/Gias/EstablishmentRefresherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/Establishments/Tps/TpsEstablishmentRefresherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/PersonMatching/PersonMatchingServiceTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncServiceFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/TpsCsvExtractProcessorTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/WorkforceDataExporterTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.cs

Our tests currently create alerts using a DQT-like schema. This needs to be amended to use the new TRS schema.
Add a `WithAlert()`  method on `CreatePersonBuilder` and use a builder type (like MQs).
All properties should be optional.
If the alert type is not specified, choose a random alert type.
If the details property is not specified, use some lorem ipsum (`Faker.Lorem.Paragraph()`)
If the external link property is not specified, generate a fake URL.
If start date is not specified, generate a random date (see MQs).
If end date is not specified, use `null`.
If end is specified but is before start date, throw an exception.
Leave the existing `WithSanction()` method for now until we have fully migrated alerts from DQT to TRS.
-   [x] …

Add support for creating alerts against a person in the TRS database to use in tests

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-preprod.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-test.yml

As per [teacher-services-cloud/documentation/disaster-recovery-testing.md at main · DFE-Digital/teacher-services-cloud](https://github.com/DFE-Digital/teacher-services-cloud/blob/main/documentation/disaster-recovery-testing.md#prerequisites) we require a manual deploy workflow for DR
Add manual deploy to workflows
https://trello.com/c/m7VgZ94r/2033-trs-dr-deploy-workflow-setup
Workflows can be deployed manually and existing workflows continue working fine

Add manual deploy to workflows

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/FindPersonByLastNameAndDateOfBirth.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/FindPersonsByTrnAndDateOfBirth.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/GetPerson.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/ReferenceDataCache.cs

Our API implementation assumed we have a mapping from every DQT sanction code to a TRS alert type - that's not the case.

Handle 'redundant' alert types that are not being migrated

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Responses/GetPersonResponse.cs

We won't be storing this in TRS.

Remove induction periods from the latest API version

---

TeachingRecordSystem/src/TeachingRecordSystem.Cli/Commands.SyncPerson.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SyncAllMqsFromCrmJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SyncAllPersonsFromCrmJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncService.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Filters/CheckPersonExistsFilter.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs

When run in 'dry run' mode, DB transactions are not committed.

Add dry run support to TrsDataSyncHelper

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Address.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/DateOfBirth.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Email.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Identity.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Name.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/NationalInsuranceNumber.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/NpqCheck.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/PreviousName.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/Details.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/EndDate.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/Link.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/Reason.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/StartDate.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/Type.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/AddMq/Provider.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/AddMq/Specialism.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/AddMq/StartDate.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/AddMq/Status.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/DeleteMq/Index.cshtml.cs

We have a pattern used in a few places of assigning model-bound properties from journey state in `OnPageHandlerExecuting` using `??=`. While this works fine in most places, as a general pattern it's not correct. Consider an 'edit' page that allows a field to be 'cleared' (i.e. set to `null`) but the journey state has non-`null`; if we use `??=` in `OnPageHandlerExecuting` we will incorrectly undo the assignment to `null` in `POST` requests.

Assign initial state in Get handlers

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Alert.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/AlertCreatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/AlertUpdatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Filters/CheckAlertExistsFilter.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/JourneyNames.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/PageContextFeatures.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/EndDate.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/StartDate.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/StartDate/AlertChangeStartDateReasonOption.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/StartDate/CheckAnswers.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/StartDate/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/StartDate/EditAlertStartDateState.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/StartDate/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/StartDate/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/StartDate/Reason.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/StartDate/Reason.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/AlertTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PageExtensions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/AddAlert/EndDateTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/AddAlert/StartDateTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/StartDate/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/StartDate/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/StartDate/ReasonTests.cs

Build out the TRS console as per the Figma designs, ensuring that an AlertUpdatedEvent is created with the original and changed start date.

Implemented Edit an alert start date journey + tests

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/StartDate/Index.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/StartDate/IndexTests.cs

Following clarification with the business, we do not want to allow the start date to be set in the future.
Also, start date can only be amended where there is no end date (i.e. only amended for active alerts).
If there is an end date for the alert return 400 Bad Request.
Add validation to ensure start date is not in the future.

Tweaks to edit start date validation

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/AlertCreatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/AlertDqtDeactivatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/AlertDqtImportedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/AlertDqtReactivatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/AlertMigratedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/AlertUpdatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Models/Alert.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.Alert.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.MandatoryQualification.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.cs

This extends the alert sync job to create audit events too.
The logic and tests here are lifted directly from what we've done for MQs.

Alert audit history to alert sync

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/ClearAlertsJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SyncAllAlertsFromCrmJob.cs

This adds a job to clear alerts and their events (since I ran the migration on prod when the dry-run flag wasn't be observed 🙈).
It also adds a couple more migration jobs so we have:
* dry-run;
* copy data without a migration event;
* copy data with a migration event.
We may well schedule the 'copy data without a migration event' job to run on a schedule once we've got the reporting table in place so that reports can be amended pre-migration.

Add more alert migration jobs

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/JourneyNames.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/Alert/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/Alert/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/EndDate/AlertChangeEndDateReasonOption.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/EndDate/CheckAnswers.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/EndDate/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/EndDate/EditAlertEndDateState.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/EndDate/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/EndDate/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/EndDate/Reason.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/EndDate/Reason.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/StartDate/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/AlertTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PageExtensions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/EndDate/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/EndDate/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/EndDate/ReasonTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/TeachingRecordSystem.SupportUi.Tests.csproj

Build out the TRS console as per the Figma designs ensuring that an AlertUpdatedEvent is created with the original and changed end date.
The endpoint for the start of this journey should be `/alerts/{alertId}/end-date`
If the alert does not already have an end date (i.e. is active) then return a 400 Bad Request response.
This journey will be accessed from a `Change` action on the previous alerts detail page (which is not in the scope of this card).
UI + tests

Create edit an alert end date journey in trs console

---

.github/workflows/pr.yml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/JourneyNames.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/CloseAlert/CheckAnswers.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/CloseAlert/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/CloseAlert/CloseAlertReasonOption.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/CloseAlert/CloseAlertState.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/CloseAlert/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/CloseAlert/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/CloseAlert/Reason.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/CloseAlert/Reason.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/AlertTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PageExtensions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/CloseAlert/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/CloseAlert/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/CloseAlert/ReasonTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs

Build out the TRS console as per the Figma designs ensuring that an `AlertUpdatedEvent` is created with the original (i.e. null) and changed end date.
The endpoint for the start of this journey should be `/alerts/{alertId}/close`
This journey will be accessed from a `Close Alert` action on the current alerts detail page (which is not in the scope of this card).
UI + tests

Implemented close alert journey

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Filters/CheckPersonExistsFilter.cs

When an alert cannot be synced because its `Person` hasn't been synced yet we forcibly sync the person. In dev we have a few invalid records that are causing errors. This tweak passes along the `ignoreInvalid` flag so we get a better error message in such situations.

Propagate the 'ignore invalid' flag when syncing an alert's Person

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncService.cs

We're still getting out of memory exceptions, even after increasing the worker's memory. This halves the page size used for backfill queries to reduce the memory requirement.

Reduce the page size in TrsDataSyncService

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/JourneyNames.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/EndDate/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/ReopenAlert/CheckAnswers.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/ReopenAlert/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/ReopenAlert/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/ReopenAlert/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/ReopenAlert/ReopenAlertReasonOption.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/ReopenAlert/ReopenAlertState.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/AlertTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PageExtensions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/ReopenAlert/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/ReopenAlert/IndexTests.cs

Build out the TRS console as per the attached Figma designs ensuring that an `AlertUpdatedEvent` is created with the original and changed end date.
The endpoint for the start of this journey should be `/alerts/{alertId}/reopen`
This journey will be accessed from a Remove action next to and end date on the previously closed alerts detail page (which is not in the scope of this card).

Implemented re-open alert journey + tests

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/EventMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241003094321_RemovePayloadFromEventIndex.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241003094321_RemovePayloadFromEventIndex.cs

We've got errors caused by trying to insert records that exceed the maximum row size allowed by `ix_events_person_id_event_name`. That index is large because it includes the `payload` column; this change removes it.

Remove the payload column from event index

---

TeachingRecordSystem/Directory.Packages.props
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/AlertMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/AlertTypeMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/QualificationMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Alert.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/AlertType.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Person.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/TrsDbContext.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj

This adds navigation properties from `Alert` to `AlertType` and from `AlertType` to `AlertCategory` so we can more easily write queries that return alerts, their type and their category.
I've added an `Alerts` property to `Person` (and `Qualifications`) too.
In addition this adds `EntityFrameworkCore.Projectables` so that we can have queries that include computed properties but run on the DB. In this case we're using it for a new `IsActive` property on `Alert`.

Add navigation properties to Alert models

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/TrsDbContext.cs

We don't want navigation properties to lazy load, we want to be explicit about the data we need upfront in the queries.

Throw on lazy loading

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/EventBase.cs

We want to be able to evolve events by adding new properties with the required modifier (so that we can ensure they're initialized correctly everywhere) but we don't want to break deserialization for older events that are missing those new properties. This removes all required constraints from properties when deserializing events.

Allow deserializing events with missing properties

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/Infrastructure/RateLimiting/ClientIdRateLimiterOptions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Infrastructure/RateLimiting/ServiceCollectionExtensions.cs

This removes the duplicate client ID lookup and revises the configuration setup to be more consistent with how we usually do it.

Tidy rate limiting configuration

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs

We're migrating deactivated alerts as deleted, just as we did for MQs. Until now we've used the deactivation time as the 'deleted on' timestamp. That's causing problems as it assumes the deactivation is the last action yet some production records have been updated _after_ their deactivation. (This would give us an audit trail that says a record has been updated after it's been deleted which clearly doesn't make sense.)
This change amends the migration process to use `$now` as the 'deleted on' timestamp. That way, we'll never have any audit records appearing after the 'deleted on' timestamp.

Amend DeletedOn to match migration time

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241007154621_AlertDqtSyncFields.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241007154621_AlertDqtSyncFields.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Alert.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/Migrations/0031_TrsAlertsSyncMetadata.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
TeachingRecordSystem/src/TeachingRecordSystem.Worker/appsettings.json

This adds alerts to the sync service so that TRS and the DQT reporting DB are updated in near-real time. I've added the `dqt_{first|last}_sync` tracking columns too.

Add Alerts to sync service

---

TeachingRecordSystem/Directory.Packages.props
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/ServiceCollectionExtensions.cs

A .NET service release has changed behavior around keyed service registrations in a way that breaks things for us. This fixes things.

Fixed keyed service registration for .NET service update

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/AlertCreatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/AlertDeletedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/AlertUpdatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/CloseAlert/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/DeleteAlert/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/EndDate/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/StartDate/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/ReopenAlert/CheckAnswers.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/AddAlert/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/CloseAlert/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/DeleteAlert/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/EndDate/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/StartDate/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/ReopenAlert/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs

The change reason field names in our Alert events are different from those for MQs. This unifies them.

Unify change reason field names in events

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/FeatureNames.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/FeatureProvider.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Filters/RequireFeatureEnabledFilter.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/_ViewImports.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Program.cs

We need to be able to check for enabled filters in views as well as the existing `IResourceFilter`. This moves all the logic into a `FeatureProvider` type. It also adds a `FeatureNames` class where we can list all the feature names.

Move feature flag detection into a FeatureProvider type

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/CrmQueryDispatcher.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/CrmQueryDispatcherExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Security/AssignUserInfoOnSignIn.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ChangeRequests/EditChangeRequest/Accept.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ChangeRequests/EditChangeRequest/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ChangeRequests/EditChangeRequest/Reject.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditDateOfBirth/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditName/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/AddUser/Confirm.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Program.cs

Currently the TRS Console requires each user to have an account in DQT so that we can use impersonation in API calls. We do this so that data changes have a ‘real’ user’s name in the audit history instead of a generic ‘TRS’ user. However, relatively few pages in the console are writing data to DQT.
This change adds a `WithDqtUserImpersonation()` extension method that can be used to selectively opt-in to user impersonation per-call. It's used in the few places where we write data to DQT only.

Only use impersonation for DQT write actions

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Filters/CheckPersonExistsFilter.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/PageContextFeatures.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.UpdatePerson.cs

Instead of going to DQT to get the person then checking it exists in TRS, go to TRS first and only go to DQT if the TRS lookup failed.

Amend filter that checks a person exists to check TRS first

---

.github/workflows/pr.yml

Until now we've run tests sequentially in the same job (aside from DQT integration tests). This moves each project into its own job that can be run in parallel. I've also removed the upfront solution build step (since it's already being done by the package process).
Combined, these changes more than half our PR workflow run times.

Split CI test execution into multiple jobs

---

.github/workflows/pr.yml
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/FindPersonsByTrnAndDateOfBirth.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/GetActiveContactsByTrnsHandler.cs

We've got an error in Sentry caused by a missing TRN passed to a CRM query. This adds a check that TRNs aren't empty before running the query.

Handle empty TRN in bulk search endpoint

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/GetPerson.cs

API users with the AB role only get ITT provider name so there's no way of knowing which ITT record is the latest. This change means the newest ITT record will be returned first.

Return newest ITT records first

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240920/Controllers/PersonsController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240920/Responses/GetPersonResponse.cs

This moves the special AB mapping logic out of the `PersonsController` and into the response class itself. We don't want to have to repeat all this logic for subsequent API versions in the controller action.
In future we should look at moving all the mapping logic into the `Response` classes but I've left that for another day.

Move mapping logic into response class

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/JourneyNames.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Link/AlertChangeLinkReasonOption.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Link/CheckAnswers.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Link/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Link/Conventions.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Link/EditAlertLinkState.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Link/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Link/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Link/Reason.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Link/Reason.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/AlertTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PageExtensions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/Link/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/Link/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/Link/ReasonTests.cs

Build out the TRS console as per the Figma designs (similar to Edit an alert start date) ensuring that an AlertUpdatedEvent is created with the original and changed link.

Implemented Edit alert link journey

---

terraform/aks/config/production.tfvars.json

We increased the API replicas from 2 to 4 to mitigate an incident recently but we've since solved the problem. This drops the replicas down to 3. Assuming that doesn't cause any issues overnight we can further reduce back down to 2 tomorrow.

Reduce API replicas to 3

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Program.cs

We've got folks who have an old authentication cookie who are still signed in but we've since changed their roles and they're not 'seeing' the change. Also, we should force users to sign in at least once a day. This adds an 8 hour lifetime to the authentication cookie.

Shorten the session lifetime for the TRS Console

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/FeatureNames.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Filters/RequireFeatureEnabledFilter.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/Conventions.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/MyRoles.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/MyRoles.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/appsettings.Development.json
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/appsettings.EndToEndTests.json
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/appsettings.Testing.json
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/appsettings.json

For testing UI that's affected by the current user's role it's useful to be able to easily swap the roles of the signed in user. This adds such a page at `/my-roles`, controlled by a feature flag (which will obviously never be enabled in production).
There are no tests for this since this is a debugging aid and our tests don't work the same way w.r.t. authentication so it would be difficult to test any way.

Add a page for updating signed in user's roles

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/EndDate/CheckAnswers.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/EndDate/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/EndDate/EditAlertEndDateState.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/EndDate/Reason.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/EndDate/Reason.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/AlertTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/EndDate/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/EndDate/ReasonTests.cs

The designs for the Edit end date journey have evolved since they were first built.
Align the implementation with the latest Figma designs.

Aligned End date journey with designs

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/CloseAlert/CheckAnswers.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/CloseAlert/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/CloseAlert/CloseAlertState.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/CloseAlert/Conventions.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/CloseAlert/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/CloseAlert/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/CloseAlert/Reason.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/CloseAlert/Reason.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Details/Reason.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/EndDate/EditAlertEndDateState.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/EndDate/Reason.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Link/Reason.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/StartDate/Reason.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/AlertTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/CloseAlert/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/CloseAlert/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/CloseAlert/ReasonTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/StartDate/ReasonTests.cs

The designs for the Close alert journey have evolved since they were first built.
Aligned the implementation with the latest Figma designs +
fixed an issue where navigating from check answers to the reason page lost any uploaded files 

Aiigned close alert journey with designs

---

terraform/aks/config/production.tfvars.json

The production TRS Console certificate expired without us noticing. This adds StatusCake alerts for the production TRS Console.
We don't have monitoring for Teacher Auth either (authorise-access-to-a-teaching-record.education.gov.uk) so that's added too.

Add TRS Console URLs to StatusCake monitoring

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/CloseAlert/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/ReopenAlert/CheckAnswers.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/ReopenAlert/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/ReopenAlert/Conventions.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/ReopenAlert/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/ReopenAlert/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/ReopenAlert/ReopenAlertState.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/AlertTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PageExtensions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/ReopenAlert/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/ReopenAlert/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/ReopenAlert/ReopenAlertTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/TestBase.cs

The designs for the Reopen alert journey have evolved since they were first built.
Align the implementation with the latest Figma designs.

Align reopen alert journey with designs

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/appsettings.json

Hopefully this removes the `MsalUiRequiredException` we see when calling the graph API with an 'old' session.

Match authentication cookie lifetime to access token lifetime

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/CountryMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/EarlyYearsTeacherStatusQualificationMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/QualificationMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/QualifiedTeacherStatusQualificationMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/RouteMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241029120016_AddQtsAndEytsQualificationTypes.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241029120016_AddQtsAndEytsQualificationTypes.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241029131635_Route.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241029131635_Route.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Country.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/EarlyYearsTeacherStatusQualification.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Person.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Qualification.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/QualifiedTeacherStatusQualification.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Route.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/TrsDbContext.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/InductionExemptionReason.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/QualificationType.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/RouteStatus.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/RouteToProfessionalStatusType.cs

This roughs out the `Route` type and extends `Qualification` to include QTS and EYTS. I've added a few dependent enums too, though many are currently empty.
I'm not wild about the `Route` naming but don't have anything better yet.

Add initial models for routes & QTS

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/EventMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241030101833_EventQualificationAndAlertIds.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241030101833_EventQualificationAndAlertIds.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Event.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/NpgsqlExtensions.cs

We've had a couple of needs arise in the last day or so to be able to query the `events` table for a specific alert. Today, that requires diving into the JSON `payload` and that's a little painful and not as quick as it could be.
This adds an `alert_id` column to `events` and adds an index. For symmetry, I've done the same for `qualification_id` too.
More PRs will follow to back-fill the data for these columns and to add the `events` table to the reporting DB.

Add QualificationId and AlertId to Event table

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AlertDetail.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AlertDetail.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/ReopenAlert/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Alerts.cshtml

The person alerts (for open alerts) and alert details (for closed alerts) pages currently have dummy links to the various journeys to edit / close / re-open / delete alerts.
Ensure all links related to alert journeys point to the appropriate “real” URLs.

Ensure alert links are pointing at appropriate endpoints

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241030104414_BackfillQualificationIdAndAlertId.cs
terraform/aks/app.tf

The last migration is timing out in prod. This increase the timeout and tweaks the migration a little (which may speed it up).

Give migrations more time to run

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AlertDetail.cshtml.cs

Alert details screen caused exception when change reason was null for a closed alert.
Allow change reason and/or detail to be null

Allow change reason and details to be null

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/EditUserTests.cs

https://github.com/DFE-Digital/teaching-record-system/pull/1643 made the change to allow creating users with no roles but the Edit User page still requires at least one role. This fixes that page too.

Allow updating users with no roles

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/CreateTrnRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/CreateTeacherQuery.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/FindPotentialDuplicateContactsQuery.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/CreateContactHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/FindPotentialDuplicateContactsHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/NameSynonyms/INameSynonymProvider.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240307/CreateTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240606/CreateTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/CreateContactTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/FindPotentialDuplicateContactsTests.cs

Updates the duplicate checking process to include NINO. If NINO alone is matched it's flagged as a potential duplicate (for manual review). If NINO and DOB match it's considered a definite duplicate and we return the record's TRN and mark the request as Completed.

Consider NINO when looking for duplicates

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/TrnRequestHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/GetTrnRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Controllers/OAuth2Controller.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/DebugIdentity.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/SignInJourneyHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/OneLoginUserMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/TrnRequestMetadataMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241107113402_TrnRequestMetadata.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241107113402_TrnRequestMetadata.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241107123546_NullableOneLoginUserFields.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241107123546_NullableOneLoginUserFields.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241107134330_OneLoginUserVerifiedByApplicationUserId.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241107134330_OneLoginUserVerifiedByApplicationUserId.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/OneLoginUser.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/TrnRequestMetadata.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/TrsDbContext.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/OneLoginUserMatchRoute.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/OneLoginUserVerificationRoute.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ConnectOneLoginUser/Connect.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/TestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/VNext/GetTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/OidcTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/SignInTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/SignInJourneyHelperTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateConnectOneLoginUserSupportTask.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateOneLoginUser.cs

Apply for QTS need to be able to pass us a One Login User ID with a TRN allocation request so that we can associate the One Login user with the resolved teaching record. This means that the user won't have to go through verification or matching when they sign in to AYTQ (with One Login).
This change adds a `trn_request_metadata` table in which we will stash the One Login user ID for a given request, if we have one. (This isn't going into the `trn_requests` table since we're not using that for new requests.)
Ideally we would link the One Login User to the teaching record at the point the support task is resolved but we don't have a simple and reliable way of doing that while support tasks are still managed in DQT. This puts the logic into our Get TRN request endpoint so that we can …

Link One Login user when TRN request is Completed

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/AlertUpdatedEvent.cshtml
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/ChangeLogAlertEventsTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/TestBase.cs

The change history page now shows details of events related to Alerts and has been manually tested.
The automated tests were split out into this separate PR in order to get the TRS Console deployed ASAP with alert change log events.

Added tests for alert change log UI

---

TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240814/FindPersonByLastNameAndDateOfBirthTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240814/FindPersonsByTrnAndDateOfBirthTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240912/SetQtlsDateRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/PluginTests/UpdateInductionStatusTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/GetInductionByContactIdTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs

We will shortly be adding the data model for induction to TRS for migration. We'll need a way to control whether induction data is written to CRM or TRS in tests. This renames the current `WithInduction()` method on `CreatePersonBuilder` to `WithDqtInduction()`; when we get the TRS version that can then take the `WithInduction()` name.

Rename TestData.WithInduction to WithDqtInduction

---

terraform/aks/storage.tf

https://trello.com/c/jZuPIctz/459-move-ewc-wales-integration-logic-into-trs
GTCWalesImport  import job is being moved from the SSIS import into TRS as a background job. This requires a storage container for processing the import files.

Added new storage container for dqt integrations

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/CrmQueryDispatcher.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/CrmTransactionScope.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/ICrmQueryDispatcher.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/ICrmTransactionalQuery.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/ICrmTransactionalQueryHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/ServiceCollectionExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/CrmQueryDispatcherExtensions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/CrmQueryDispatcherSpy.cs

Currently all our CRM query handlers run in their own transaction but we need to be able to support queries being part of a larger transaction that's managed at a higher level.
This change introduces new query and handler types: `ICrmTransactionalQuery` and `ICrmTransactionalQueryHandler`. The latter doesn't actually execute the query; it instead appends the query to a `RequestBuilder` and returns a delegate that can be executed by the caller once the transaction has been executed.
```cs
public record CreateContactTransactionalQuery(string FirstName, string LastName) : ICrmTransactionalQuery<Guid>
{
}
public class CreateContactTransactionalHandler : ICrmTransactionalQueryHandler<CreateContactQuery, Guid>
{
public Func<Guid> AppendQuery(CreateContactQuery query, RequestBuilder …
```

Add support for CRM query handlers that run inside a transaction

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/EndDate/Conventions.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/EndDate/Index.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/AddAlert/AddAlertTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/AddAlert/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/AddAlert/DetailsTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/AddAlert/LinkTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/AddAlert/ReasonTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/AddAlert/StartDateTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/AddAlert/TypeTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/CloseAlert/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/CloseAlert/CloseAlertTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/CloseAlert/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/CloseAlert/ReasonTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/Details/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/Details/DetailsTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/Details/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/Details/ReasonTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/EndDate/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/EndDate/EndDateTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/EndDate/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/EndDate/ReasonTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/Link/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/Link/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/Link/LinkTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/Link/ReasonTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/ReopenAlert/CheckAnswersTests.cs

We’ve started to refactor some of the tests for the the alert journeys. 
We should do the same for all alert journeys so they’re consistent.
Go through tests for all the alert journeys and refactor in a similar way to the edit alert start date tests

Refactored tests to cleaner consistent approach

---

.github/workflows/deploy.yml

Failing manual deployment workflow: https://github.com/DFE-Digital/teaching-record-system/actions/runs/11891562537/job/33132567400
Add the missing permission
Succesful run: https://github.com/DFE-Digital/teaching-record-system/actions/runs/11891998183/job/33134093047

[2148] Add missing permission for google auth on manual deploy

---

TeachingRecordSystem/Directory.Packages.props
TeachingRecordSystem/src/TeachingRecordSystem.Api/packages.lock.json
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/packages.lock.json
TeachingRecordSystem/src/TeachingRecordSystem.Cli/packages.lock.json
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Webhooks/WebhookOptions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Webhooks/WebhookSender.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
TeachingRecordSystem/src/TeachingRecordSystem.Core/packages.lock.json
TeachingRecordSystem/src/TeachingRecordSystem.ServiceDefaults/packages.lock.json
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/packages.lock.json
TeachingRecordSystem/src/TeachingRecordSystem.UiCommon/packages.lock.json
TeachingRecordSystem/src/TeachingRecordSystem.Worker/packages.lock.json
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/packages.lock.json
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/packages.lock.json
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/packages.lock.json
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/packages.lock.json
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/Webhooks/WebhookSenderTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/TeachingRecordSystem.Core.Tests.csproj
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/packages.lock.json
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/packages.lock.json
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/packages.lock.json
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/packages.lock.json
TeachingRecordSystem/tests/TeachingRecordSystem.UiCommon.Tests/packages.lock.json
TeachingRecordSystem/tests/TeachingRecordSystem.UiTestCommon/packages.lock.json

We're adding an [HTTP message signature](https://www.rfc-editor.org/rfc/rfc9421.html) to webhook messages so that receivers can confirm the message has come from us.
This updates `WebhookSender` to add the signature and its tests to check the signature can be verified successfully.
Most of the ceremony here is around DI since the provided extension methods in NSign don't allow scoping services to a specific `HttpClient` instance; I don't want things like `AddContentDigestOptions` to be around globally.

Add HTTP message signature to webhook messages

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/Endpoints/IdentityWebHooks/GetAnIdentityEndpoints.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Endpoints/IdentityWebHooks/WebHookEndpoints.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Endpoints/WebhookJwks.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/appsettings.Development.json
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Webhooks/ApplicationBuilderExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Webhooks/WebhookOptions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Webhooks/WebhookSender.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/HostFixture.cs

Receivers of webhook messages need to verify they've come from us. To do that they need access to our public keys so they can check messages have been signed by us. This exposes a `/webhook-jwks` endpoint to allow just that. The `kid` parameter here aligns with the key ID uses in the HTTP message signature.

Add a webhook-jwks endpoint

---

.editorconfig

This adds our convention for naming private fields with an underscore (and camel case) to .editorconfig. VS will pick this up and its suggested actions like 'Create and assign field ...' will take the naming into account.

Add private field naming rule to editorconfig

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/appsettings.Development.json
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Webhooks/ApplicationBuilderExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Webhooks/IWebhookSender.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Webhooks/WebhookDeliveryService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Webhooks/WebhookSender.cs
TeachingRecordSystem/src/TeachingRecordSystem.Worker/Program.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/Webhooks/WebhookDeliveryServiceTests.cs

This adds a `BackgroundService` that polls for due `WebhookMessages` and tries to send them with `WebhookSender`. If that's successful the message is marked as delivered. If not it's scheduled to be retried (unless we've run out of retries).
We query in relatively small batches within a transaction to try to keep the transaction relatively short. We send messages in parallel for the same reason. The `for update skip locked` means that if multiple instances of this service are running in parallel they won't be contending for the same messages.

Add a background service for delivering webhook messages

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/CreateTrnRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/SharedModels/Gender.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240307/Controllers/TrnRequestsController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Controllers/TrnRequestsController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/ApiModels/Gender.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Controllers/TrnRequestsController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Requests/CreateTrnRequestRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Validators/CreateTrnRequestRequestValidator.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/CreateTeacherQuery.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/CreateContactHandler.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/VNext/CreateTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/CreateContactTests.cs

https://trello.com/c/Yqh9vWpD/542-add-address-and-gender-fields-to-trn-allocation-api
Tests fail when setting Address fields to null, looking into it.

Add Address fields onto v3 trn request

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/Migrations/0038_TrsPersonsInductionSync.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj

Forgot to add some new Persons table columns to the reporting db schema.
The migrations here fix that.

Added missing induction sync columns to reporting db

---

terraform/aks/.terraform.lock.hcl
terraform/aks/config/production.tfvars.json

Use Google federated authentication in production. It's already been applied to the other environments successfully.
Set terraform variable to true
Compare with the other environments

[2124] Enable Bigquery federated authentication in production

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Alert.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/MandatoryQualification.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/DeleteAlert/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Details/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/EndDate/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Link/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/StartDate/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/ReopenAlert/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/AddMq/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/DeleteMq/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Provider/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Specialism/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/StartDate/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Status/Confirm.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Status/Confirm.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs

We're starting to get some repetition particularly around creating events and it will be compounded when we start adding more API endpoints that have corresponding UI.
This adds `Create`, `Update` and `Delete` methods to `Alert` and `MandatoryQualification` which all output events.

Add Create|Delete|Update methods to Alert and MQ

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241129152408_CpdInduction.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241129152408_CpdInduction.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Person.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/PersonInductionUpdatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/InductionExemptionReason.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/DataStore/Postgres/Models/PersonTests.cs

This updates the `Person` model to add `CpdInduction*` fields. We're tracking 'induction according to CPD' separately so that we can correctly infer the right status in all cases (since CPD doesn't know about all induction statuses).

Add methods to Person for changing induction

---

TeachingRecordSystem/src/TeachingRecordSystem.Cli/Commands.MigrateDb.cs

The `alter user...` statement won't work unless the DB exists but it's the `MigrateAsync` that ensures the DB exists. This reorders the statements.

Fix migrate-db command to work with missing database

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/GetQtls.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/SetQtlsDateHandler.cs

Reverts QTLS date handling fix as CRM changes have been made and no longer need to be handled in the api.

Revert "Fix QTLS date handling for BST (#1705)"

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Person.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs

I previously thought that `Failed` shouldn't come with either a start date or completion date but it should have both.

Require start date and completed date when InductionStatus is Failed

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/FindPersonByLastNameAndDateOfBirth.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/FindPersonsByTrnAndDateOfBirth.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240814/MapperProfile.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240814/Responses/FindPersonResponse.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240814/Responses/FindPersonsResponse.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Person.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/InductionStatus.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.Induction.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs

This adds a `ValidateInductionData` method onto `Person` and uses that everywhere for checking the right induction fields are provided for a particular status. It doesn't currently do the check for QTS (since we don't have that in TRS yet and it would complicate this method).
The status-specific rules are defined on attributes on the `InductionStatus` enum itself, in the same way we do for `MandatoryQualificationStatus`.
I've also moved the mapping from DQT statuses to TRS statuses onto this class.

Tidy induction field validation & centralise mapping from DQT statuses

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/IFeatureProvider.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Filters/RequireFeatureEnabledFilter.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/_ViewImports.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Program.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/Infrastructure/TestableFeatureProvider.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/TestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/TestScopedServices.cs

Currently feature flags cannot be overridden in a test; this adds an implementation of `IFeatureProvider` that's test-scoped that allows amending features:
```cs
FeatureProvider.Features.Add(FeatureNames.Alerts);
```

Add a mechanism for overriding features in a test

---

TeachingRecordSystem/src/TeachingRecordSystem.UiCommon/FormFlow/Filters/ActivateInstanceFilter.cs

If an invalid `ffiid` is provided to a page that has the `ActivatesInstanceAttribute` the original invalid `ffiid` parameter wasn't getting removed, causing an infinite loop since the first `ffiid` in the URL is always invalid. This fixes that.

Fix infinite redirect

---

TeachingRecordSystem/src/TeachingRecordSystem.Cli/Commands.SyncPerson.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Person.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncService.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncServiceTests.Induction.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncServiceTests.cs

Induction data is moving from DQT to TRS and we want to ensure TRS data is kept up to date with what’s in DQT.
Amend TrsDataSyncService to include induction data.
Also, extended sync-person CLI command to also sync induction data.

Sync induction changes in real time from dqt

---

.github/workflows/backup-db.yml

There is an error almost everyday around 4am and we haven't been able to identify the issue:
https://github.com/DFE-Digital/teaching-record-system/actions/runs/12289591518/job/34295330947
Move to 2am to see if the problem persists.
Code review

Schedule database backup at 2am

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/GlobalUsings.cs
TeachingRecordSystem/src/TeachingRecordSystem.Cli/Commands.WebhookEndpoint.cs
TeachingRecordSystem/src/TeachingRecordSystem.Cli/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/ApiSchema/VersionRegistry.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/WebhookEndpointMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241218104549_WebhookEndpointMetadata.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241218104549_WebhookEndpointMetadata.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/WebhookEndpoint.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Models/WebhookEndpoint.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/WebhookEndpointCreatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/WebhookEndpointDeletedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/WebhookEndpointUpdatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Webhooks/WebhookMessageFactory.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/GlobalUsings.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/Webhooks/WebhookDeliveryServiceTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/Webhooks/WebhookSenderTests.cs

These commands provide a temporary solution for managing webhook endpoints until we have some UI for doing so.
```shell
> trscli webhook-endpoint create --user-id "0b5b4d7a-f096-493f-aaea-9771fdeaff5c" --address "https://localhost:4200/webhook" --cloud-event-types alert.created alert.updated alert.deleted --api-version Next
{
"WebhookEndpointId": "e3809f55-71ff-41ff-8a6a-76b4b88219e1",
"ApplicationUserId": "0b5b4d7a-f096-493f-aaea-9771fdeaff5c",
"ApplicationUserName": "Developer",
"ApiVersion": "Next",
"Address": "https://localhost:4200/webhook",
"CloudEventTypes": [
"alert.created",
"alert.deleted",
"alert.updated"
],
"Enabled": true
}
```
```shell
> trscli webhook-endpoint list
[
{
"WebhookEndpointId": "e3809f55-71ff-41ff-8a6a-76b4b88219e1",
"ApplicationUserId": …
```

Add CLI commands for managing webhook endpoints

---

TeachingRecordSystem/Directory.Packages.props
TeachingRecordSystem/src/TeachingRecordSystem.Api/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/TeachingRecordSystem.Api.csproj
TeachingRecordSystem/src/TeachingRecordSystem.Api/appsettings.Development.json
TeachingRecordSystem/src/TeachingRecordSystem.Api/packages.lock.json
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/packages.lock.json

We've still got the basic auth configuration hanging around from when we used to host the Hangfire dashboard from the API. This removes it all.

Remove unused basic auth package

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/MandatoryQualificationSpecialism.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/MandatoryQualificationStatus.cs

I stumbled across this is passing - these mappings to DQT statuses are no longer required.
There are still a few references to DQT types hanging about but they're less quick to remove so they're saved for another day.

Remove some redundant DQT mappings from MQ types

---

.github/workflows/pr.yml
README.md
justfile

Add a just recipe to install Playwright

---

.github/workflows/pr.yml
justfile

We have a specific version of `dotnet-format` specified in local tools but our commands have been using the version in the current SDK.

Use local dotnet-format version

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Webhooks/ApplicationBuilderExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Webhooks/WebhookSender.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/Webhooks/WebhookSenderTests.cs

The HttpClient configuration wasn't getting picked up as it was registered against the concrete type instead of the interface. This fixes that.

Fix HttpClient registration for WebhookSender

---

TeachingRecordSystem/Dockerfile

Being able to query the reporting database in SQL server is a massive help in supporting any issues in TRS / DQT.
This change to add SQL server tools to the docker image allows us to do that from with an interactive session within a Kubernetes pod.

Added SQL Server tools to docker image

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SyncAllDqtContactAuditsJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SyncAllDqtInductionAuditsJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/BlobStorageAuditRepository.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/HostApplicationBuilderExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/IAuditRepository.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/CrmClientFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/ApiSchema/EventMapperTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/DqtOutbox/OutboxMessageHandlerTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/Establishments/Gias/EstablishmentRefresherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/Establishments/Tps/TpsEstablishmentRefresherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/PersonMatching/PersonMatchingServiceTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncServiceFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/TpsCsvExtractProcessorTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/WorkforceDataExporterTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestableAuditRepository.cs
terraform/aks/storage.tf

Pulling audit records from the API on-demand for induction syncing jobs is proving to be too slow. This adds jobs to push `contact` and `dfeta_induction` audits into blob storage. A follow-up change will amend the jobs to use this as the data source for syncing.

Sync audit details to blob storage

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Dtos/QtlsStatus.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Dtos/QtsInfo.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/FindPersonsBase.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/GetPerson.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Responses/FindPersonResponse.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Responses/FindPersonsResponse.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Responses/GetPersonResponse.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/ApiSchema/V3/VNext/Dtos/QtlsStatus.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/VNext/FindPersonByLastNameAndDateOfBirthTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/VNext/FindPersonsByTrnAndDateOfBirthTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/VNext/GetPersonByTrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/VNext/GetPersonTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/VNext/TestBase.cs

https://trello.com/c/sU0hEZYn/638-add-qtls-status-to-get-person-api

Added qtlsstatus to vnext getperson

---

TeachingRecordSystem/src/TeachingRecordSystem.Cli/Commands.SyncPerson.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SyncAllInductionsFromCrmJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Worker/appsettings.Production.json
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/CrmClientFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/ApiSchema/EventMapperTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Jobs/SyncAllInductionsFromCrmJobTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Jobs/SyncFromCrmJobFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Jobs/SyncFromCrmJobTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/DqtOutbox/OutboxMessageHandlerTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/Establishments/Gias/EstablishmentRefresherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/Establishments/Tps/TpsEstablishmentRefresherTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/PersonMatching/PersonMatchingServiceTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.Induction.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncServiceFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncServiceTests.Induction.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncServiceTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/TpsCsvExtractProcessorTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/WorkforceDataExporterTests.cs
terraform/aks/config/pre-production.tfvars.json
terraform/aks/config/production.tfvars.json

As the `SyncAllInductionsFromCrmJob` was run against more volumes of data, various issues came to light which needed fixing.
Various tweaks to ensure that all induction data and related audit history for dfeta_induction and contact table get synced correctly.

Added fixes while testing against CRM build environment data

---

TeachingRecordSystem/src/TeachingRecordSystem.Worker/appsettings.Production.json

Correct Serilog config to log warnings for any namespace starting with `TeachingRecordSystem`

Amend override for Serilog to log warnings for all Worker app namespaces

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SyncAllDqtIttAuditsJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SyncAllDqtQtsAuditsJob.cs

Given how long the audit sync for the `contact` entity took, I'm getting these in now well before we need the data.

Add jobs for syncing ITT and QTS audit records to blob storage

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/SetCpdInductionStatus.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/SetWelshInductionStatus.cs
TeachingRecordSystem/src/TeachingRecordSystem.Cli/Commands.SyncPerson.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SyncAllPersonsFromCrmJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Filters/CheckPersonExistsFilter.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.Person.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncServiceTests.Person.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.UpdatePerson.cs

We need to make sure that we also get any updated audit history when live syncing person details (from DQT contact).
This change makes it optional to also sync the audit history when syncing a person/contact.

Amend person sync to be able to also optionally sync contact audit too

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SyncDqtContactAuditsMopUpJob.cs

The job to sync all contact audit records from DQT to TRS took several days to run to completion.. during which time there may have been more changes in DQT.
This mop up job syncs all contact audit history records with any changes since Christmas Eve

Sync contact audit changes mop up job

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/AddAlertState.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/Details.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/Link.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/AddAlert/DetailsTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/AddAlert/LinkTests.cs

Make alert details optional on the add alert journey.
https://trello.com/c/cda4Dtiy/658-make-entering-details-about-the-alert-type-an-optional-field-on-the-create-alert-journey

Make alert details optional on add journey

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/BlobStorageAuditRepository.cs

The jobs to store ITT and QTS audit history in TRS needed to have `dfeta_initialteachertraining` and `dfeta_qtsregistration` added as aknown types to the serializer.

Added known types for entities we want to store audit details in blob storage for

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250108144947_RemoveDqtSyncAttributes.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250108144947_RemoveDqtSyncAttributes.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Alert.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/MandatoryQualification.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Qualification.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs

These attributes were added just in case we needed them around migration. We didn't, so now they're going.
We still have a few around `Person` but these can be tidied up later when induction migration changes are less frequent.

Remove DQT sync columns for migrated entities

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/EventBase.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Models/DqtInduction.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SyncAllInductionsFromCrmJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/BlobStorageAuditRepository.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.Induction.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncServiceTests.Induction.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs

Induction data is moving from DQT to TRS and we want to ensure TRS' data is kept up to date with what’s in DQT.
During testing the sync inductions job against prod data, it has become apparent that there are gaps in audit history data which means we can’t use them to build full snapshots of entities over time.
Amend the induction sync code in `TrsDataSyncHelper` to generate TRS events for `dfeta_induction` and `Contact` entities directly from audit history records.
The induction related eventshave been changed to just store any changed properties rather than a whole induction record snapshot.

Refactored sync induction job to generate DQT events from audit history partial entities

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/ReferenceDataCache.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Worker/appsettings.json
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.Induction.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/DbHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.cs

Induction data is moving from DQT to TRS and we want to ensure TRS' data is kept up to date with what’s in DQT.
We only recently had a full picture with regard to how induction exemption reasons would be migrated to TRS.
Enhance the induction sync code in TrsDataSyncHelper to also migrate induction exemptions reasons for persons who are exempt.

Add support for mapping DQT induction exemption reason to TRS induction exemption reason

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Webhooks/WebhookDeliveryService.cs

Once we've disabled an endpoint we shouldn't try to send messages to it until it's re-enabled.

Don't send webhook messages to disabled endpoints

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SyncAllInductionsFromCrmJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs

Unfortunately when live syncing for induction was enabled in production an exception was thrown related to incorrect CRM column names being queried.
Fixed job and helper to use the correct entity name and columns

Amended induction live sync so to use correct column names

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/CreateTrnRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/GetTrnRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/MapperProfile.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/ApiSchema/V3/VNext/Dtos/TrnRequestInfo.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250116092809_TrnRequestMetadataAllPii.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250116092809_TrnRequestMetadataAllPii.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/TrnRequestMetadata.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtOutbox/Handlers/TrnRequestMetadataMessageHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtOutbox/Messages/TrnRequestMetadataMessage.cs

We need to be able to return data submitted in the original TRN request from our API endpoints but currently that data isn't easily available. This is the first step to fixing that - stashing all data from all TRN requests in the TRS DB. A separate PR will follow to back-fill.

Write all TRN request data to TRS DB

---

.github/workflows/package.yml

`ubuntu-latest` has changed and has a newer version of the .NET SDK. For some reason that breaks `trscli`. This puts the package workflow back down to the old ubuntu version; we can review when we upgrade to .NET 9.

Fix migrations deployment

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/ChangeHistory.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/DqtContactInductionStatusChangedEvent.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/DqtInductionCreatedEvent.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/DqtInductionDeactivatedEvent.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/DqtInductionImportedEvent.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/DqtInductionReactivatedEvent.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/DqtInductionUpdatedEvent.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/InductionMigratedEvent.cshtml
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/ChangeLogInductionEventTests.cs

The TRS needs entries in the change history tied to events relating to induction details.
We are using audit history from DQT to generate events related to inductions in TRS.
Create the UI for each of the following events in the change history:
`DqtInductionImportedEvent`
`DqtInductionCreatedEvent`
`DqtInductionDeactivatedEvent`
`DqtInductionReactivatedEvent`
`DqtInductionUpdatedEvent`
`DqtContactInductionStatusChangedEvent`
`InductionMigratedEvent`

Added the change history UI for induction related events generated from DQT audit history

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/ProfessionalStatusMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250121102214_ProfessionalStatusSourceApplication.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250121102214_ProfessionalStatusSourceApplication.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/ProfessionalStatus.cs

The new API for professional statuses uses the source system's reference as an ID; this adds the two columns to do that, with an index.

Add SourceApplication references to ProfessionalStatus

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.Induction.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.Person.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestableAuditRepository.cs

Teachers with QTLS can potentially have an induction status without any dfeta_induction records associated with a Contact.
We are currently only live syncing any induction status changes for changes to the dfeta_induction table.
We need to also capture any changes to the induction status on the Contact table when the QTLS date changes alone as part of the Person live sync.
Amend the SyncPersons code in `TrsDataSyncHelper` to also generate any `DqtContactInductionStatusChangedEvent` events if there are any changes to the `Contact.dfeta_InductionStatus` field but only where the `Contact.dfeta_qtlsdate` field has changed too (i.e. the induction status has changed as a result of the QTLS date having changed). …

Amended person sync to create events if there are any QTLS related induction changes

---

TeachingRecordSystem/src/TeachingRecordSystem.Cli/Commands.SyncPerson.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/MigrateInductionsFromCrmJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Jobs/SyncAllInductionsFromCrmJobTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.Induction.cs

The job which syncs all induction records from DQT to TRS takes around 12 hours to run in Production.
We need a separate much quicker process to denote induction data as “migrated”.
There is now a separate job which generates the InductionMigratedEvent for all induction data which is now migrated to TRS.

Created job which just generates induction migrated events

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/CheckYourAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/CommonJourneyPage.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/CompletedDate.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/EditInductionState.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/ExemptionReason.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/InductionChangeReason.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/StartDate.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/Status.cshtml.cs

- Use primary constructors.
- Amended `protected` properties to `private`, where appropriate.
- Removed redundant `JourneyStartPage` assignments.

Tidy induction pages

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/BackfillDqtInductionEventEnumDescriptionsJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs

This replaces the database migration which timed out when trying to update induction events in prod
with a hangfire job which updates records in transactions of 1000 at a time.

Added job to backfill induction status and exemption reason descriptions in induction events

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/InductionMigratedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/InductionMigratedEvent.cshtml
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.Induction.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/ChangeLogInductionEventTests.cs

Use our `InductionStatus` enum and `ExemptionReasonId` instead of strings.

Use model types on InductionMigratedEvents

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/InductionExemptionReasonMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/PersonMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250206162245_InductionStatusWithoutExemption.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250206162245_InductionStatusWithoutExemption.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/InductionExemptionReason.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Person.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Models/Induction.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/PersonInductionUpdatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/PersonInductionUpdatedEvent.cshtml
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/DataStore/Postgres/Models/PersonTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/ChangeLogInductionEventTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditInduction/ChangeReasonTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditInduction/CheckYourAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditInduction/CommonPageTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditInduction/EditCompletedDateTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditInduction/EditExemptionReasonTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditInduction/EditInductionStateBuilder.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditInduction/EditInductionStatusTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditInduction/EditStartDateTests.cs

When an induction exemption is removed (e.g. because QTLS has gone away) we need to know what `InductionStatus` to set the person to. Previously, this wasn't possible - we weren't storing enough information.
This change adds an `InductionStatusWithoutExemption` property to `Person`. It contains the status that the person would have if they weren't exempt. When the last induction exemption is removed, we revert to this status. To make this work, we also need to leave the `StartedDate` and `CompleteDate` values intact when we initially change the status to `Exempt`.
This also removes the need for the separate `CpdInduction*` fields.

Remodel induction to handle removing exemptions

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250207144159_InductionExemptWithoutReason.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250207144159_InductionExemptWithoutReason.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Person.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Models/Induction.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/PersonInductionUpdatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/Migrations/0043_InductionExemptWithoutReason.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/DataStore/Postgres/Models/PersonTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/ChangeLogInductionEventTests.cs

We have lots of production data that has people with `InductionStatus` of `Exempt` without any exemption reasons. Currently, if we were to add another exemption reason then remove it we would incorrectly change the status to `RequiredToComplete`.
This change adds a separate flag - `InductionExemptWithoutReason` - that we check before undoing an `Exempt` status when removing a reason. If the flag is set, we keep the status as `Exempt`. Whenever the status is explicitly set, we clear this flag.

Handle exemptions without a reason

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/TrainingProviderMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250207130532_TrainingProviderUkprn.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250207130532_TrainingProviderUkprn.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250207145156_DqtReportingSyncTrainingProviders.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250207145156_DqtReportingSyncTrainingProviders.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/TrainingProvider.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/RefreshTrainingProvidersJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/Migrations/0044_TrsTrainingProviders.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/PublishApi/HostApplicationBuilderExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/PublishApi/IPublishApiClient.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/PublishApi/PublishApiClient.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/PublishApi/PublishApiOptions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
TeachingRecordSystem/src/TeachingRecordSystem.Worker/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.Worker/appsettings.json
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Jobs/RefreshTrainingProvidersJobTests.cs

We need a set of ITT providers that is shared with Register and we can associate with professional statuses in TRS.
Add a UKPRN field to the `training_providers` table in TRS.
Add a nightly job that calls the publish API and upserts the records into the TRS table. 
Note that some providers should be explicitly excluded (see the linked ticket).
Added trs_training_providers table to the reporting db.

Added Job to import ITT providers

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/EventMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250211110334_EventNameCreatedIndex.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250211110334_EventNameCreatedIndex.cs

We have a nightly job that's looking for particular event types within a time period - it's currently timing out. This adds an index to speed it up.

Add an index on events for event_name and created

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/InductionStatus.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/EditInductionState.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/Status.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/Status.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Induction.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditInduction/EditInductionStateBuilder.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditInduction/EditInductionStatusTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/InductionTests.cs

When the status is Exempt or FailedInWales, even if the logic says it's managed by CPD, don't show the warning message about it being managed by CPD and allow all the statuses
https://trello.com/c/rWMyoTUr

Different behaviour for statuses exempt and FailedInWales when ManagedByCpd

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/OutboxProcessorMetadataMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250212140318_OutboxMessageProcessorMetadata.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250212140318_OutboxMessageProcessorMetadata.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/OutboxProcessorMetadata.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/TrsDbContext.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtOutbox/DqtOutboxMessageProcessorService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtOutbox/OutboxMessageHandler.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/DqtOutbox/OutboxMessageHandlerTests.cs

It's possible we can see an outbox message multiple times (if, say, the entity changes service has to reset and replay messages due to a CRM change).
We also need to be able to skip some messages in dev that are invalid.
This change adds a metadata table to the DB that contains a timestamp. Any messages before or equal to this timestamp will be ignored. Every time we process a message we update this metadata with that message's timestamp. With this we avoid processing a message multiple times *and* we have a mechanism to skip bad messages in dev.
This also fixes `DqtOutboxMessageProcessorService` to run forever instead of running once then completing.

Don't process messages multiple times

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_Layout.cshtml

The 'Find a record' nav item shouldn't be active when we're within a specific record.
Also amends logic around showing the 'Users' tab to align with 'Application Users'.

Fix logic around 'Find a record' active nav item

---

.github/workflows/main.yml
Makefile
terraform/domains/environment_domains/output.tf

Add workflows for domain deployment to build workflow
updated deploy.yml adding calls to the deploy domains github actions. 
output.tf is added to provide external_urls for testing
updated Makefile to make domains-plan work for different environments 
Check successful run: https://github.com/DFE-Digital/teaching-record-system/actions/runs/13312646524
[Implement CI/CD for domains on all services](https://trello.com/c/qyXB3RQA/1972-implement-ci-cd-for-domains-on-all-services)

CI-CD for domains

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Induction.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Induction.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/InductionTests.cs

We have some people with an `InductionStatus` of `None` even though they have QTS. Currently we don't show the induction card or allow the status to be changed for `None`. This amends the logic to always show the card if the person has QTS.

Always show Induction card if person has QTS

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DistributedLockKeys.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtOutbox/DqtOutboxMessageProcessorService.cs

We're getting errors due to multiple nodes attempting to update metadata at once.

Prevent multiple nodes processing outbox messages at once

---

global_config/domains.sh

'make env domains-apply' is only running against the production environment, regardless of the env called.
see https://github.com/DFE-Digital/teaching-record-system/actions/runs/13371135644/job/37340178820
Remove CONFIG from domains.sh as this is overriding the env setting
make dev|test|pre-production|production domains-plan
make domains-infra-plan

Fix global_config for domains

---

Makefile

Domains apply during cicd run fails if any changes as AUTO_APPROVE is not passed to terraform,
see https://github.com/DFE-Digital/teaching-record-system/actions/runs/13412046506/job/37464799756
Update Makefile to use ${AUTO_APPROVE}
check code

Add AUTO_APPROVE to domains apply for cicd

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/CheckYourAnswers.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/CheckYourAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/Detail.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/Detail.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/TrsLinkGenerator.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/RouteDetailViewModel.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_RouteDetail.cshtml
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/DetailTests.cs

The details view for routes (comes after hitting 'edit route' on the qualification and routes tab) and also before committing changes.
I did this next because this page plus the 'routes and quals tab' ticket gives us some kind of user journey through.
Some, but not all of this ticket
https://trello.com/c/kcfqcyPh/800-routes-and-professional-status-front-end-edit-details-edit-cya-and-reasons
I used a partial because I think I can use it for both pages-  if not I'll split the views off later.

Routes details

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/InductionMigratedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/InductionMigratedEvent.cshtml
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/ChangeLogInductionEventTests.cs

Some people had statuses of `Exempt` without a `dfeta_induction` record; these people should have an `InductionMigratedEvent` created too.

Create InductionMigratedEvents when there's no dfeta_induction record

---

TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/DataStore/Postgres/DbContextTests.cs

We've had a few cases where we've changed models in some way and not generated a migration. This adds a test that to prevent that from happening.

Add a test that there are no DbContext changes not covered by a migration

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/Migrations/0048_TrsQualificationsProfessionalStatusType.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj

`professional_status_type` was added to TRS qualifications tables recently and so needs to be added to the reporting DB too

Add missing professional_status_type column to trs_qualifications in reporting db

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/FieldRequirement.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/ProfessionalStatusStatus.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/CheckYourAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/Detail.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/EndDate.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/EndDate.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/QuestionDriverHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/TrsLinkGenerator.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/RouteDetailViewModel.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_RouteDetail.cshtml
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/DetailTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/EndDateTests.cs

Add End date Page for routes
This can be reviewed and merged as it's under a feature flag. 
This PR includes unifying the two 'FieldRequirement' enums into one.
EndDate only shows on the details page if it's applicable to the route and status combo, and the change link will always appear if EndDate is applicable
EndDate page validation is kept simple - if you've asked to edit the end date you have to add a value (removes the need for for mandatory/optional checks)
https://educationgovuk.sharepoint.com.mcas.ms/:x:/s/TRATransformationTeamDocs/ETLJKljZyxJCig3Pz_sPH2sBMV8QMbXNBs0EZfpKxA9ZCg?e=SmjX7Z). 
- Added page
- Added Tests
https://trello.com/c/bX0M9P80/837-routes-and-professional-status-front-end-edit-journey-end-date

Add Enddate Page for routes

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/StartDate.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/StartDate.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/TrsLinkGenerator.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/RouteDetailViewModel.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_RouteDetail.cshtml
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/JourneyTests/EditRouteToProfessionalStatusTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/RouteToProfessionalStatusPageExtensions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/CheckYourAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/DetailTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/EditRoutePostRequestBuilder.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/EditRouteStateBuilder.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/StartDateTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/TestDataHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.UiTestCommon/AssertEx.cs

Edit start date
https://trello.com/c/xLpCCppQ/871-routes-and-professional-status-front-end-edit-journey-start-date
Like edit end date but with different validation. If editing start date invalidates end date, user is taken to the end date page

edit start date

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/CheckAnswers.cshtml

Get A Trn Journey has been experiencing users who are submitting multiple requests by double clicking the submit button from the CYA page. I've added prevent-double-click=true to the button to help mitigate the multiple requests.

Add prevent-double-click to the GetATrn journey

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/CreateTrnRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/appsettings.Testing.json
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/CreateTeacherQuery.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/CreateContactHandler.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/Startup.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240307/CreateTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/CreateContactTests.cs

There are rules in place that control whether we accept PII updates from Register over the API. Those rules rely on the value of the dfeta_allowpiiupdatesfromregisterattribute on the contact. The new TRN allocation API needs to be extended to populate that attribute.
Populate the dfeta_allowpiiupdatesfromregister attribute when creating a contact in the v3 TRN allocation endpoint. Its value should be true when the calling user ID is present in the AllowContactPiiUpdatesFromUserIds configuration array.

Populate dfeta_allowpiiupdatesfromregister based on AllowContactPiiUpdatesFromUserIds config setting

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/TpsEmploymentMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250401134352_TpsEmploymentEmployerEmailAddress.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250401134352_TpsEmploymentEmployerEmailAddress.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/TpsCsvExtractItemLoadErrors.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/TpsEmployment.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Models/TpsEmployment.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/TpsEmploymentUpdatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/BackfillEmployerEmailAddressInEmploymentHistoryJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/Migrations/0053_TpsEmploymentsEmployerEmail.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/NewTpsEmployment.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/TpsCsvExtractFileImporter.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/TpsCsvExtractProcessor.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/UpdatedTpsEmployment.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/UpdatedTpsEmploymentEmployerEmailAddress.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/UpdatedTpsEmploymentEndDate.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/TpsCsvExtractFileImporterTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/TpsCsvExtractProcessorTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePersonEmployment.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateTpsCsvExtract.cs

Workforce data is being used by the Find Teachers For Research application and a number of additional fields have been identified which would improve this.
Add a `employer_email_address` to the `tps_employments` table in TRS and amend the import job to include this field.
Add a backfill job to populate this field for the existing records in the `tps_employments` table.
Remember to include a migration for the reporting db.

Added employer email to workforce data

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/TpsCsvExtractFileImporter.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/TpsCsvExtractFileImporterTests.cs

The workforce data extract has been amended to include (and validate) the estblishment email address however when it was run in production it appears that some of the data has whitespace for the email address rather than just being empty - this is currently being rejected as invalid but really it could be trimmed and treated as null.
Amend the workforce data import to trim any whitespace from the establishment_email_address before validating it (empty is allowed).
Applied the same logic for member_email_address too.

Amended workforce data import to trim whitespace from email addresses

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Security/AlertAuthorization.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Security/AuthorizationPolicies.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/Conventions.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/AddUser/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/AddUser/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/Index.cshtml.cs

Updates user page authorization filter and conventions to use the `UserManagement` policy instead of the `Administrator` role
**To clarify:** these were the only instances within `TeachingRecordSystem.SupportUi` where roles were used instead of policies - there were other instances within `TeachingRecordSystem.Api` but those were out of scope of this PR

Update user page authorization to use policies instead of roles

---

.editorconfig
README.md
TeachingRecordSystem/TeachingRecordSystem.sln
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240807133540_RenameTpsEmployment.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250227173520_DegreeTypesTrainingSubjectsAndCountriesPopulation.cs

`.editorconfig` settings file was incomplete and didn't have all the settings necessary for code changes not to fail the linter on a PR build (only an issue if the user settings were different to the defaults)
* Update `.editorconfig` to include all the default settings and tweak so it conforms with current code conventions
* Add to solution so it can be used with Visual Studio Code Cleanup
* Update README file to document this and some other missing info around DB migrations

Update readme and editorconfig settings

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Validators/SetProfessionalStatusRequestValidator.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/V3/VNext/SetProfessionalStatusTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/SeedCrmReferenceData.cs

During testing of the new routes v3 API, discovered that some validation from the v2 API around mandating a training country code for iQTS route type had not been ported to this version.
Amend `SetProfessionalStatusRequestValidator` to ensure that the TrainingCountryReference field is populated for International Qualified Teacher Status route type + amend tests.

Amended validation to mandate country code for iQTS

---

.editorconfig
README.md

Removes line ending settings from .editorconfig to fix dotnet-format inconsistencies

Remove line ending settings from .editorconfig

---

CHANGELOG.md
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Dtos/TrnRequestInfo.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/CreateTrnRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/GetTrnRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Controllers/TrnRequestsController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/MapperProfile.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Requests/CreateTrnRequestRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Validators/CreateTrnRequestRequestValidator.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/ApiSchema/V3/VNext/Dtos/TrnRequestInfo.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/TrnRequestMetadata.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/TrnRequestHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/V2/Operations/GetOrCreateTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/V2/Operations/GetTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/V3/V20240307/CreateTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/V3/V20250203/CreateTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/V3/VNext/CreateTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/V3/VNext/GetTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/OperationTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/Startup.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/TestScopedServices.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/V3/CreateTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/V3/GetTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/TestScopedServices.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs

There are a few tests skipped here as we need a way of processing CRM outbox messages - that'll follow in a separate PR.

Add potential duplicate flag and AYTQ link to TRN allocation endpoints

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/CreateTrnRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/GetTrnRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250422155112_TrnRequestMetadataResolvedPersonId.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250422155112_TrnRequestMetadataResolvedPersonId.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/TrnRequestMetadata.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/CreateTeacherQuery.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/CreateContactHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtOutbox/Handlers/TrnRequestMetadataMessageHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtOutbox/Messages/TrnRequestMetadataMessage.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/TrnRequestHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/V3/GetTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/CreateContactTests.cs

During TRN allocation, when we've found a 'definite duplicate' (i.e. exactly one record matches with NINO and DOB), we return its TRN immediately with status `Completed`. However, if the `GET` endpoint were subsequently polled, we'd return a `404` since we have no record of the request in the `trn_requests` table (legacy) and we have no CRM `contact` with matching `dfeta_trnrequestid`.
This change adds `ResolvedPersonId` to `TrnRequestMetadata` and populates it during TRN allocation if the resolved record is known. Every time a `Pending` request is queried we check if it's been completed since the last time and populate `ResolvedPersonId` if it has been.
At some point we'll need a back-fill job to populate this field for all existing requests, since we won't have `dfeta_trnrequestid` …

Handle 'definite duplicate' TRN requests in GET endpoint

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/SupportTaskMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250424164400_SupportTaskTrnRequestMetadataLink.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250424164400_SupportTaskTrnRequestMetadataLink.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250424170249_TrnRequestPreviousNames.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250424170249_TrnRequestPreviousNames.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/SupportTask.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/TrnRequestMetadata.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtOutbox/Handlers/TrnRequestMetadataMessageHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtOutbox/Messages/TrnRequestMetadataMessage.cs

Adds a link between `SupportTask` and `TrnRequestMetadata` so we can associate a support task with a specific TRN request.
Also adds previous first & last name to `TrnRequestMetadata` as we'll need it for 'Get a TRN' requests going forward.
https://trello.com/c/8aPODZqj/1022-add-backend-support-for-support-tasks-related-to-trn-requests

Add back end additions for TRN request support tasks

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250425142820_PersonQtsDateAndEytsDate.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250425142820_PersonQtsDateAndEytsDate.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Person.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/Migrations/0054_QtsAndEytsDates.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.Person.cs

For person matching for TRN requests, we need to know who has QTS and EYTS. This adds `QtsDate` and `EytsDate` properties to `Person` and updates the person sync to populate them.
We'll need to do a full person sync to back-fill this.

Sync QTS and EYTS into TRS persons table

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TagHelpers/ColoredTagHelper.cs

We have designs that have coloured tags with an application user's name in, where the colour is random. This adds a tag helper that will produce GDS tag with a random, but deterministic, colour assigned based on the content.
```razor
<colored-tag>Register</colored-tag>
```

Add ColoredTagHelper

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/UserPermissionTypes.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/UserRoles.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Security/AuthorizationHandlers/ChangeManagementAuthorizationHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_Layout.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/AddUser/Confirm.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/AddUser/Confirm.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/AddUser/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/AddUser/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/AddUser/UserPermissionViewModel.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/AddUser/UserRoleViewModel.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TempData.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/wwwroot/Styles/site.scss
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/AddUser/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/AddUser/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/UsersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.UiTestCommon/AssertEx.cs

Following the access permissions redesign we need to update the Manage Users pages and journeys to reflect the new designs and functionality.
* Adds new add user pages under the `users` path using new user role designs
* Prevents non-Administrators from viewing the Administrator role/adding Administrator users

Create new "Add a User" journey

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/SupportTaskMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/TrnRequestMetadataMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250429081808_TrnRequestMetadataUserForeignKey.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250429081808_TrnRequestMetadataUserForeignKey.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/SupportTask.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/TrnRequestMetadata.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskCategory.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskData/ApiTrnRequestData.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskType.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/V3/CreateTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/V3/GetTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateApiTrnRequestSupportTask.cs

This adds an initial version of the list of open API TRN requests page. There are some things that are not yet aligned to the designs or missing:
- Search button alignment;
- pagination;
- sortable table.
These will follow separately.
Permission checks will also be a in separate PR.
https://trello.com/c/kvHCycNP/1055-add-ui-for-managing-api-trn-request-potential-duplicates

Add beginnings of list of API TRN requests

---

TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/JourneyTests/LegacyUserTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/JourneyTests/UserTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/TestUsers.cs

Fixes failing end-to-end tests caused by more than one add user test (legacy and new add user journeys) - meaning whichever add user test ran last failed as it was seeing the edit user page.

Fix end-to-end user tests

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/JourneyTests/UserTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/EditUserTests.cs

Following the access permissions redesign we need to update the Reactivate users journey to reflect the new designs and functionality.
* Adds reactivate action to edit user page
* Makes sure only Admins can reactivate other Admins

Add new reactivate user journey

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/TrnRequestMetadataMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250430074942_TrnRequestMetadataMatches.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250430074942_TrnRequestMetadataMatches.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/TrnRequestMetadata.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Filters/CheckSupportTaskExistsFilter.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/JourneyNames.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Conventions.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Matches.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Matches.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Merge.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Merge.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/ResolveApiTrnRequestState.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/MatchesTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateApiTrnRequestSupportTask.cs

This adds a page where a user can select a matched record for a TRN request, or choose to create a new one.
Highlighting attribute differences isn't included here but will follow separately. Gender isn't included yet either since we have some model changes to fix up.

Add page to choose potential duplicate for TRN request

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.DqtNote.cs

https://trello.com/c/S6eTf26f/1012-amend-notes-sync-job-to-exclude-notes-that-will-not-be-migrated-from-the-dqt
Don't allow syncing of notes with terms defined in the above trello ticket.
Added a few tests, but not for every term.
- Mixed casing
- Substring
- Exact match

Prevent syncing notes that contain certain text

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Models/IttQualificationExtensions.cs

During testing it was discovered that TRS degree type `6d07695e-5b5b-4dd4-997c-420e4424255c` was incorrectly mapping to ITT qualification `997` which is `Graduate Diploma` (and inactive ITT qual only available in prod).
This has now been removed so if this is called in future it will return a 400 Bad Request rather than 500 Internal Server Error

Removed incorrect degree type mapping to Graduate Diploma ITT qual

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/SignInJourneyHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/OneLoginUserMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/OneLoginUser.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/PersonMatchedAttribute.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/PersonMatching/IPersonMatchingService.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/PersonMatching/MatchResult.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/PersonMatching/PersonMatchingService.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Matches.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Matches.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TagHelpers/HighlightTagHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/wwwroot/Styles/site.scss
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/SignInJourneyHelperTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/PersonMatching/PersonMatchingServiceTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/MatchesTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateApiTrnRequestSupportTask.cs

This adds highlights to matched records to show which attributes on the matched `Person` are different from the TRN request.
I've repurposed the `OneLoginUserMatchedAttribute` enum and renamed it to `PersonMatchedAttribute`.
The method that figures out the differences is currently on the `Matches` `PageModel`; that'll likely move with the next PR so it can be re-used on the 'merge' page. The logic here is different to what we use for the matching; here we want to show all differences (even in case) whereas the matching is more permissive. (e.g. we could have a match on first name but still have differences between the two first names.)
https://trello.com/c/kvHCycNP/1055-add-ui-for-managing-api-trn-request-potential-duplicates

Show differences between matched record and TRN request

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/Migrations/0055_TrsQualificationsRemoveProfessionalStatusType.sql
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj

remove ProfessionalstatusType from the reporting DB qualifications table because it has been removed from the TRS qualifications table

remove ProfessionalstatusType from the reporting DB qualifications table

---

.github/workflows/dbml.yml

We don't need a DBML file producing for every push; being able to run it on demand is sufficient.

Don't produce dbml for every push

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/UserDeactivatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/AddUser/Confirm.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/AddUser/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser/Deactivate.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser/Deactivate.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser/DeactivateDefaults.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/UserPermissionViewModel.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/UserRoleViewModel.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/JourneyTests/UserTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PageExtensions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/AddUser/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/AddUser/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/EditUser/DeactivateTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/EditUser/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/UsersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/TestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/TestScopedServices.cs

Following the access permissions redesign we need to create a new deactivate user journey to reflect the new designs and functionality.
* Adds deactivate user page with the ability to add additional information and upload evidence

Add new user deactivate journey

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/CheckAnswers.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/Matches.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/Matches.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/Merge.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/Merge.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/ResolveApiTrnRequestState.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/wwwroot/Styles/site.scss
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/Resolve/MatchesTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/Resolve/MergeTests.cs

This adds the UI for selecting which attributes should be retained on the selected record vs copied from the TRN request.
I've also fixed the Matches page to redirect the user to Check Answers if 'I want to create a new record ...' is selected.
There a few rough edges here (mostly around content) but the snagging session on the journey as a whole will address those.

Choose attributes to merge from TRN request

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/SortDirection.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TagHelpers/SortableTableColumnTagHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/wwwroot/Styles/site.scss

MOJ design system includes a `sortable-table` component but it runs client-side. We need it to work with pagination so we need it to run server side. This adds a tag helper to aid with setting it up.
I've noticed we're referencing a very old version of moj-frontend; when we update we'll likely need to update this tag helper.
A PR showing this in use is at https://github.com/DFE-Digital/teaching-record-system/pull/2006

Add tag helper for generating a sortable-table

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/CreateTrnRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/CreateContactQuery.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/UpdateContactQuery.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/CreateContactHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/TrnRequestHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/ResolveApiTrnRequestState.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/V3/CreateTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/CreateContactTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/Resolve/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/TestScopedServices.cs

This will allow us to share the logic between the SupportUi and API. It should also make it simpler to run from Hangfire jobs.
I've removed the name normalization bits as we won't need it by the time this goes live.

Move contact creation and update to TrnRequestHelper

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.WebCommon/Infrastructure/TransactionScopeEndpoint.cs
TeachingRecordSystem/src/TeachingRecordSystem.WebCommon/TransactionScopeAttribute.cs

We have places where we want to enqueue a Hangfire job and update our DB atomically. We can do this if both of those operations are within a `TransactionScope`.
The challenge is we have a request-scoped `DbContext` so creating a `TransactionScope` in a Razor page handler is too late (since the `DbContext` may already be up and running for the request if it's been used in a filter).
This adds a mechanism for decorating a Razor page with `[TransactionScope]`; if that's present a `TransactionScope` will be setup immediately after the route has been identified. With that, all our filters and the page handlers will all share a `TransactionScope`.

Add mechanism for creating a TransactionScope around an endpoint

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/SupportTask.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskData/ApiTrnRequestData.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/Matches.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/Merge.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/ResolveApiTrnRequestPageModel.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/ResolveApiTrnRequestState.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ConnectOneLoginUser/Connect.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/Resolve/CheckAnswersTests.cs

This adds the resolved person attributes to the `SupportTask`s data. As part of this I've had to fix up how we're updating `Data` (it's a bit different since it's stored as JSON in the DB).
I've also pulled some of the common methods into a `PageModel` base class for the journey.

Add TRN Request resolution details to SupportTask data

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Event.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/AlertCreatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/AlertDeletedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/AlertUpdatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/EventBase.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/IEventWithOptionalPersonId.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/SupportTaskCreatedEvent.cs

We have an `IEventWithPerson` interface that's used for extracting the `PersonId` when we're saving events so we can populate the `person_id` column. This column is indexed and exists for querying events by person efficiently.
We have a few places coming up where events of the same type _might_ relate to a person but don't always. The `Guid PersonId` spec on `IEventWithPerson` doesn't work in that case.
This adds `IEventWithOptionalPerson` where `PersonId` is nullable.
I considered making `IEventWithPerson` have a `Nullable<Guid>` instead but it implies all our existing `IEventWithPerson` events can have null `PersonId` set, which isn't valid.
Another alternative would be to use `Guid.Empty` or some other well-known GUID but that seemed a little weird.

Add an interface for events that can possibly have a related Person

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/TrnRequestHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/CheckAnswers.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/Resolve/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/TestBase.cs

The TRN request API responses include a magic link for the person's registration with ID. The magic link is generated from a TRN token stored on the request metadata. This updates the support task resolution journey to populate the TRN token.

Generate a TRN token on request resolution

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/PageModelExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/Merge.cshtml.cs

The process to resolve a TRN request uses Person data from the TRS DB. This is synced in _near_ real time but can lag. Showing stale data on these pages, particularly when the user is choosing what person data to use, is not ideal.
This adds a proactive sync to GET requests for the pages that compare the matched record to the request and show the resolved person attributes. If the sync fails for whatever reason we won't block progress; we don't want a transient error or CRM slow-ness to prevent the journey being completed when 99% of time the data won't have changed.
Once this is live we can monitor and adjust when/where we do this sync and whether the 5 second threshold is sufficient.
We don't need a sync on the PersonDetail page (that we link to once the request is resolved) since …

Proactively sync matched Person before comparing attributes

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/UserMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250513102656_ApplicationUserShortName.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250513102656_ApplicationUserShortName.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/User.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/ApplicationUserUpdatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Models/ApplicationUser.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ApplicationUsers/AddApplicationUser.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ApplicationUsers/AddApplicationUser.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ApplicationUsers/EditApplicationUser.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ApplicationUsers/EditApplicationUser.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/ApplicationUsers/AddApplicationUserTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/ApplicationUsers/EditApplicationUserTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateApplicationUser.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.cs

We have places on our UI where we want to show a tag with an application user's name but some of our names are very long. This adds an optional 'short name' to `ApplicationUser` which we can use in tags.

Add optional 'short name' to application user

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/Scheduling/ExecuteImmediatelyJobScheduler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/Scheduling/HangfireBackgroundJobScheduler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/Scheduling/IBackgroundJobScheduler.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/Resolve/CheckAnswersTests.cs

When an API TRN request is resolved, the update to the DQT record is done in a background job. It's somewhat likely that a user will navigate to the created/updated record immediately after resolving the task so they may see stale data if the job hasn't yet completed.
This change passes the background job ID to the page that renders the link to the created/updated record so that it can wait for a bit for the job to complete. It'll only wait for up to 5 seconds; that should be sufficient most of the time.

Wait for background job to finish before rendering list of tasks

---

TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.cs

' characters in test names cause problems in a few places e.g. O'Reilly. While we would ideally be handling these by escaping the name, for now prevent those names from being generated at all.

Prevent 's in generated test names

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditDetails/CheckAnswers.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_PersonDetail.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/appsettings.EndToEndTests.json
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/JourneyTests/EditDetailsTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PageExtensions.cs

Currently a user is only able to change the Name and Date of Birth on a record within TRS. We need to develop the functionality for a user to be able to change any and all PII fields through the console.
https://trello.com/c/JA0sdQWB/1146-build-journey-for-changing-pii-in-the-trs-console
* Adds missing end-to-end tests for the above ticket

Add end-to-end tests for edit person details journey

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Person.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/EnumHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/ChangeHistory.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/PersonDetailsUpdatedEvent.cshtml
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/ChangeLogEditDetailsEventTests.cs

We need to be able to view PII changes in the Change history section of the console for a record.
https://trello.com/c/z0Rvrr3l/1105-2-implement-change-history-functionality-for-changing-pii-in-the-trs-console
* Adds change history entry for Edit Person Details

Add change history for Edit Person Details journey

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditDetails/CommonJourneyPage.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/CheckYourAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/CommonJourneyPage.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/CompletedDate.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/ExemptionReason.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/InductionChangeReason.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/InductionChangeReason.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/StartDate.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/Status.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditDetails/CommonPageTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditInduction/ChangeReasonTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditInduction/CommonPageTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditInduction/EditInductionStateBuilder.cs

Fixes a couple of issues with the Edit Induction journey:
1. If a user uploaded an evidence file but other fields were invalid on the page, the uploaded file would not be remembered when validation errors are displayed and the user would have to re-upload it
2. If the journey was cancelled any uploaded file would not be deleted
3. If an additional reason detail was previously given and the additional reason choice was later changed to "No", the additional reason detail would still be persisted to the journey
-   [N/A] Attach to Trello card
-   [N/A] Run DQT integration tests locally (if appropriate)

Fix Edit Induction journey to remember/delete previously uploaded files

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditDetails/IndexTests.cs

Live sync is currently broken due to a phone number that's more than 15 characters long. From a quick scan of the reporting DB there's a lot of bad data in the mobile number field.
This change will ensure we're not getting mobile numbers that are too long. We'll have to re-visit what to do about the bad values when we get to migrating the contact record.

Handle badly-formatted mobile numbers in sync

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/TpsCsvExtractProcessor.cs

The TPS import job is currently failing with a `Connection is busy` error.
This can sometimes happen when using the same EF DBContext to read and write data so the code has been amended to avoid this.

Amended code to avoid conflicts with EF dbContext reading and writing

---

CHANGELOG.md
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Controllers/PersonController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Controllers/PersonsController.EwcWales.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Controllers/PersonsController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Requests/FindPersonRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Requests/FindPersonsRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Requests/GetPersonRequestIncludes.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Responses/FindPersonResponse.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Responses/FindPersonsResponse.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Responses/GetPersonResponse.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/ApiSchema/V3/VNext/Dtos/DegreeType.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/ApiSchema/V3/VNext/Dtos/EytsInfo.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/ApiSchema/V3/VNext/Dtos/InductionExemptionReason.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/ApiSchema/V3/VNext/Dtos/InductionInfo.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/ApiSchema/V3/VNext/Dtos/ProfessionalStatusType.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/ApiSchema/V3/VNext/Dtos/QtsInfo.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/ApiSchema/V3/VNext/Dtos/RouteToProfessionalStatus.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/ApiSchema/V3/VNext/Dtos/TrainingAgeSpecialism.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/ApiSchema/V3/VNext/Dtos/TrainingCountry.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/ApiSchema/V3/VNext/Dtos/TrainingProvider.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/ApiSchema/V3/VNext/Dtos/TrainingSubject.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj

This also removes the `NpqQualifications` and `InitialTeacherTraining` `Includes`.
I've also added some additional information to `Induction` as CTR/AYTQ will need it.
https://trello.com/c/k8jCATfI/1177-routes-v3-get-api-endpoint

Add skeleton of next version of GetPerson API endpoint with routes

---

TeachingRecordSystem/src/TeachingRecordSystem.Worker/appsettings.json

We've got an error on pre-prod trying to sync `dfeta_sanction` records from DQT into the reporting database as we've deleted that table. This removes `dfeta_sanction` and `dfeta_sanctioncode` from the reporting service configuration as they're not used any more.

Remove DQT sanction tables from reporting sync

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/TeachingRecordSystem.AuthorizeAccess.csproj
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TeachingRecordSystem.SupportUi.csproj

The contents of the lib folder that we need are included into our stylesheet so we don't need these files publishing.

Don't publish wwwroot/lib folders

---

TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/Resolve/CheckAnswersTests.cs

Test was failing due to request timeout which caused a race condition in FakeXrmEasy - assert on response status to make the cause of failure more explicit

Assert on response to surface test failure caused by timeout

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Qualifications.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Qualifications.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/RouteToProfessionalStatusCreatedEvent.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/RouteToProfessionalStatusDeletedEvent.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/RouteToProfessionalStatusUpdatedEvent.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/CheckYourAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/Route.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/DeleteRoute/CheckYourAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/CheckYourAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/Detail.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/SubjectDisplayHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/ChangeLogProfessionalStatusEventsTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/QualificationsTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/AddRoute/CheckYourAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/DeleteRoute/CheckYourAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/CheckYourAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/DetailTests.cs

Add reference code to subjects wherever they're listed:
in edit details page, 
cya pages,
change history, 
qualifications tab
https://trello.com/c/eGPo4QFp/1243-routes-subject-specialisms-not-differentiatable
Also additions to the qualification tab Routes card - but not the coloured statuses
bug fix - don't list archived routes in the main routes drop-down

add reference code to subjects

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/ResyncAllPersonsJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.Person.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/IndexTests.cs

Our resync job is having most records ignored because of the guard we have in the sync process that prevents out-of-order updates. This removes that check. (We don't really need the out-of-order check - things will sort themselves out in the case that updates get replayed.)
I've increased the batch size too.

Fix resync ignoring already-synced records

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/RequireRouteWritesEnabledAttribute.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240912/Controllers/PersonsController.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20250425/Controllers/PersonsController.cs

During routes migration we want to be sure we're not getting any route writes coming through the API. Although we should have a block in place in CRM this gives us an extra layer of protection.
I've tested this locally but not added automated tests as we can't easily override configuration there currently.

Disable API endpoints that write routes via configuration

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Dtos/QtsInfo.cs

We have some pre-prod data where the person has a non-`null` QTS date but no routes migrated (yet). This tweaks the API's logic to handle the missing routes. This will be reverted once the data is fixed up.

Temporary API fix for semi-migrated pre-prod data

---

TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/V3/V20250425/SetPiiTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/UpdateContactPiiTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditDetails/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditDetails/CommonPageTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditDetails/PersonalDetailsTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.cs

We want to be using the model Gender enum in the tests rather than the CRM enum - so when contacts are migrated the tests won't need updating

Replace CRM gender with model gender in tests

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/NationalInsuranceNumber.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/Create/PersonalDetailsTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditDetails/PersonalDetailsTests.cs

TPS workforce data currently has NINOs in the form `QQ 12 34 56 A` | `AB 12 34 56 F` | `AB 12 34 56 M` | `AB 12 34 56 U` which are technically invalid NINOs. Relaxing validation to accommodate existing data

Relax NINO validation to allow for legacy TPS workforce data

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/EytsAwardedEmailsJobItemMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/InductionCompletedEmailsJobItemMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/InternationalQtsAwardedEmailsJobItemMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/QtsAwardedEmailsJobItemMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250704081507_EmailJobItemsTrnIndex.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250704081507_EmailJobItemsTrnIndex.cs

The email jobs that email when someone is awarded QTS/EYTS/iQTS or completes induction check we haven't already sent an email for the given TRN. This adds an index to the `trn` column to speed up that check.

Add indexes to trn column on email job item tables

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Security/AuthorizationHandlers/Legacy/LegacyNotesViewAuthorizationHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Security/AuthorizationHandlers/NotesViewAuthorizationHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Security/AuthorizationPolicies.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Security/NonPersonOrAlertDataAuthorization.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Security/Requirements/NotesViewRequirement.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Notes.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Notes.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/NotesTests.cs

We need to restrict access to the Notes section in certain scenarios where a user holds a DBS alert as the Notes may contain information that is not appropriate for all users to see.
https://trello.com/c/SL5pHmy2/1320-restrict-access-to-notes-based-on-user-permissions

Add authorization for notes

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/ChangeHistory.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/RouteToProfessionalStatusMigratedEvent.cshtml
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/ChangeLogProfessionalStatusEventsTests.cs

The background job which migrated ITT / QTS data from DQT into the TRS data structure generated a RouteToProfessionalStatusMigratedEvent for each migrated route.
This change allows details of this event to be displayed this in the Change History section for a person.

Added UI for route migrated event

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs

The ewc induction importer service got accidentally removed, which causes the ewc job to fail. This re-adds the service.

Re-add induction importer service for ewc wales

---

.github/workflows/pr.yml

Removes the 'TeachingRecordSystem.' prefix from the test reports.

Shorten test report names on CI

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/GetTrnRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/SignInJourneyHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250721161658_TrnRequestMetadataStatusOptional.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250721161658_TrnRequestMetadataStatusOptional.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/TrnRequestMetadata.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtOutbox/Handlers/TrnRequestMetadataMessageHandler.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrnRequests/GetTrnRequestResult.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrnRequests/TrnRequestService.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs

This updates `TrnRequestService.GetTrnRequestInfoAsync` to handle TRN requests that are resolved both in DQT and TRS. For tasks resolved in DQT we need to figure out the `TrnRequestStatus` ourselves; for the TRS ones the various task resolution journeys will sort that out.

Handle TRN requests in both DQT and TRS

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/CreateTrnRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/GetTrnRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/SupportTask.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrnRequests/TrnRequestOptions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrnRequests/TrnRequestService.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/CheckAnswers.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/OperationTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/Startup.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/TestScopedServices.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/V3/CreateTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/Resolve/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/Resolve/ResolveApiTrnRequestTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/TestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/TestScopedServices.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/DbFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateApiTrnRequestSupportTask.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateNpqTrnRequestSupportTask.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateTrnRequestManualChecksNeededSupportTaskAsync.cs

This creates a 'further checks needed' support task once the TRN request resolves to a known person and that person has an open alert, QTS or EYTS *and* the request came from Register or AYTQ.

Create 'further checks needed' tasks

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/EventMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250801110135_EventPersonIds.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250801110135_EventPersonIds.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Event.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/NpgsqlExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/IEventWithSecondaryPersonId.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/PersonsMergedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
terraform/aks/databases.tf

We have some events, notably `PersonsMergedEvent`, that relate to multiple Persons so our scalar `PersonId` event doesn't work. This adds a `PersonIds` property, an `IEventWithSecondaryPersonId` interface and updates the event mapping to populate it.
Subsequent PRs will follow to back-fill `PersonId`s, start using it, and finally to remove `PersonId`.

Add support for a secondary person ID in events

---

.github/workflows/actions/test/action.yml
TeachingRecordSystem/src/TeachingRecordSystem.Api/FeatureNames.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/Program.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/CreateDateOfBirthChangeRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/CreateDateOfBirthChangeRequestHandler_Dqt.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/appsettings.Development.json
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/EmailMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250804124340_AddEmailReplyToIdToEmail.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250804124340_AddEmailReplyToIdToEmail.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/TrsDbContextModelSnapshot.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Email.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/SupportTask.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskData/ChangeDateOfBirthRequestData.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskData/ChangeRequestEmailConstants.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskData/ChangeRequestOutcome.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/HostFixture.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/Startup.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/TestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/V3/V20240606/CreateDateOfBirthChangeTests_Dqt.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/OperationTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/Startup.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/TeachingRecordSystem.Api.UnitTests.csproj
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/TestScopedServices.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/V3/CreateDateOfBirthChangeTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/packages.lock.json
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/Infrastructure/ExecuteImmediatelyJobScheduler.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/Infrastructure/ExecuteOnCommitBackgroundJobScheduler.cs

The TRS Console currently allows users to manage Change name and change date of birth requests which are stored as “Cases” in DQT.
As part of migrating from DQT, we need to move these to be stored as support tasks in TRS.
Create a new record `ChangeDateOfBirthRequestData` in the `TeachingRecordSystem.Core.Models.SupportTaskData` namespace based on existing fields in `CreateDateOfBirthChangeRequestCommand` replacing `EvidenceFileUrl` with `EvidenceFileId`.
Amend `CreateDateOfBirthChangeRequestHandler` to create a `SupportTask` of type `ChangeDateOfBirthRequest` populating the `Data` field with a `ChangeDateOfBirthRequestData` record populated from the incoming request (when the feature flag is enabled otherwise call the existing code which creates cases in DQT).
Considerations:
- The …

Amended DOB change to create support task in TRS (behind feature flag)

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/CreateNameChangeRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/CreateNameChangeRequestHandler_Dqt.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/SupportTask.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskData/ChangeNameRequestData.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskData/ChangeRequestEmailConstants.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/V3/V20240606/CreateDateOfBirthChangeTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/V3/V20240606/CreateNameChangeTests_Dqt.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/V3/CreateNameChangeTests.cs

The TRS Console currently allows users to manage Change name and change date of birth requests which are stored as “Cases” in DQT.
As part of migrating from DQT, we need to move these to be stored as support tasks in TRS.
Create a new record `ChangeNameRequestData` in the `TeachingRecordSystem.Core.Models.SupportTaskData` namespace based on existing fields in `CreateNameChangeRequestCommand` replacing `EvidenceFileUrl` with `EvidenceFileId`.
Amend `CreateNameChangeRequestHandler` (use a feature flag to keep the existing DQT related functionality toggleable) to create a `SupportTask` of type `ChangeNameRequest` populating the Data field with a `ChangeNameRequestData` record populated from the incoming request.
Considerations:
- The incoming request populates the `EvidenceFileUrl` with an …

Added support for creating name change support tasks in TRS

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/NoteMapping.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250805162823_NoteCreatedBy.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250805162823_NoteCreatedBy.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250805165316_NoteFileId.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250805165316_NoteFileId.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250806074708_NoteContent.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250806074708_NoteContent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Note.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Models/Note.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/NoteCreatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/HtmlHelperExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/AddNote.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/AddNote.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Notes.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Notes.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.DqtNote.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/AddNoteTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/NotesTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/AddUser/ConfirmTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/AddUser/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/EditUser/DeactivateTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/EditUser/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/UsersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateDqtNote.cs

This also amends the notes view to preserve line breaks when rendering out notes. I'm not 100% sure all the HTML content we have from DQT will render correctly but we can tweak things later on.
For now I've added a separate column for plaintext content; notes from DQT will have HTML and notes created via this process will have plaintext content. We can look at consolidating those two columns later.
https://trello.com/c/7sEBSPDF/1407-create-functionality-to-add-new-notes-through-the-trs-console

Add UI to add a note

---

TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/NotesTests.cs

Creating two notes at the same time makes the test flaky due to the ordering.

Fix flaky notes test

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/ChangeDateOfBirthRequestSupportTaskApprovedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/ChangeDateOfBirthRequestSupportTaskCancelledEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/ChangeDateOfBirthRequestSupportTaskRejectedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/ChangeNameRequestSupportTaskApprovedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/ChangeNameRequestSupportTaskCancelledEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/ChangeNameRequestSupportTaskRejectedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskData/ChangeRequestEmailConstants.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ChangeRequests/EditChangeRequest/Accept.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ChangeRequests/EditChangeRequest/Accept.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ChangeRequests/EditChangeRequest/Reject.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/JourneyTests/ChangeRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/ChangeRequests/EditChangeRequest/AcceptTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/ChangeRequests/EditChangeRequest/RejectTests.cs

The TRS Console currently allows users to manage Change name and change date of birth requests which are stored as “Cases” in DQT.
These cases/requests are created when a teacher requests a change of details via AYTQ.
As part of migrating from DQT, we need to move these to be stored as support tasks in TRS.
Re-wire the `Accept` page at `TeachingRecordSystem.SupportUi.Pages.ChangeRequests.EditChangeRequest` to approve a change name or date of birth request `SupportTask` in TRS and update `Person` and `PreviousName` tables as appropriate + raise events + send emails.

Rewired Accept/Approved page for change requests to use TRS support tasks

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/FeatureNames.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ChangeRequests/EditChangeRequest/Accept.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ChangeRequests/EditChangeRequest/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ChangeRequests/EditChangeRequest/Reject.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/Index.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/appsettings.Development.json
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/appsettings.EndToEndTests.json
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/JourneyTests/ChangeRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/IndexTests.cs

The TRS Console currently allows users to manage Change name and change date of birth requests which are stored as “Cases” in DQT.
These cases/requests are created when a teacher requests a change of details via AYTQ.
As part of migrating from DQT, we need to move these to be stored as support tasks in TRS.
Amend the `Pages/SupportTasks/Index` page to get change date of birth and name requests from TRS instead of DQT i.e. `SupportTask` with `SupportTaskType` of `SupportTaskType.ChangeNameRequest` or `SupportTaskType.ChangeDateOfBirthRequest` with Status `SupportTaskStatus.Open`
Amend the `Pages/Index` page to add a tile for change requests which links to the above page (i.e.  `/support-tasks`).

Add tile for change requests and amend support tasks index to get change requests from TRS

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/PersonMatching/PersonMatchingService.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/V3/CreateTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/PersonMatching/PersonMatchingServiceTests.TrnRequest.cs

A match on NINO or email only should be considered possible matches (and not a definite match).
Also adds `COLLATE` to ensure the index on `person_search_attributes` is being used.

Fix TRN request matching for email and NINO matches

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/CheckAnswers.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/Matches.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/ResolveApiTrnRequestPageModel.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/NpqTrnRequests/Details.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/NpqTrnRequests/Resolve/Matches.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/NpqTrnRequests/Resolve/Matches.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/NpqTrnRequests/Resolve/ResolveNpqTrnRequestPageModel.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/PotentialDuplicate.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TagHelpers/HighlightTagHelper.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/JourneyTests/SupportTasks/NpqTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/Resolve/MatchesTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/NpqTrnRequests/DetailsTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/NpqTrnRequests/NoMatches/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/NpqTrnRequests/NpqTrnRequestTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/NpqTrnRequests/Resolve/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/NpqTrnRequests/Resolve/MatchesTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateApiTrnRequestSupportTask.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateNpqTrnRequestSupportTask.cs

Changes to highlight tag helper to fix double html-encoding.
Fix comparison of Person::MiddleName to support task request when it's empty
Add the file evidence to matches page

Highlight tag helper fixes and other match comparison fixes

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/CreateDateOfBirthChangeRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/CreateNameChangeRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskData/ChangeRequestEmailConstants.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ChangeRequests/EditChangeRequest/Accept.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ChangeRequests/EditChangeRequest/Reject.cshtml.cs

The email templates for change name and date of birth requests are in the Teaching Regulation Agency GOV Notify service whereas the email templates for qualification emails in TRS are in the Teaching Regulation service.
Now we’ve ported the change name and date of birth requests to support tasks in TRS we need to be able to send the emails from the Teaching Regulation service in GOV Notify.

Amended to use email templates from correct notify service

---

TeachingRecordSystem/src/TeachingRecordSystem.WebCommon/Middleware/AppendSecurityResponseHeadersMiddleware.cs

PDFs were not rendering embedded in the change name / date of birth chang request page.
This fix amends the response headers to allow content from the same origina (i.e. from the same website)

Amended to allow embedded content to render if it's from the same origin

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/Index.cshtml.cs

Previously EF was pulling every matched record into memory and then doing the `group by`.

Fix person search facet perf

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/PersonMatching/PersonMatchingService.cs

This fixes an issue from prod where we had a different name split in the incoming request vs existing record.

Fix multi word name matching for TRN requests

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SetMissingHasEypsOnPersonsJob.cs

There are a number of `Person` records where the `HasEyps` flag is set to false even though the person holds an EYPS route.
This job fixes that.

Add job to set has_eyps for Person records holding an EYPS route

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/TrnAllocatedEvent.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/AllocateTrnsToPersonsWithEyps.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs

Before we delete all records without TRNs we need to ensure all persons with EYPS have a TRN.
Create a job that allocates TRNs to any Person that has EYPS and doesn’t already have a TRN.
The job should output a CSV to blob storage with the Person ID of all records that have been updated.
The job should have a ‘dry run’ mode which doesn’t actually update any records but does output the CSV report of records that would be updated.
Every record that has a TRN allocated should have a `TrnAllocatedEvent` added for the `Person`.

Added job to allocate TRNs to Person records with HasEyps which currently have null TRN

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/EwcWalesImport/InductionImporter.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/EwcWalesImport/QtsImporter.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Jobs/QTSImporterTests.cs

Currently when ITR failures are exported, each row has a trailing \r, this PR removes the trailing carriage return and also separates the validation errors by a semi colon, making it easier to see the reasons the ewc wales job failed.

Stop adding trailing newline to itr rowdata

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/NpqCheck.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/PersonalEmail.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/SchoolOrEducationalSetting.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/SchoolOrEducationalSetting.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/appsettings.EndToEndTests.json
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/PageExtensions.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/RequestTrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/NpqCheckTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/SchoolOrEducationalSettingTests.cs

Reference numbers submitted are often incorrect, so remove the reference number page and instead always collect the NPQ name and Provider.
https://trello.com/c/HbXPPmk2/1581-update-get-a-trn-user-journey
I haven't removed the page from the codebase in case someone decides they want it back.
Also some backlink bug fixes, and reset work email to null if 'working in educational setting' has been changed from 'yes' to 'no'

remove the page that collects the Npq appplication reference

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Models/MandatoryQualification.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/LegacyDataCache.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/MandatoryQualificationSpecialism.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/ReferenceDataCache.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Specialism/Index.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/JourneyTests/Qualifications/MqTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/AddMq/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/DeleteMq/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Provider/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Specialism/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Specialism/IndexTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/StartDate/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Status/CheckAnswersTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/ChangeLogMandatoryQualificationEventsTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs
TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.DeleteMandatoryQualification.cs

We're still using DQT for MQ reference data in a few places. This adds that reference data to `LegacyDataCache` and amends lookups to use DQT's `dfeta_value` attribute instead of the environment-specific `id`. A job has already been run to populate the relevant fields in the DB.

Add DQT MQ reference data to LegacyDataCache

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250910100811_SupportTaskTypeId.Designer.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250910100811_SupportTaskTypeId.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/SupportTask.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskType.cs

We need to get our reference data into the DB so it can be reported on, specifically the enum-based reference data like `SupportTaskType`.
This adds `SupportTaskTypeId` to `SupportTask` so we'll have both the new and old values being written (`SupportTask.SupportTaskType` will be replaced by `SupportTask.SupportTaskTypeId` eventually). A follow-up PR will back-fill `SupportTaskTypeId` and remove usage of `SupportTaskType`.

Add SupportTaskTypeId to SupportTask

---

TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/OperationTestBase.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/Setup.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/V3/CreateDateOfBirthChangeTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/V3/CreateNameChangeTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/V3/CreateTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/V3/GetQtlsTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/V3/GetTrnRequestTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/V3/GetTrnTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/V3/SetQtlsTests.cs

We can't wrap execution (e.g. to create a transaction) if we're targeting the handlers directly.
Best reviewed with 'Hide whitespace' enabled.

Use command dispatcher in API unit tests

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Program.cs

For some reason the Hangfire dashboard doesn't work with our `TransactionScope` stuff. This disables that middleware for Hangfire's endpoints.

Fix Hangfire dashboard

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/AllocateTrnToPersonJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs

We need to assign a TRN to this record to enable support to proceed with their work.
The simplest way to do this is a one-off job.

Added job to allocate a TRN to a specific person

---

TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Index.cshtml
TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/PersonalEmail.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/PersonalEmailTests.cs

When a request for a TRN comes in via NPQ, there's an attempt to stop duplicate requests by checking for open requests with the same email. That check doesn't ignore case so User@example.com would be seen as different to user@example.com. Do a case-insensitive check instead.
https://trello.com/c/7uWCUmOn/1642-update-email-checks-to-remove-case-sensitivity

make check for email case-insensitive

---

TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/ImportTpsCsvExtractFileJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/RefreshEstablishmentsJob.cs

when there is a chain of jobs starting with an `Enqueue..` and following with `ContinueWith..` they all need to be wrapped in a single transaction

Wrapped entire chain of jobs being queued in a transaction

---

TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/TeacherPensions/Resolve/Matches.cshtml
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/TeacherPensions/Resolve/MatchesTests.cs

Show middlename from the capita imported file on the duplicate matches screen.

show middlename on teacher pensions imported record match screen

---

TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/CreateDateOfBirthChangeRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/CreateNameChangeRequest.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/EmailTemplateIds.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/BatchSendProfessionalStatusEmailsJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SendInductionCompletedEmailJob.cs
TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTasks/ChangeRequestEmailConstants.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ChangeRequests/EditChangeRequest/Accept.cshtml.cs
TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ChangeRequests/EditChangeRequest/Reject.cshtml.cs
TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Jobs/BatchSendProfessionalStatusEmailsJobTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/ChangeRequests/EditChangeRequest/AcceptTests.cs
TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/ChangeRequests/EditChangeRequest/RejectTests.cs

We currently have email template IDs scattered about in multiple places e.g. `ChangeRequestEmailConstants` and `BatchSendProfessionalStatusEmailsJob.TemplateIds`. We should move all of these into a common `EmailTemplateIds` class.

Consolidate email template IDs
