- .editorconfig
- .github/workflows/actions/deploy-environment/action.yml
- .github/workflows/build.yml
- Dockerfile
- azure/Set-ResourceGroup.ps1
- azure/azuredeploy.dev.parameters.json
- azure/azuredeploy.json
- docs/environment-setup.md
- src/DqtApi/Startup.cs
- terraform/.gitignore
- terraform/.terraform.lock.hcl
- terraform/api-app.tf
- terraform/data.tf
- terraform/dev.backend.tfvars
- terraform/dev.tfvars
- terraform/dev.tfvars.json
- terraform/outputs.tf
- terraform/provider.tf
- terraform/terraform.tf
- terraform/variables.tf
Adds initial Terraform resource definitions and amends the CI pipeline to deploy to the dev environment when PRs are ready for review.
Also adds docs around environment setup, secrets etc.
https://trello.com/c/PVd5L7Ne/65-terraform-the-api-application
> Deploy to dev environment with Terraform

- src/DqtApi/DqtApi.csproj
- src/DqtApi/Program.cs
- src/DqtApi/Security/ApiKeyAuthenticationHandler.cs
- src/DqtApi/appsettings.Development.json
- src/DqtApi/appsettings.Production.json
- src/DqtApi/appsettings.json
- terraform/api-app.tf
Sets up Logit.io on PAAS and amends app logging to output JSON.
Additionally adds a middleware to log all requests to ASP.NET Core, append a `CorrelationId` property and, for authenticated clients, a `ClientId` property.
https://trello.com/c/ZeszPWN9/36-logging
> Push logs to Logit.io

- .github/workflows/build.yml
- azure/azuredeploy.test.parameters.json
- docs/environment-setup.md
- terraform/test.backend.tfvars
- terraform/test.tfvars.json
Deploy to test environment from main branch.
Also updates the docs to add a missing step around service principal roles.
https://trello.com/c/PVd5L7Ne/65-deploy-api-application-to-paas-test
> Deploy to test environment from main branch

- src/DqtApi/Controllers/TeachersController.cs
- src/DqtApi/Filters/ProducesJsonOrProblemAttribute.cs
- src/DqtApi/Program.cs
- src/DqtApi/Swagger/ResponseContentTypeOperationFilter.cs
Enriches the swagger metadata for the Get Teacher endpoint.
Endpoint and parameter descriptions are largely lifted from the EAPIM implementation.
https://trello.com/c/Lh8Sg0RN/113-build-the-get-teacher-operation-endpoint
> Enrich the swagger endpoint for the Get Teacher operation

- .github/workflows/build.yml
Action setup is failing sporadically with HTTP 503 errors.
> Temporarily allow tflint to fail

- src/DqtApi/DqtApi.csproj
- src/DqtApi/Program.cs
Export ASP.NET Core metrics to Prometheus via `/metrics` endpoint
https://trello.com/c/mlmPAocF/111-set-up-prometheus-for-tra-services
> Add ASP.NET Core Prometheus metrics and expose at /metrics endpoint

- .github/pull_request_template.md
Bring our template inline with other services in TS
> Improve Github PR template

- src/DqtApi/DAL/DataverseAdaptor.cs
- src/DqtApi/DAL/IDataverseAdaptor.cs
- src/DqtApi/Models/GeneratedCode.cs
- src/DqtApi/Models/GeneratedOptionSets.cs
- src/DqtApi/V2/Controllers/IttProvidersController.cs
- src/DqtApi/V2/Handlers/GetIttProvidersHandler.cs
- src/DqtApi/V2/Requests/GetIttProvidersRequest.cs
- src/DqtApi/V2/Responses/GetIttProvidersResponse.cs
- src/DqtApi/V2/Responses/IttProviderInfo.cs
- tests/DqtApi.Tests/DataverseIntegration/GetIttProvidersTests.cs
- tests/DqtApi.Tests/V2/Operations/GetIttProvidersTests.cs
- tools/coretools/CrmSvcUtil.exe.config
Adds an endpoint to retrieve a list of ITT providers, sorted by name.
https://trello.com/c/FqYEp3Hr/160-find-my-trn-api-get-itt-providers-endpoint
> Add endpoint for retrieving all ITT providers

- terraform/dev.tfvars.json
- terraform/preprod.tfvars.json
- terraform/prod.tfvars.json
- terraform/provider.tf
- terraform/statuscake.tf
- terraform/terraform.tf
- terraform/test.tfvars.json
- terraform/variables.tf
Status Cake resources is defined along with provider and variables.
Status cake terraform code plus status cake alert context for dev, test, preprod and prod environments
> Added Status Cake terraform code

- Set-AppConfigSecret.ps1
Bad rebase/merge or something meant an old version of the script was commited in this PR https://github.com/DFE-Digital/qualified-teachers-api/pull/87 This fixes it to use the latest version that actually works.
> Fix Set-AppConfigSecret script

- azure/azuredeploy.json
Storage blob containers are created from a list of container names.
This is an improvement to replication of code used to create multiple
containers previously.
> Update storage container creation

- docs/api-specs/v2.json
- src/DqtApi/DataStore/Crm/DataverseAdapter.cs
- src/DqtApi/DataStore/Crm/IDataverseAdapter.cs
- src/DqtApi/DataStore/Crm/Models/FindTeachersQuery.cs
- src/DqtApi/ModelBinding/DateOnlyTypeConverter.cs
- src/DqtApi/Program.cs
- src/DqtApi/Properties/StringResources.Designer.cs
- src/DqtApi/Properties/StringResources.resx
- src/DqtApi/V2/Controllers/TeachersController.cs
- src/DqtApi/V2/Handlers/GetTrnDetailsHandler.cs
- src/DqtApi/V2/Requests/FindTeachersRequest.cs
- src/DqtApi/V2/Responses/FindTeacherResult.cs
- src/DqtApi/V2/Responses/FindTeachersResponse.cs
- src/DqtApi/V2/Validators/GetTrnDetailsRequestValidator.cs
- src/DqtApi/Validation/ErrorRegistry.cs
- tests/DqtApi.Tests/V2/Operations/GetTrnDetailsTests.cs
first pass on creating a new endpoint to trn detais - **return trn-details-match** (https://trello.com/c/zWPYqVDJ/106-create-trn-details-match-endpoint) from the following spec (https://github.com/DFE-Digital/teacher-id/blob/main/openapi/find-my-trn-api.yml)
Change include a new handler,controller,request & response & some tests to mock the crm response.
> add trn-details-match endpoint

- src/DqtApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
- src/DqtApi/EnumerableExtensions.cs
- tests/DqtApi.Tests/DataverseIntegration/CreateTeacherTests.cs
- tests/DqtApi.Tests/ExecuteTransactionRequestExtensions.cs
https://trello.com/c/YWxt7mJg/129-design-and-build-trn-qts-and-update-endpoint-validation-tests
Adding a missed validation from the first pass - create a review task if a teacher's name contains digits.
> Create a review task if a name contains digits

- tests/DqtApi.Tests/DataverseIntegration/UpdateTeacherTests.cs
Change has some additional qts/eyts tests that were not part of the original work.
Additional tests around changing itt programme type & countryid.
- Change to existing test to show qualification country can be changed.
- added test around showing that eyts cannot change to qts
- added test around showing that qts cannot change to eyts
> trn update - additional tests.

- docs/api-specs/v2.json
- src/DqtApi/DataStore/Crm/DataverseAdapter.cs
- src/DqtApi/DataStore/Crm/IDataverseAdapter.cs
- src/DqtApi/DataStore/Crm/UpdateTeacherCommand.cs
- src/DqtApi/V2/Handlers/SetIttOutcomeHandler.cs
- src/DqtApi/V2/Handlers/UpdateTeacherHandler.cs
- src/DqtApi/V2/Requests/SetIttOutcomeRequest.cs
- src/DqtApi/V2/Requests/UpdateTeacherRequest.cs
- tests/DqtApi.Tests/V2/Operations/SetIttOutcomeTests.cs
- tests/DqtApi.Tests/V2/Operations/UpdateTeacherTests.cs
Make dob mandatory in setting an itt outcome & updating a trn.
Changes include updating requests & updating tests to include birthdate.
> Added dob to setittoutcome request & update trn request

- tests/DqtApi.Tests/DataverseIntegration/CreateTeacherTests.cs
Verify that programme start date and programmeenddate is saved correctly.
Added extra test to verify that dates are saved correctly, and match what was sent in the request.
> Added test to verify programmestartdate and programmeenddate is correctly saved

- src/DqtApi/DataStore/Crm/DataverseAdapter.cs
- tests/DqtApi.Tests/DataverseIntegration/GetTeachersByTrnAndDobTests.cs
Added supporting tests for GetTeachersByTrnAndDoB.
Birthdate had previously been added to the matching criteria of finding a teacher, which was only covered by a mocked test. This adds an integration test for GetTeachersByTrnAndDoB.
> Fixed GetTeachersByTrnAndDoB & added supporting tests

- docs/api-specs/v2.json
- src/DqtApi/DataStore/Crm/CreateTeacherCommand.cs
- src/DqtApi/DataStore/Crm/CreateTeacherResult.cs
- src/DqtApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
- src/DqtApi/DataStore/Crm/DataverseAdapter.UpdateTeacher.cs
- src/DqtApi/DataStore/Crm/UpdateTeacherCommand.cs
- src/DqtApi/DataStore/Crm/UpdateTeacherResult.cs
- src/DqtApi/V2/Handlers/GetOrCreateTrnRequestHandler.cs
- src/DqtApi/V2/Handlers/UpdateTeacherHandler.cs
- src/DqtApi/V2/Requests/GetOrCreateTrnRequest.cs
- src/DqtApi/V2/Requests/UpdateTeacherRequest.cs
- tests/DqtApi.Tests/DataverseIntegration/CreateTeacherTests.cs
- tests/DqtApi.Tests/DataverseIntegration/UpdateTeacherTests.cs
- tests/DqtApi.Tests/V2/Operations/UpdateTeacherTests.cs
Added subject3 field to both create and update teacher. [Include relevant motivation and context.](https://trello.com/c/zY193rsj/243-dqt-api-updates-based-on-register-comments#)
Subject3 has been added to requests for create or update, and tests updated.
> Added subject3 to create teacher & update teacher

- tests/DqtApi.Tests/DataverseIntegration/GetTeacherTests.cs
Adds a test for deb5ec4771628c9663455f4eccac1627031a57fb that was missed.
> Add test to ensure columns are pulled through for merged records

- src/DqtApi/DataStore/Crm/DataverseAdapter.UpdateTeacher.cs
- src/DqtApi/V2/Validators/UpdateTeacherValidator.cs
- tests/DqtApi.Tests/DataverseIntegration/UpdateTeacherTests.cs
Remove validation on ukprn for qualification.
Remove validation on ukprn for qualification.
> Removed ukprn validation on qualification

- src/DqtApi/Services/LogRemainingCrmLimitsService.cs
If an exception is thrown in a `BackgroundService` then the app is stopped. We don't want that here - log the error instead.
> Don't stop the app if querying CRM API limits fails

- src/DqtApi/DataStore/Crm/DataverseAdapter.SetIttResultForTeacher.cs
- tests/DqtApi.Tests/DataverseIntegration/SetIttOutcomeForTeacherTests.cs
Manual testing yielded a gap - we were not creating a Task when a teacher with active sanctions was found on the Set ITT outcome endpoint.
Add a task when a teacher with active sanctions is referenced.
> Create a review task when a teacher with active sanctions has ITT outcome set

- src/DqtApi/DataStore/Crm/DataverseAdapter.cs
Also improve the 'empty' field check to account for empty strings.
> Only match on Active teachers

- src/DqtApi/DataStore/Crm/DataverseAdapter.SetIttResultForTeacher.cs
Change to include returning trn with getting teacher.
> return trn with getteacher

- Makefile
- docs/restore-paas-postgres-database.md
- terraform/api-app.tf
- terraform/dev.backend.tfvars
- terraform/pre-production.backend.tfvars
- terraform/production.backend.tfvars
- terraform/provider.tf
- terraform/test.backend.tfvars
- terraform/variables.tf
Postgres database can be restored from point in time backups available in Gov PaaS. This PR adds the Makefile rules and terraform configuration to enable developers to run the restore process during a disaster recovery.
https://trello.com/c/yVw2bqAe
> Add database restore capability

- .github/workflows/database-backup.yml
- Makefile
- azure/azuredeploy.dev.parameters.json
- azure/azuredeploy.json
- azure/azuredeploy.pre-production.parameters.json
- azure/azuredeploy.production.parameters.json
- azure/azuredeploy.test.parameters.json
- docs/restore-paas-postgres-database.md
- terraform/variables.tf
Postgres database backup needs to be stored outside of PaaS. This PR adds ARM template resources to deploy the backup storage on Azure and workflow which runs the backup of the database.
https://trello.com/c/vU6zXRZu
> Add backup storage account

- .github/workflows/database-backup.yml
Slack notify task was indented incorrectly. This commit applies the fix.
> Fix indentation

- docs/api-specs/v2.json
- src/DqtApi/DataStore/Crm/DataverseAdapter.cs
- src/DqtApi/V2/Handlers/FindTeachersHandler.cs
- src/DqtApi/V2/Responses/FindTeacherResult.cs
- tests/DqtApi.Tests/V2/Operations/FindTeachersTests.cs
Include HasActiveSanctions field on the find teachers endpoint.
[Include a summary of the change.](https://trello.com/c/pbIitjyu)
> added hasactivesanscations field on find endpoint

- .github/workflows/database-backup.yml
- .gitignore
- Makefile
- bin/download-db-backup
- bin/restore-db
Automate the process of restoring database backup to postgres
Makefile rule added to start restore process. Downloads backup from azure storage and restores it into postgres.
> Make download restore backup

- src/DqtApi/DataStore/Crm/DataverseAdapter.cs
Method was delegating to `GetIttProviderOrganizationByUkprn` incorrectly.
> Fix ITT provider lookup by name

- src/DqtApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
- src/DqtApi/DataStore/Crm/DataverseAdapter.SetIttResultForTeacher.cs
- src/DqtApi/DataStore/Crm/DataverseAdapter.UpdateTeacher.cs
- src/DqtApi/DataStore/Crm/GuidExtensions.cs
This allows us to use ?. on Nullable<Guid> values instead of a more
verbose HasValue check with the ternary operator.
> Add extension method for creating an EntityReference from a GUID

- src/DqtApi/V2/Handlers/SetIttOutcomeHandler.cs
- src/DqtApi/V2/Handlers/UpdateTeacherHandler.cs
We're seeing some errors in Sentry (as well an unlikely data race)
caused by concurrent requests for the same TRN.
This modifies the Update/Outcome endpoints to acquire an advisory lock
in Postgres keyed to the TRN to prevent concurrent modifications for a
given teacher record.
https://sentry.io/organizations/dfe-teacher-services/issues/3251086289/?project=6165440&query=is%3Aunresolved
Acquire a TRN-level advisory lock in Postgres to prevent concurrent modifications for a given teacher record.
> Acquire a TRN-level lock for Update/Outcome operations

- docs/api-specs/v2.json
- src/DqtApi/DataStore/Crm/CreateTeacherCommand.cs
- src/DqtApi/DataStore/Crm/CreateTeacherResult.cs
- src/DqtApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
- src/DqtApi/DataStore/Crm/DataverseAdapter.UpdateTeacher.cs
- src/DqtApi/DataStore/Crm/UpdateTeacherCommand.cs
- src/DqtApi/DataStore/Crm/UpdateTeacherResult.cs
- src/DqtApi/V2/Handlers/GetOrCreateTrnRequestHandler.cs
- src/DqtApi/V2/Handlers/UpdateTeacherHandler.cs
- src/DqtApi/V2/Requests/GetOrCreateTrnRequest.cs
- src/DqtApi/V2/Requests/UpdateTeacherRequest.cs
- tests/DqtApi.Tests/DataverseIntegration/CreateTeacherTests.cs
- tests/DqtApi.Tests/DataverseIntegration/UpdateTeacherTests.cs
- tests/DqtApi.Tests/TestDataHelper.CreatePerson.cs
- tests/DqtApi.Tests/V2/Operations/GetOrCreateTrnRequestTests.cs
- tests/DqtApi.Tests/V2/Operations/UpdateTeacherTests.cs
https://trello.com/c/dwTwWp4B/574-take-additional-previous-qualification-subjects-from-register
Add qualification subject2 & subject 3
> Add qualification subject2 & subject3

- .github/workflows/build.yml
Until we figure out the Dynamics issues...
> Allow tests to fail for now

- src/DqtApi/DataStore/Crm/DataverseAdapter.CreateTeacher.cs
- src/DqtApi/DataStore/Crm/DataverseAdapter.UpdateTeacher.cs
- src/DqtApi/DataStore/Crm/DataverseAdapter.cs
- src/DqtApi/DataStore/Crm/IDataverseAdapter.cs
- tests/DqtApi.Tests/DataverseIntegration/GetTeacherByHusIdTests.cs
tests are failing because getteacherbyhusid can return more than one record. This change includes trying changing the method so that it can return an array.
> Change GetTeacherByHusid to return an array

- .github/workflows/build.yml
- tests/DqtApi.Tests/DataverseIntegration/GetTeacherByHusIdTests.cs
- tests/DqtApi.Tests/DataverseIntegration/UpdateTeacherTests.cs
- tests/DqtApi.Tests/V2/Operations/UpdateTeacherTests.cs
Changes for updateteacher tests to pass a random husid to stop collisions in crm.
> Make husid random for tests

- docs/api-specs/v2.json
- src/DqtApi/V2/Handlers/GetTeacherHandler.cs
- src/DqtApi/V2/Requests/GetTeacherRequest.cs
- src/DqtApi/V2/Validators/GetTeacherRequestValidator.cs
- tests/DqtApi.Tests/V2/Operations/GetTeacherTests.cs
remove dob field from request.
https://trello.com/c/9CTFoEaH/724-amend-the-v2-get-teacher-endpoint-to-allow-omitting-dob
Inlude any dependencies that are required for this change.x
> Remove birthDate parameter from v2 Get teacher endpoint request

- src/DqtApi/Program.cs
We're seeing timeouts fire for TRN request operations which is causing our advisory locks to be dropped, even though the operation is still running on the CRM side. This combination of surfacing 500 errors and clients retrying with the early dropping of the locks means our duplicate detection is not working, since we effectively have two transactions in progress for the same trainee concurrently.
This extends our timeout to 5 minutes which should be enough time for the operation to succeed in CRM.
We will investigate separately why it's taking so long.
This also modifies app to create a new `ServiceClient` for every request, which might some samples suggests helps overall throughput.
> Create a new ServiceClient for each request

- .github/workflows/build.yml
Remove this job until we can fix it up to work reliably.
> Temporarily disable OWASP scan

- .github/workflows/actions/deploy-environment/action.yml
- .github/workflows/build.yml
- .gitignore
- Makefile
- terraform/dev.backend.tfvars
- terraform/dev.tfvars.json
- terraform/pre-production.backend.tfvars
- terraform/pre-production.tfvars.json
- terraform/production.backend.tfvars
- terraform/production.tfvars.json
- terraform/test.backend.tfvars
- terraform/test.tfvars.json
Migrating Azure resources to standardized approach.
Changes to Azure resource names in make and terraform files.
Testing manually
> Migrate to azure standards

- terraform/test.tfvars.json
Add new var to tfvars for test env
> Update test tfvars for new app storage account

- .github/pull_request_template.md
- QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/IDataverseAdapter.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/V2/Handlers/GetTeacherHandler.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/V3/ApiModels/IttOutcome.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/V3/ApiModels/IttProgrammeType.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Handlers/GetTeacherHandler.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Responses/GetTeacherResponse.cs
- QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/GetInitialTeacherTrainingByTeacherTests.cs
- QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V2/Operations/GetTeacherTests.cs
- QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/GetTeacherTests.cs
- docs/api-specs/v3.json
Need to add initial teacher training info to v3 API for new qualifications service
Add changes to API endpoint + DataverseAdapter + tests 
None specifically
> Add itt to v3 qualifications endpoint

- QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.SetNpqQualification.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.UpdateTeacher.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/IDataverseAdapter.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/Models/QualificationTypeExtensions.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/V1/Handlers/GetTeacherHandler.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/V3/ApiModels/NpqQualificationType.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Handlers/GetTeacherHandler.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Responses/GetTeacherResponse.cs
- QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/CreateTeacherTests.cs
- QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/DataverseIntegration/GetQualificationsForTeacherTests.cs
- QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V2/Operations/SetNpqQualificationTests.cs
- QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/GetTeacherTests.cs
- docs/api-specs/v3.json
- docs/config.rb
- docs/openapi-merge.json
NPQ qualification details needed in API for new qualifications UI
npqQualifications section added to v3 API.
v3 API code change + dataverse adapter + tests + docs
> Added npqQualifications section to v3 API + associated tests and docs

- QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Controllers/CertificatesController.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Handlers/GetEytsCertificateHandler.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Handlers/GetTeacherHandler.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Requests/GetEytsCertificateRequest.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Responses/GetTeacherResponse.cs
- QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/GetEytsCertificateTests.cs
- QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/GetTeacherTests.cs
- docs/api-specs/v3.json
Need to provide ability to generate a certificate for EYTS via the qualifications API
Add endpoint for EYTS
Essentially a copy and paste of how certificates are implemented for QTS
> Add EYTS Certificate endpoint

- QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.SetIttResultForTeacher.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.UpdateTeacher.cs
Lots of changes have been made to the selection criteria for setittoutcome & teacher update for register. With every PR being made, the linq statement is getting more complicated. This PR is to tidy up the selection criteria into readable blocks.
Tidying up the selection criteria for selecting itt/qts records.
-   [] Attach to Trello card
> Tidy up SelectIttRecord & SelectQTSRecord by expanding out linq query

- QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Responses/GetCertificateResponse.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Responses/GetTeacherResponse.cs
- docs/api-specs/v3.json
Also adds `required` to response object properties.
> Fix up incorrect nullable flags in v3 swagger spec

- QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.SetIttResultForTeacher.cs
Added await statement to the requestbuilder to stop deadlocks.
> Fix status cache by adding await requestBuilder

- QualifiedTeachersApi/src/QualifiedTeachersApi/Services/GetAnIdentityApi/GetAnIdentityApiClient.cs
Also fix the GetUserById method to throw if it sees an unexpected response status.
> Camel case JSON messages sent to DQT API

- QualifiedTeachersApi/src/QualifiedTeachersApi/Program.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/Services/GetAnIdentity/LinkTrnToIdentityUserService.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/Services/GetAnIdentity/ServiceCollectionExtensions.cs
- QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/ApiFixture.cs
- QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/Services/GetAnIdentity/LinkTrnToIdentityUserServiceTests.cs
Tweaked the DI on the service to resolve all its dependencies via the IServiceProvider, not just the DbContext.
I've also moved the service into the appropriate namespace and fixed up the test name format.
> Fix CI test errors caused by background service

- .github/workflows/actions/deploy-environment/action.yml
Reverts DFE-Digital/qualified-teachers-api#433
This is now fixed in the action we use.
> Revert "Workaround CF CLI download issue"

- QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Controllers/TeacherController.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Controllers/TeachersController.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Handlers/GetTeacherHandler.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/V3/Responses/GetTeacherResponse.cs
- QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/GetTeacherByTrnTests.cs
- QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/V3/GetTeacherTests.cs
- docs/api-specs/v3.json
Also moved the Get teacher by TRN action to the `TeachersController`.
> Add DateOfBirth and NINO to v3 teacher response

- QualifiedTeachersApi/src/QualifiedTeachersApi/Services/GetAnIdentity/WebHooks/GetAnIdentityEndpoints.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/Services/GetAnIdentity/WebHooks/NotificationEnvelope.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/Services/GetAnIdentity/WebHooks/User.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/Services/GetAnIdentity/WebHooks/UserUpdatedHandler.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/Services/GetAnIdentity/WebHooks/UserUpdatedMessage.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/Services/GetAnIdentity/WebHooks/UserUpdatedRequest.cs
- QualifiedTeachersApi/tests/QualifiedTeachersApi.Tests/Services/GetAnIdentity/WebHooks/UserUpdatedTests.cs
Also added nullability annotations for webhook handling code and tests.
> Handle webhook messages for users that don't have a TRN

- QualifiedTeachersApi/src/QualifiedTeachersApi/Services/DqtReporting/EntityTableMapping.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/Services/DqtReporting/Migrations/0004_ContactAdditionalAttributes.sql
Also fixes table generation for __Updated column.
> Add additional attributes to contact table

- QualifiedTeachersApi/src/QualifiedTeachersApi/Jobs/ServiceCollectionExtensions.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/Program.cs
Also removes a redundant parameter.
> Fix namespace from ported file

- QualifiedTeachersApi/src/QualifiedTeachersApi/Services/GetAnIdentity/ServiceCollectionExtensions.cs
- QualifiedTeachersApi/src/QualifiedTeachersApi/appsettings.Development.json
- QualifiedTeachersApi/src/QualifiedTeachersApi/appsettings.Production.json
Running this in development mode makes the logs extremely noisy.
> Don't run LinkTrnToIdentityUserService in dev mode by default

- QualifiedTeachersApi/src/QualifiedTeachersApi/Services/DqtReporting/DqtReportingService.cs
We handle CRM rate limit errors when the `DqtReportingService` is up and running but not when it's initializing. This adds a simple retry loop to `LoadEntityMetadata`.
> Handle rate limit errors on start up

- .github/workflows/deploy-preprod.yml
This step was added during development to validate data was output correctly.
> Remove debugging step from workflow

- QualifiedTeachersApi/src/QualifiedTeachersApi/DataStore/Crm/DataverseAdapter.SetIttResultForTeacher.cs
Selecting an itt record that is not associated with an establishment currently casues a NRE, this fixes this error.
> Handle ITT record that is not associated with an establishment

- TeachingRecordSystem/src/TeachingRecordSystem.Api/Services/DqtReporting/DqtReportingService.cs
We previously added a wrapping `Exception` so that we could see which entity types had failed in the logs. In doing so, we broke the type-specific `catch` blocks we had. This fixes them.
> Fix exception catching in DqtReportingService

- TeachingRecordSystem/src/TeachingRecordSystem.Api/DataStore/Crm/DataverseAdapter.UpdateTeacher.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/DataStore/Crm/DataverseAdapter.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/DataStore/Crm/IDataverseAdapter.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/DataStore/Crm/UpdateTeacherCommand.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Handlers/UpdateTeacherHandler.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Requests/UpdateTeacherRequest.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Validators/UpdateTeacherValidator.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/DataverseIntegration/TestDataHelper.CreatePerson.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/DataverseIntegration/UpdateTeacherTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V2/Operations/UpdateTeacherTests.cs
Register require an update to the api so that teachers can be updated using a slugid.
https://trello.com/c/2v0pKlF3/5533-add-slugid-to-dqt-update-teacher-endpoint
Add Slugid to update endpoint.
Updated tests to test that slugid is used.
> Initial changes required for updating a teacher by both trn/dob & slugid

- TeachingRecordSystem/src/TeachingRecordSystem.Api/TeachingRecordSystem.Api.csproj
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/Endpoints/SwaggerTests.cs
Also added tests that Swagger endpoints don't error.
> Fix v3 swagger endpoint

- TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Handlers/SetIttOutcomeHandler.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Requests/SetIttOutcomeRequest.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Dqt/DataverseAdapter.SetIttResultForTeacher.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Dqt/IDataverseAdapter.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V2/Operations/SetIttOutcomeTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Dqt.Tests/DataverseAdapterTests/SetIttOutcomeForTeacherTests.cs
Register require a method of updating an outcome using a slugid.
- Added slugid to update endpoint.
- Updated tests to include slugid.
> Initial commit of updating outcome using slugid

- TeachingRecordSystem/tests/TeachingRecordSystem.TestFramework/Discovery.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestFramework/Execution.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestFramework/TestClassAttribute.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestFramework/TestConcurrencyMode.cs
Tests in the same group won't be run in parallel with each other.
> Add test concurrency group support

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Dockerfile
Since the API has some additional packages installed for fonts it was easier to migrate the UI project.
> Use Alpine base image for UI so we can use konduit

- TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/ApiModels/IttProgrammeType.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/DataverseAdapter.UpdateTeacher.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Models/GeneratedOptionSets.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/DataverseAdapterTests/CreateTeacherTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/DataverseAdapterTests/UpdateTeacherTests.cs
https://trello.com/c/dE6Moads/1128-add-hpitt-programme-type 
add new programme type for high potential itt programme type.
updated crm models
> Add new High potential ITT programme type

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/UserEditedEvent.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/UserUpdatedEvent.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/EditUserTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/TestUsers.cs
We need to be able to amend a user's name and/or roles after they've been created.
- added a new edit page
- added test to match the code change
-   [#1170]
> added edit user page

- TeachingRecordSystem/src/TeachingRecordSystem.Core/UserRoles.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/TeachingRecordSystem.Api.Tests.csproj
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/TeachingRecordSystem.Core.Dqt.Tests.csproj
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/TeachingRecordSystem.Core.Tests.csproj
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/EditUserTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/TeachingRecordSystem.SupportUi.Tests.csproj
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/TestBase.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/TestUsers.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TeachingRecordSystem.TestCommon.csproj
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateUser.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.cs
Also added another role so we can reliably test role changes in tests.
> Added initial version of TestData type with CreateUser method

- .github/workflows/pr.yml
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/GetAllSubjectsQuery.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/GetAllTeacherStatusesQuery.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/GetContactByTrn.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/GetContactByTrnQuery.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/GetAllSubjectsHandler.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/GetAllTeacherStatusesHandler.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/GetContactByTrnHandler.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/ReferenceDataCache.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/ServiceCollectionExtensions.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/CrmClientFixture.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/QueryTests/GetAllSubjectsTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/QueryTests/GetAllTeacherStatusesTests.cs
Includes subjects and teacher statuses only for now.
> Add initial version of CRM ReferenceDataCache

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_Layout.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/Index.cshtml
* Change the 'Add user' link to a button and move it under the users list.
* Change the 'Save and continue' button to 'Save'.
* Pre-populate the user's current roles on Edit User page.
* Add a Back link from Edit User page to Users.
> A few tweaks to Users list and Edit User page

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/UserActivatedEvent.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser.cshtml.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/EditUserTests.cs
We need to be able to reactivate a user that has been deactivated.
- added changes to activate a user
- added relevant test
-   [#1181]
> added functionality to activate a user

- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/ServiceCollectionExtensions.cs
We've had a few sporadic test failures caused by exceptions in the guts of FakeXrmEasy around collection modification during enumeration; I suspect the context we're sharing amongst current tests isn't thread safe. This adds a middleware to the pipeline that grabs a shared lock before processing the message. This seems to have solved the problem.
> Only allow a single request through FakeXrmEasy at a time

- .gitignore
- Makefile
- terraform/domains/environment_domains/.terraform.lock.hcl
- terraform/domains/environment_domains/config/dev.tfvars.json
- terraform/domains/environment_domains/config/dev_Terrafile
- terraform/domains/environment_domains/config/dev_backend.tfvars
- terraform/domains/environment_domains/config/pre-production.tfvars.json
- terraform/domains/environment_domains/config/pre-production_Terrafile
- terraform/domains/environment_domains/config/pre-production_backend.tfvars
- terraform/domains/environment_domains/config/production.tfvars.json
- terraform/domains/environment_domains/config/production_Terrafile
- terraform/domains/environment_domains/config/production_backend.tfvars
- terraform/domains/environment_domains/config/test.tfvars.json
- terraform/domains/environment_domains/config/test_Terrafile
- terraform/domains/environment_domains/config/test_backend.tfvars
- terraform/domains/environment_domains/main.tf
- terraform/domains/environment_domains/terraform.tf
- terraform/domains/environment_domains/variables.tf
- terraform/domains/infrastructure/.terraform.lock.hcl
- terraform/domains/infrastructure/config/trs.tfvars.json
- terraform/domains/infrastructure/config/trs_Terrafile
- terraform/domains/infrastructure/main.tf
- terraform/domains/infrastructure/terraform.tf
- terraform/domains/infrastructure/variables.tf
- terraform/paas/.terraform.lock.hcl
Add DNS and Azure Frontdoor resources
Confirm all settings are correct for 'teaching-record-system'
-   [ ] Attach to Trello card  https://trello.com/c/ow5mJquA/376-database-of-qt-api-create-dns-zone-in-azure-dns-via-terraform-and-migrate
> initial dna/afd settings

- Makefile
Fix to CI
Added deploy confirm to Makefile
> Add confirm deploy ci

- terraform/domains/environment_domains/config/test.tfvars.json
- terraform/domains/environment_domains/variables.tf
Migration of test environment to AKS
Update the origin to the AKS endpoint
Check the origin is correct
> [634] Migrate test domain from paas to AKS

- terraform/domains/environment_domains/.terraform.lock.hcl
- terraform/domains/environment_domains/config/production.tfvars.json
Migration of the production environment
Update the prodcution domain origin to AKS
Same change as pre-production
> [637] Point production domain at AKS

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Security/AssignUserInfoOnSignIn.cs
It's possible that a user's name and/or email could change in AD; we want those changes to be automatically reflected in our users table. Call the Graph API on sign in and ensure our email and name match what it returns.
> Sync name and email from AAD on sign in

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Services/DqtReporting/DqtReportingService.cs
The annotation body is the base 64-encoded file contents. It's a very large field (which is the cause of our out-of-memory issues) but it's never actually used by reports.
> Exclude annotation bodies from reporting DB sync

- TeachingRecordSystem/src/TeachingRecordSystem.Api/Program.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/ServiceCollectionExtensions.cs
Also ensure old job is removed from Hangfire's DB.
> Run Hangfire for local dev

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/DataverseAdapter.SetIttResultForTeacher.cs
fix for bug reported in sentry.
> fix when programme type is null

- .github/workflows/backup-db.yml
Adds a scheduled workflow to backup the production postgres DB to Azure Blob Storage.
> Add workflow to backup production DB

- .tool-versions
- terraform/aks/monitoring.tf
- terraform/aks/terraform.tf
- terraform/aks/variables.tf
- terraform/aks/workspace_variables/production.tfvars.json
Catch more SSL errors impacting our clients
- Monitor the front door domain
- Remove confirmations to make the checks more sensitive
Run terraform-plan
> [775] Add more StatusCake monitoring

- TeachingRecordSystem/src/TeachingRecordSystem.Api/EnumHelper.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V1/Handlers/GetTeacherHandler.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/ApiModels/ClassDivision.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/ApiModels/Gender.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/ApiModels/IttProgrammeType.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/ApiModels/IttQualificationAim.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Handlers/GetOrCreateTrnRequestHandler.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Handlers/GetTeacherHandler.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/ApiModels/InductionStatus.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/ApiModels/IttProgrammeType.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/GetTeacherHandler.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Responses/GetTeacherResponse.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/DataverseAdapter.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetTeacherTestBase.cs
- Don't return inactive ITT records.
- Fix query for ITT records that don't have a provider.
- Add a `StatusDescription` property to `Induction`.
> API tweaks for Check

- TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/ApiModels/ClassDivision.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Models/GeneratedOptionSets.cs
Add new 'Other' class/division.
https://trello.com/c/KzgTjOfi/1310-add-other-as-a-he-class-division-value-to-dqt-qualifications
> Added other class/division

- TeachingRecordSystem/Directory.Packages.props
- TeachingRecordSystem/TeachingRecordSystem.sln
- TeachingRecordSystem/lib/Directory.Packages.props
- TeachingRecordSystem/nuget.config
- TeachingRecordSystem/src/TeachingRecordSystem.Api/TeachingRecordSystem.Api.csproj
- TeachingRecordSystem/src/TeachingRecordSystem.Cli/TeachingRecordSystem.Cli.csproj
- TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TeachingRecordSystem.SupportUi.csproj
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/TeachingRecordSystem.Api.Tests.csproj
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.Tests/TeachingRecordSystem.Core.Dqt.Tests.csproj
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/TeachingRecordSystem.Core.Tests.csproj
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/TeachingRecordSystem.SupportUi.EndToEndTests.csproj
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/TeachingRecordSystem.SupportUi.Tests.csproj
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TeachingRecordSystem.TestCommon.csproj
Simplifies keeping dependency versions unified across projects.
https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management
> Use central package management

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Services/DqtReporting/Migrations/0015_dfeta_qualification_dfeta_mq_status.sql
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Services/DqtReporting/Migrations/0016_dfeta_qualification_dfeta_trsdeletedevent.sql
- TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
We've added some new MQ related fields to the dfeta_qualification table in CRM which also need to be in the reporting DB
SQL Server migrations scripts
Simple change
> Added reporting DB migration scripts for new MQ fields

- docs/adr/0001-move-id-into-trs.md
> added adr for identity to move to trs

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/CreateMandatoryQualificationHandler.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/AddMq/CheckAnswers.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/AddMq/Provider.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/AddMq/Specialism.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/AddMq/StartDate.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/AddMq/Status.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/AddMq/Status.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/DeleteMq/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Provider/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Status/Confirm.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Status/Confirm.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Status/EditMqResultState.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Status/Index.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Mqs/EditMq/Status/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Qualifications.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Qualifications.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Program.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/MqTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PageExtensions.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/AddMq/CheckAnswersTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/AddMq/StartDateTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/AddMq/StatusTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Status/ConfirmTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Mqs/EditMq/Status/IndexTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/QualificationsTests.cs
There are a few snags around the MQ UI.
Rename "Result" to "Status" everywhere
Use Required data annotation where possible
Remove explicit ID when creating qualification
UI + tests
> Fixed MQ related snags including tests

- TeachingRecordSystem/src/TeachingRecordSystem.Cli/Commands.MigrateDb.cs
PRs are deployed to the dev environment automatically. If that PR contains any migrations that are subsequently changed (or not merged) then the environment is stuck with the original changes applied, which possibly blocks newer changes from being applied successfully.
This change adds an option to the CLI command we use for deploying migrations to allow specifying a target migration. With this, we can SSH into a pod and run it to selectively roll back applied migrations. We could automate this but it happens sufficiently rarely that this is probably good enough for now.
> Add option to DB migration command for specifying target migration

- docs/c4-diagrams-as-code/trs-to-be-external-data-integrations-c4.dsl
- docs/trn-generation.md
added a to be trn .md file and a few changes to .dsl
> Additional docs and updates

- .github/workflows/pr.yml
Better to timeout than to hang indefinitely.
> Add timeouts to test steps on CI

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ApiKeys/EditApiKey.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ApplicationUsers/EditApplicationUser.cshtml
> Fix ID in EditApiKey JS

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
Audit records include some attributes that we don't care about; ignore those to ensure we don't get a 'non-contiguous audit records' error.
> Ignore un-mapped attributes when computing initial entity version

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/ChangeLog.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/MandatoryQualificationCreatedEvent.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/MandatoryQualificationDeletedEvent.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/MandatoryQualificationDqtDeactivatedEvent.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/MandatoryQualificationDqtImportedEvent.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/MandatoryQualificationDqtReactivatedEvent.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/MandatoryQualificationMigratedEvent.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/MandatoryQualificationUpdatedEvent.cshtml
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/ChangeLogTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/SeedCrmReferenceData.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs
We’ve added MQ Deleted and Deactivated events to the Change log but not Created or Updated.
Add the MQ Created and Updated events to the Change log. In addition, align the existing events to any changes in the Figma designs.
UI changes + tests
> Added UI for missing events in change log + tests

- TeachingRecordSystem/src/TeachingRecordSystem.Api/Infrastructure/ApplicationModel/ApiVersionConvention.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/Infrastructure/ApplicationModel/BackFillVersionedEndpointsConvention.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/Infrastructure/ApplicationModel/Constants.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/Infrastructure/OpenApi/ServiceCollectionExtensions.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/VersionRegistry.cs
Also fixes endpoint comparison to include the route template defined on the controller (as well as the action).
> Fix Swagger document generation for minor versions

- TeachingRecordSystem/src/TeachingRecordSystem.Api/Infrastructure/Security/AuthorizationPolicies.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/Program.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/Properties/StringResources.Designer.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/Properties/StringResources.resx
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/CreateTrnRequestHandler.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Requests/CreateTrnRequestBody.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Requests/GetTeacherRequest.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Requests/TrnRequestPerson.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Responses/TrnRequestInfo.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Responses/TrnRequestStatus.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240101/Controllers/TrnRequestsController.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Validators/CreateTrnRequestValidator.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/Validation/ErrorRegistry.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/ApiRoles.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Models/AttributeConstraints.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/CreateTeacherQuery.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/FindExistingTeacherQuery.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/CreateTeacherHandler.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/FindExistingTeacherHandler.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/HostFixture.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/TestScopedServices.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/CreateTrnRequestTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/CreateTeacherTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/FindExistingTeacherQueryTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/FakeTrnGenerationApiClient.cs
Added a v3 endpoint of trn-requests that uses the new query handlers.
https://trello.com/c/bauxANrV/1731-trn-api-post-endpoint
> Added v3 trn request endpoint

- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Handlers/GetTrnRequestHandler.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Requests/GetTrnRequest.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240101/Controllers/TrnRequestsController.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetTrnRequestTests.cs
v3 get trn request endpoint.
https://trello.com/c/0YQIiuVF/1732-trn-api-get-endpoint
> Added get trn-request v3 endpoint

- TeachingRecordSystem/src/TeachingRecordSystem.Api/Infrastructure/ApplicationModel/BackFillVersionedEndpointsConvention.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/Infrastructure/Features/RequestedVersionFeature.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/Infrastructure/Middleware/AssignRequestedVersionMiddleware.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/Program.cs
Also moves version logic into middleware.
> Add requested and effective minor versions to Sentry context

- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/GetTrnRequest.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240101/Controllers/TrnRequestsController.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/GetContactWithParentById.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/GetContactWithParentByIdHandler.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/GetTrnRequestTests.cs
https://trello.com/c/0YQIiuVF/1732-trn-api-get-endpoint
When a record is merged, the gettrnrequest v3 endpoint should return the trn of the parent record.
> Get TrnRequest returns master record trn when merged

- CHANGELOG.md
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/ApiModels/TrnRequestInfo.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/ApiModels/TrnRequestPerson.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/ApiModels/TrnRequestStatus.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Controllers/TrnRequestsController.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Requests/CreateTrnRequestRequest.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Validators/CreateTrnRequestRequestValidator.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/TestBase.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240101/CreateDateOfBirthChangeTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240101/CreateNameChangeTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240101/FindTeachersTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240101/GetEytsCertificateTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240101/GetInductionCertificateTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240101/GetNpqCertificateTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240101/GetQtsCertificateTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240101/GetTeacherByTrnTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240101/GetTeacherTestBase.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240101/GetTeacherTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240101/TestBase.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/VNext/CreateTrnRequestTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/VNext/GetTrnRequestTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/VNext/TestBase.cs
Also moves tests into a child namespace by version.
> Move TRN request endpoints into VNext

- TeachingRecordSystem/Directory.Packages.props
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/EstablishmentMapping.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240212172019_Establishments.Designer.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20240212172019_Establishments.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Establishment.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/TrsDbContext.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/RefreshEstablishmentsJob.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/Establishment.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Establishments/CsvDownloadEstablishmentMasterDataService.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Establishments/EstablishmentCsvRow.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Establishments/GiasOptions.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Establishments/IEstablishmentMasterDataService.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Establishments/ServiceCollectionExtensions.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
- TeachingRecordSystem/src/TeachingRecordSystem.Worker/Program.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Worker/appsettings.Development.json
- TeachingRecordSystem/src/TeachingRecordSystem.Worker/appsettings.json
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Jobs/RefreshEstablishmentsJobTests.cs
As part of the workforce data import process we need to map from the format establishment details are stored in TPS to known establishments in GIAS.
Create a job which runs daily to import the minimal fields we need from GIAS for the workforce data establishment mapping + data which may be needed to provide via the TRS API
Database change + background job + tests
> Added establishment (GIAS) refresh job

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Common/PersonSubNavigationTab.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/Layout.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/ChangeHistory.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/ChangeHistory.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Annotation.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/MandatoryQualificationCreatedEvent.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/MandatoryQualificationDeletedEvent.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/MandatoryQualificationDqtDeactivatedEvent.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/MandatoryQualificationDqtImportedEvent.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/MandatoryQualificationDqtReactivatedEvent.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/MandatoryQualificationMigratedEvent.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/MandatoryQualificationUpdatedEvent.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/IncidentResolution.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Task.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/TimelineItem.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/ChangeLogTests.cs
Also fix timestamp format and reduce bottom margin on details components in timeline entries.
> Rename Change log to Change history

- .github/workflows/pr.yml
- TeachingRecordSystem/TeachingRecordSystem.sln
- TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Index.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Program.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/HostFixture.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/Infrastructure/Security/FakeOneLoginHandler.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/OneLoginUserInfo.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/PageExtensions.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/SignInTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/Startup.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests.csproj
- TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/TestBase.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/xunit.runner.json
- TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/HostFixture.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateOneLoginUser.cs
Also adds tests for the core sign in scenarios.
> Add EndToEndTests project for Authorize access

- TeachingRecordSystem/src/TeachingRecordSystem.Api/Program.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/ServiceCollectionExtensions.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Program.cs
It's adversely affecting hot reload.
> Don't pre-warm ReferenceDataCache for local dev

- TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/Validators/UpdateTeacherValidator.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V2/Operations/UpdateTeacherTests.cs
A validation rule was incorrectly added to middlename.
> Fix middlename not being optional

- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/CreateTrnRequest.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/NationalInsuranceNumberHelper.cs
Normalize storing nino & extract existing nino logic into separate method.
> Extract existing nino normalization logic into separate method

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SyncAllMqsFromCrmJob.cs
Also clear out any existing `*Migrated` events so we can safely re-run the job multiple times.
> Create migrated events in SyncAllMqsFromCrmJob

- TeachingRecordSystem/src/TeachingRecordSystem.Cli/Commands.SyncPerson.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/MandatoryQualificationMigratedEvent.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/SyncAllMqsFromCrmJob.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.MandatoryQualification.cs
Also fix the MandatoryQualificationMigratedEvent to track changes to Specialism.
> Prefer non-legacy specialisms mapped from provider

- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/CreateTrnRequest.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/DataverseAdapter.CreateTeacher.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/CreateTeacherQuery.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/FindExistingTeacherQuery.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/CreateContactHandler.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/FindExistingTeacherHandler.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/DataverseAdapterTests/CreateTeacherTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/CreateTeacherTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/FindExistingTeacherQueryTests.cs
When more than one contact is found with with the same name/dob matching, a review task is created. This PR updates that logic so that a review task is created for every potential duplicate that is found.
> Update trn endpoints to support creating more than one review task

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/DataverseAdapter.CreateTeacher.cs
fix that was checking for null on an array that was empty, resulting in trns not being allocated.
> Fix checking for null on an empty array

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/Migrations/0018_ContactQTLSDate.sql
- TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
https://trello.com/c/uYoTtKGG/1772-add-a-qtlsdate-attribute-to-the-crm-contact-record
added qtls date to contact reporting table.
> Add dfeta_qtlsdate to contact

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/DataverseAdapter.CreateTeacher.cs
change logic for trn allocation fix that was merged previously.
https://github.com/DFE-Digital/teaching-record-system/pull/1231
> allocate trn when there is no existing teachers

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/ImportTpsCsvExtractFileJob.cs
Accidentally left some code commented out while do some investigation prior to merging the previous PR.
This adds it back in and allows the TPS extract files to be fully processed
> Uncommented out temporarily commented out code

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/WorkforceData/TpsCsvExtractProcessor.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/WorkforceData/TpsCsvExtractProcessorTests.cs
We need to import workforce data from Capita so we can expose employment history on the APIs.
Amended queries to only match on LA Code and Postcode for HEIs IF there is not already a match for the same record on LA Code and Establishment (fixes duplicates issue)
> Fixed queries for workforce data

- TeachingRecordSystem/src/TeachingRecordSystem.Api/Infrastructure/Security/AuthorizationPolicies.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/Program.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/ApiRoles.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/RoleNamesData.cs
Add new assignqtls role for new api
https://trello.com/c/JAnXRGTi/1775-add-an-assignqtls-api-role
> Add Assignqtls role

- TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Program.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Cli/Commands.GenerateKey.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Cli/Program.cs
Also adds a CLI command for generating keys in the format we need.
> Get encryption and signing keys for config

- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/DataverseAdapterTests/CreateTeacherTests.cs
> Fix broken test

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Filters/CheckPersonExistsFilter.cs
While setting up some test records in pre-prod I've got errors saving an MQ because the person hasn't yet synced to the TRS DB (so the FK from `qualifications` fails). This adds a simple DB lookup to the `CheckPersonExistsFilter` and schedules an ad-hoc sync if the person doesn't exist yet. This isn't perfect (since that job may not be picked up in time) but it's still an improvement.
> Ensure person has been synced to TRS DB

- TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/.gitignore
- TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/OidcTest/SignedIn.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/OidcTest/_Layout.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/Shared/_Layout.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/TeachingRecordSystem.AuthorizeAccess.csproj
- TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/libman.json
- TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/wwwroot/Styles/site.scss
This is largely copy/paste from the `SupportUi` project.
> Add SASS to AuthorizeAccess project

- TeachingRecordSystem/Dockerfile
- TeachingRecordSystem/db.sh
With this we can `kubectl exec` into a pod, run `db.sh` and we're into the DB.
> Add script to simplify connecting to DB from a pod

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/Migrations/0019_dfeta_qtlsdatehasbeenset.sql
- TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
Add qtlsdatehasbeenset to contact table for reporting.
> Added qtlsdatehasbeenset to contact table

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/Migrations/0020_incidentresolution_msdyn_proposeknowledge.sql
- TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
added msdyn_proposeknowledge column to incidentresolution in reporting solution.
> updated incidentresolution to include new msdyn_proposeknowledge column

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ConnectOneLoginUser/Index.cshtml
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/SupportTaskTests.cs
I missed this from the previous PR.
> Handle no suggestions for connecting One Login user

- TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Identity.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Index.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/NationalInsuranceNumber.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/PreviousName.cshtml.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/PreviousNameTests.cs
The Get a TRN journey has evolved since we first started building it. There may be changes we’ve missed.
Review the latest designs and ensure the journey we’ve built matches it.
Simple changes
> Fixed any remaining glitches and typos in Request a TRN journey

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/FindPotentialDuplicateContactsHandler.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/FindPotentialDuplicateContactsTests.cs
This amends the query used for finding potential duplicate contacts such that matching on email address alone is considered a match (previously at least two other attributes would need to be matched too).
> Match on email address alone in duplicates query

- docs/trs-integration.dsl
In prep for conversations with TCS on future data integrations
Update integration .dsl to reflect all integrations (as is and to be)
This is just a change to the .dsl file, I will update the jpeg files and .md in later PR's
> added all integrations to .dsl file

- docs/workforce-data-import/monthly-process.md
Tweaked the workforce data monthly import docs based on experience
> Updated workforce data docs

- Makefile
- terraform/aks/.terraform.lock.hcl
- terraform/aks/app.tf
- terraform/aks/databases.tf
- terraform/aks/dqt-reporting.tf
- terraform/aks/storage.tf
- terraform/aks/variables.tf
- terraform/aks/workspace_variables/dv_review.backend.tfvars
- terraform/aks/workspace_variables/dv_review.tfvars.json
Review app config added to deploy app on development cluster.
Following changes done :
1 ) Make file chnages.
2 ) Added vault secrets
3 ) tfvars for review.
Run the following command to deploy review app.
make dv_review terraform-apply  CLUSTER=cluster2 IMAGE=ghcr.io/dfe-digital/teaching-record-system:b96c149d3b2db5f4ce4ddb29928cfec6af0e286a.
Verify the cluster : 
➜  register-trainee-teachers git:(main) ✗ kubectl -n development get po | grep trs
trs-review-api-59f4984c4b-9qlwc              1/1     Running     0          5h19m
trs-review-authz-58bc558848-qwfz7            1/1     Running     0          5h19m
trs-review-migrations-hqd4g                  0/1     Completed   0          23h
trs-review-reporting-migrations-kcqbl        0/1     Completed   0          23h …
> Review app config added.

- docs/api-designs/webhooks.md
We're moving to CloudEvents & HTTP Message Signatures since Standard Webhooks doesn't have a stable asymmetric key story. This updates the docs accordingly. More detail around signatures, keys and message types will follow when we've got the implementation fleshed out.
> Update webhook spec for CloudEvents

- docs/workforce-data-import/useful-queries.md
Needed to create a number of queries as part of analysing the workforce data.
It makes sense to makes these available as starting points for anyone else wanting to query the data.
> Added useful workforce data queries to docs

- terraform/aks/monitoring.tf
Update contact group for statuscake so we can stay on top of incidents
Set statuscake contact group to TRA digital and Teacher-Services-infra
> Update statuscake contact group

- terraform/aks/app.tf
- terraform/aks/variables.tf
- terraform/aks/workspace_variables/dev.tfvars.json
- terraform/aks/workspace_variables/pre-production.tfvars.json
- terraform/aks/workspace_variables/production.tfvars.json
- terraform/aks/workspace_variables/test.tfvars.json
Scrape the web app and worker custom metrics
https://trello.com/c/Zlih3dRZ/1889-scrape-custom-metrics
Add enable_prometheus_monitoring to ui app and worker
remove from review tfvars before merge
make <env> terraform-plan
Check metrics are being collected for the review app
> Scrape custom metrics

- TeachingRecordSystem/src/TeachingRecordSystem.Api/V2/ApiModels/IttProgrammeType.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/SharedModels/IttProgrammeType.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Models/GeneratedOptionSets.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V2/Operations/UpdateTeacherTests.cs
Add new programme types for 24/25 collection
- Primary and secondary undergraduate fee funded
- Primary and secondary postgraduate fee funded
https://trello.com/c/qPDhbjjN/272-add-new-programme-types-for-24-25-collection
> Added two new programme types

- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/FindPersonByLastNameAndDateOfBirth.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240101/Controllers/TeachersController.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Controllers/PersonsController.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Requests/FindPersonRequest.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Responses/FindPersonResponse.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Validators/FindTeachersRequestValidator.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Controllers/PersonsController.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Requests/FindPersonsRequest.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Responses/FindPersonsResponse.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240606/FindPersonByLastNameAndDateOfBirthTests.cs
This adds a skeleton bulk person find endpoint for review.
I've also fixed up the naming of the existing find endpoint and the associated operation.
> Scaffold bulk person find endpoint

- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs
The `MandatoryQualificationInfo` type used by `TestData` is no longer required; we can use the `MandatoryQualification` type instead.
> Remove redundant MQ type on TestData

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/DqtReportingService.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/Services/DqtReporting/DqtReportingServiceTests.cs
We're about to add workforce data to the DQT reporting DB. We occasionally truncate data in those tables so we need to support that in the sync too.
Annoyingly some of the tests around this are still timing out on CI (so they're skipped) but they are working locally for me. Given that this is temporary I'm not too concerned about fixing them.
> Handle deletes and truncates in TRS tables

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/BackfillDqtReportingPersons.cs
Somehow we're getting errors in the back-fill job that puts `person` records in the DQT reporting DB due to duplicates on the `person_id` primary key. This change keeps track of all the `person_id`s we've seen and skips adding the row if we've already seen it. I've also added a `truncate` to the start of the job so we always start with a blank slate.
> Work around duplicate person records in job

- .github/workflows/pr.yml
- Makefile
https://github.com/DFE-Digital/teaching-record-system/actions/runs/10887241105/job/30209263140
Install terrafile
Delete bin/terrafile
Run make dev terraform-plan
> [2044] Fix terrafile issue

- .github/workflows/backup-db.yml
- .github/workflows/deploy-preprod.yml
- .github/workflows/deploy-prod.yml
- .github/workflows/postgres-ptr.yml
- .github/workflows/postgres-restore.yml
Add workflows for disaster recovery situations
- Refactor the backup workflow to use the standard github action
- Add Point in time restore workflow
- Add restore from storage workflow
Code review. Workflows must be merged to main to be able to test the workflow dispatch trigger
> [2031] Workflows for database backup/restore

- .github/workflows/backup-db.yml
Invalid syntax
Fix indentation
Code review
> Fix backup-db workflow

- .github/workflows/backup-db.yml
- .github/workflows/postgres-restore.yml
The workflow failed
- Fix syntax
- Rename SERVICE_NAME to SERVICE_SHORT for consistency
https://github.com/DFE-Digital/teaching-record-system/actions/runs/10940247738
https://github.com/DFE-Digital/teaching-record-system/actions/runs/10940481178
> DB workflow fixes

- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/FindPersonByLastNameAndDateOfBirth.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/FindPersonsByTrnAndDateOfBirth.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/GetPerson.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/SharedModels/Alert.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240920/ApiModels/Alert.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240920/FindPersonByLastNameAndDateOfBirthTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240920/FindPersonsByTrnAndDateOfBirthTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240920/GetPersonByTrnTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240920/GetPersonTests.cs
This was missed when adding the new API version.
> Add Details property to Alerts on latest API

- terraform/aks/config/pre-production.tfvars.json
> Increase memory for pre-prod worker

- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs
Currently when we add an MQ or Alert in `TestData.CreatePerson()` we create each in its own transaction. This moves everything to use a single `DbContext` and it reduces the roundtrips by batching by model type.
This also re-queries the added data so that we get navigation properties loaded.
> Batch MQ and Alert creation in TestData

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/AlertDeletedEvent.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Filters/CheckAlertExistsFilter.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/JourneyNames.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/DeleteAlert/Confirm.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/DeleteAlert/Confirm.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/DeleteAlert/DeleteAlertState.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/DeleteAlert/Index.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/DeleteAlert/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Program.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/AlertTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PageExtensions.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/DeleteAlert/ConfirmTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/DeleteAlert/IndexTests.cs
Implemented Delete an alert journey based on Figma designs + tests.
> Implemented delete alert journey in TRS Console

- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/AlertMapping.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/TrsDbContextModelSnapshot.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Alert.cs
Also fixes up the EF snapshot.
> Rename Alert.IsActive to Alert.IsOpen

- TeachingRecordSystem/src/TeachingRecordSystem.Api/Infrastructure/Mapping/OptionMapper.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/Program.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240920/Controllers/PersonsController.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240920/Responses/GetPersonResponse.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240920/GetPersonByTrnTests.cs
This allows API users with the `AppropriateBody` role to access ITT, but only the provider.
> Expose ITT provider for the AppropriateBody role

- .github/workflows/backup-db.yml
- .github/workflows/postgres-ptr.yml
- .github/workflows/postgres-restore.yml
Need to update service workflows after updates to related github-actions
hhttps://trello.com/c/JPtELArk/2082-template-github-action-workflows
Updates to DR workflows, backup db, restores
to be merged **after** github-actions pr is merged
Run against updated github-actions branch using the test env
- backup: https://github.com/DFE-Digital/teaching-record-system/actions/runs/11330526295
- ptr: https://github.com/DFE-Digital/teaching-record-system/actions/runs/11330846342
- ptr backup: https://github.com/DFE-Digital/teaching-record-system/actions/runs/11331012600
> Update workflows with github-actions changes

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/PooledOrganizationService.cs
The connection pooling change has eliminated the network connection errors we were seeing under load but we now have a few `CommunicationException`s in their place. This adds a basic retry for when we see such errors.
> Retry request on CommunicationExceptions

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/AddAlertState.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/Details.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/Details.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/Reason.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/AddAlert/Reason.cshtml.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/AddAlert/CheckAnswersTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/AddAlert/DetailsTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/AddAlert/ReasonTests.cs
Also renames `HaveAdditionalReasonDetail` to `HasAdditionalReasonDetail`.
> Add length validation to Add Alert journey

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/Migrations/0032_AddMissingProgrammeTypes.sql
- TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
Add Missing programme types to reporting db
- Primary and secondary postgraduate fee funded
- Primary and secondary undergraduate fee funded
> Add missing programme types to reporting db

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Alerts.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Alerts.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Index.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Index.cshtml.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/AlertsTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/IndexTests.cs
The 'TRA' link in one of the banners will follow later.
> Add alert notification banners

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/MyRoles.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/MyRoles.cshtml.cs
Also adds a 'Reset' button to restore roles to what's stored in the DB.
> Don't allow non-admins to become admins

- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Alert.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/JourneyNames.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/CloseAlert/CheckAnswers.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Details/AlertChangeDetailsReasonOption.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Details/CheckAnswers.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Details/CheckAnswers.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Details/Conventions.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Details/EditAlertDetailsState.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Details/Index.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Details/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Details/Reason.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Details/Reason.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/Link/CheckAnswers.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/EditAlert/StartDate/CheckAnswers.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Alerts/ReopenAlert/CheckAnswers.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/AlertTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PageExtensions.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/AddAlert/TypeTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/Details/CheckAnswersTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/Details/IndexTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/Details/ReasonTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Alerts/EditAlert/Link/IndexTests.cs
Build out the TRS console as per the attached Figma designs (similar to Edit an alert start date), ensuring that an AlertUpdatedEvent is created with the original and changed details.
> Implemented Edit alert details journey + tests

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_Layout.cshtml
> Remove the crown from Support UI footer

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/AddUser/Confirm.cshtml.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/AddUser/ConfirmTests.cs
Users without any roles is totally valid.
> Allow creating users with no roles

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Alerts.cshtml
Tweaked width of closed alerts columns to allow d MMMM yyyy format in table
> Tweaked width of closed alerts columns to fit dd MMMM yyyy format

- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/WebhookEndpointMapping.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/WebhookMessageMapping.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241105182201_Webhooks.Designer.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241105182201_Webhooks.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/WebhookEndpoint.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/WebhookMessage.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/TrsDbContext.cs
A spike was done some time ago around webhooks and CloudEvents. We need to productionise this soon so this is the first of the PRs bringing over various useful, and hopefully non-contentious, bits from the initial spike.
> Add DB model types for webhooks

- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/FindPersonByLastNameAndDateOfBirth.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/FindPersonsByTrnAndDateOfBirth.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/GetPerson.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240101/Responses/GetTeacherResponse.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240814/ApiModels/InductionStatusInfo.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Requests/SetInductionStatusRequest.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241112115351_Induction.Designer.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20241112115351_Induction.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Person.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/InductionExemptionReason.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/InductionExemptionReason.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/InductionStatus.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/Migrations/0036_TrsPersonsInduction.sql
- TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
We've got various Induction-related enums all over the place but future changes will sort all that out.
> Add beginnings of Induction data model

- TeachingRecordSystem/src/TeachingRecordSystem.Worker/Program.cs
We need change tracking enabled on the CRM entity for this to work.
> Temporarily disable outbox processing until CRM config is updated

- terraform/aks/config/test.tfvars.json
Enable test application to use big query configuration
Update to terraform variable to enable federation
Run terraform-plan. It should create the google resources.
> Enable big-query config on test env

- terraform/aks/config/pre-production.tfvars.json
Migrate all environments one by one to Google bigquery with workload identity federation
⚠️ This depends on PR https://github.com/DFE-Digital/terraform-modules/pull/132. It must be released to testing first
Enable gcp wif on the preprod environment
Compare with the test environment
Update the SharedConfig secret in the s189t01-trs-pp-inf-kv keyvault: remove the DfeAnalytics key
> [2124] Migrate preprod to GCP WIF

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/FindPotentialDuplicateContactsQuery.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/CreateContactHandler.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/FindPotentialDuplicateContactsHandler.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/CreateContactTests.cs
Fixes `Unknown matched field: 'dfeta_previouslastname'.` error in TRN allocation.
https://dfe-teacher-services.sentry.io/share/issue/9c903827e9d743998082ea2436578696/
> Fix error from unknown matched attribute

- TeachingRecordSystem/src/TeachingRecordSystem.Worker/Program.cs
The required change in CRM has now been deployed to production.
> Restore outbox message processing

- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Core/Operations/GetQtls.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/SetQtlsDateHandler.cs
I noticed `dfeta_qtlsdate` was setup as a local time - this fixes our code to account for that.
> Fix QTLS date handling for BST

- .gitignore
- README.md
While setting up a new machine I noticed some of our developer setup notes are a little stale. This adds a few corrections.
> Update developer setup notes

- docs/trs-technical-architecture-hld.md
fixed tiny render bug in tech arch diagram.
> fixed render bug in mermaid code

- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/V20240101/FindTeachersTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs
Sanctions are now replaced with alerts in TRS.
> Remove sanctions from TestData

- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Person.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.cs
Splitting this out of the induction API PR to unblock other work.
> Add support for specifying induction details in TestData.CreatePerson

- TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Pages/RequestTrn/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/appsettings.Testing.json
- TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/PageTests/RequestTrn/IndexTests.cs
https://trello.com/c/kxyqYugO/593-close-get-a-trn-service-and-provide-link-to-npq-for-those-mop-up-users
> Require a token for accessing Request TRN journey

- README.md
Tech docs README.md is out of date, this is to tidy up after a number of updates to technical diagrams / views and text.
> tidy readme.md

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
`Task.WhenAll()` yields better performance than `Parallel.ForEachAsync` and we're unlikely to ever get near the 20k req/sec Blob Storage limit.
> Read and write audit blobs in parallel

- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/RouteToProfessionalStatusMapping.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250109110513_RoutesToProfessionalStatus.Designer.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250109110513_RoutesToProfessionalStatus.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/RouteToProfessionalStatus.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/TrsDbContext.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/QualificationType.cs
This is the initial cut. Refinements to the `Name`s and some descriptions will follow later.
> Add reference data for routes to professional status

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/EWCWalesImport/EWCWalesImportJob.cs
> Disable job

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
Also make sure we observe the `retry-after` backoff across concurrent requests.
> Limit concurrency on audit queries

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
The induction live sync failed in Prod because it was trying to process an empty array of updated inductions
Amend code to short cricuit and return if there is nothing to process
> Fix to live sync to short circuit if there are no records to update

- .github/workflows/package.yml
We should scan the build image using SNYK
Add a job in the pipeline to run when an image is built.
https://trello.com/c/9tIfEgW1
Check the build log - https://github.com/DFE-Digital/teaching-record-system/actions/runs/12913115270/job/36009574134
> Add snyk image scan

- README.md
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/CheckYourAnswers.cshtml.cs
fix bug - Show upload file link on check your answers page
and updated readme with info on blob storage emulation
> Show upload file link on check your answers page

- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Person.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Induction.cshtml
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/DataStore/Postgres/Models/PersonTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditInduction/EditInductionStatusTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/InductionTests.cs
Re-coding the definition of which records are managed by CPD
And some text changes to induction summary card
https://trello.com/c/QNRd9oP9/762-induction-fix-cpd-managed-induction-details-validation-change
https://trello.com/c/KA57dsU6/753-induction-fix-summary-card
> change the 'managed by cpd' condition 

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/ExemptionReason.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/InductionChangeReason.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/EditInduction/Status.cshtml
https://trello.com/c/75UBOV3f/754-induction-fix-make-the-h1s-larger-across-the-journey
> fix heading size

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/EwcWalesImport/EwcWalesImportJob.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/EwcWalesImport/InductionImporter.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/EwcWalesImport/QtsImporter.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Jobs/EwcWalesImportJobTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Jobs/InductionImporterTests.cs
EWC Wales import Bug fixes
- Trim whitespace from csv columns 
- Prevent updating a induction that already has an end date.
- Rename file (prefix with date & time) when moving to processed folder.
> Bugfixes for ewc job

- .github/workflows/actions/deploy-aks-environment/action.yml
- .github/workflows/backup-db.yml
- .github/workflows/deploy.yml
- .github/workflows/main.yml
- .github/workflows/postgres-ptr.yml
- .github/workflows/postgres-restore.yml
- .github/workflows/pr.yml
Replace azure credentials with OIDC. See [our documentation](https://github.com/DFE-Digital/teacher-services-cloud/blob/main/documentation/onboard-service.md#deploy-via-github-actions).
Modify the workflows to use the secrets pointing at the managed identities instead of secrets.
See successful runs:
- PR deployment: https://github.com/DFE-Digital/teaching-record-system/actions/runs/13033017648
- Manual deployment: https://github.com/DFE-Digital/teaching-record-system/actions/runs/13033990802
- Back up DB: https://github.com/DFE-Digital/teaching-record-system/actions/runs/13032834513
- Restore DB: https://github.com/DFE-Digital/teaching-record-system/actions/runs/13032989600
- Point in time restore: https://github.com/DFE-Digital/teaching-record-system/actions/runs/13034009527
-   [x] …
> [2201] Migrate workflows to OIDC

- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Controllers/PersonsController.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Requests/SetProfessionalStatusRequest.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/ApiRoles.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/ApiSchema/V3/VNext/Dtos/ProfessionalStatusStatus.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/ApiSchema/V3/VNext/Dtos/TrainingAgeSpecialismType.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/ProfessionalStatusMapping.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250131115818_ProfessionalStatusAmends.Designer.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250131115818_ProfessionalStatusAmends.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/ProfessionalStatus.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/TrainingAgeSpecialismType.cs
Also tweaked some model names to align with the API shape.
> Add stub v3 routes API

- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Requests/SetProfessionalStatusRequest.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250131131727_TrainingAgeSpecialism.Designer.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250131131727_TrainingAgeSpecialism.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/ProfessionalStatus.cs
Fix up some training age-related property names.
> Fix training specialism age property names

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/InductionStatus.cs
Having an explicit `Priority` for `InductionStatus`es is a little nicer than having it implied everywhere.
> Add Priority to InductionStatus metadata

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/CpdInductionImporterJob.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs
- terraform/aks/storage.tf
- New Job to set cpd induction.
- Add new container cpd-inductions
https://trello.com/c/fbXQkIlK/811-job-to-import-induction-records-managed-by-cpd
> New Job to ingest cpd inductions

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/EwcWalesImport/EwcWalesQTSFileImportData.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/EwcWalesImport/QtsImporter.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Jobs/EwcWalesImportJobTests.cs
EWC wales job has two filetypes. This is to handle the second one, by using a mapping class to reference to the fields by index.
> Support ewc wales qts second format

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/EwcWalesImport/EwcWalesImportJob.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/EwcWalesImport/QtsImporter.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Jobs/EwcWalesImportJobTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Jobs/QTSImporterTests.cs
- Regs change
- Re-enable ewc job.
https://trello.com/c/PeCC7KP3/1238-improve-ewc-wales-job-logic-for-qts-statuses
> Add changes to ewc wales import to handle regs change

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/FeatureNames.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/Layout.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Qualifications.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Qualifications.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/Index.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/Detail.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/TrsLinkGenerator.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/appsettings.Development.json
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/QualificationsTests.cs
Update homepage to include routes to professional status.
https://trello.com/c/XN63tmcR/824-routes-and-professional-status-front-end-home-page
> Routes & Qualification homepage.

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/ProfessionalStatusStatus.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Qualifications.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/CheckYourAnswers.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/Detail.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/EndDate.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/EndDate.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/TrsLinkGenerator.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/RouteDetailViewModel.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_RouteDetail.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/appsettings.EndToEndTests.json
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/JourneyTests/EditRouteToProfessionalStatusTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PageExtensions.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/RouteToProfessionalStatusPageExtensions.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/DetailTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/EndDateTests.cs
Mostly End to end tests
Plus:
user journey with the back links and continue buttons
saving all the data to the journey state from the details page
moving the ProfessionalStatusStatus file
> Routes e2 e tests

- TeachingRecordSystem/src/TeachingRecordSystem.Api/ApiError.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/SetPii.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Controllers/PersonsController.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/VNext/Requests/SetPiiRequest.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/UpdateContactPiiQuery.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/UpdateContactPiiHandler.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.Tests/V3/VNext/SetPiiTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Dqt.CrmIntegrationTests/QueryTests/UpdateContactPiiTests.cs
New endpoint to set PII data.
https://trello.com/c/WnQdjQhq/884-v3-pii-update-api
> New vnext endpoint to set pii data

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/ProfessionalStatusStatus.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/DegreeType.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/DegreeType.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/EndDate.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/StartDate.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/TrainingProvider.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/TrainingProvider.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/TrsLinkGenerator.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/RouteDetailViewModel.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_RouteDetail.cshtml
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/JourneyTests/EditRouteToProfessionalStatusTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/CheckYourAnswersTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/DegreeTypeTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/DetailTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/EditRouteStateBuilder.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/EndDateTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/StartDateTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/TrainingProviderTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/TestDataHelper.cs
Add the page for editing the training provider
Added the logic for whether to display each field in details and change reason pages
Also some changes to the tests across all the pages 
https://trello.com/c/V9B7rLhi/873-routes-and-professional-status-front-end-edit-journey-training-provider
> Routes - edit training provider

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Qualifications.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/AwardDate.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/Country.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/Country.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/TrsLinkGenerator.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_RouteDetail.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TeachingRecordSystem.SupportUi.csproj
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/JourneyTests/EditRouteToProfessionalStatusTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/RouteToProfessionalStatusPageExtensions.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/CountryTests.cs
Edit country page, plus a big-fix to the qualifications tab when SubjectIds is null
https://trello.com/c/JtS68RdW/903-routes-and-professional-status-front-end-edit-journey-country
> Edit country page

- TeachingRecordSystem/src/TeachingRecordSystem.Core/ReferenceDataCache.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/EditRouteState.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/SubjectSpecialisms.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/SubjectSpecialisms.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/TrsLinkGenerator.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_RouteDetail.cshtml
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/JourneyTests/EditRouteToProfessionalStatusTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PageExtensions.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/RouteToProfessionalStatusPageExtensions.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/EditRouteStateBuilder.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/EndDateTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/SubjectSpecialismsTests.cs
The page to edit subject specialisms
https://trello.com/c/x5G1Jrmr/904-routes-and-professional-status-front-end-edit-journey-subject-specialisms
> Routes edit subject specialisms

- .github/workflows/backup-db.yml
- .github/workflows/postgres-restore.yml
DB Backups need to be taken on the pre-production environment.
Add pre-production environment to the backup and restore workflow
Review the following runs
- Backup for Pre-production - https://github.com/DFE-Digital/teaching-record-system/actions/runs/14170595837
- Restore for Pre-production - https://github.com/DFE-Digital/teaching-record-system/actions/runs/14171065469
> Fix preprod pg

- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/CreateTrnRequest.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250408144738_TrnRequestMetadataTrnToken.Designer.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250408144738_TrnRequestMetadataTrnToken.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/TrnRequestMetadata.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/DataverseAdapter.CreateTeacher.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtOutbox/Handlers/TrnRequestMetadataMessageHandler.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtOutbox/Messages/TrnRequestMetadataMessage.cs
Also populate all `TrnRequestMetadataMessage` properties.
> Add TrnToken to TrnRequestMetadata

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Models/CountryExtensions.cs
Tiny fix to a typo in the country code mapping for routes API
> Fixed incorrect mapping to make XK map to QO (Kosovo)

- TeachingRecordSystem/src/TeachingRecordSystem.Api/appsettings.Testing.json
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/HostFixture.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/TestBase.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/V3/V20240307/CreateTrnRequestTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/V3/V20240606/CreateTrnRequestTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/V3/V20250203/CreateTrnRequestTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/V3/VNext/CreateTrnRequestTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/V3/VNext/GetTrnRequestTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/OperationTestFixture.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/V3/CreateTrnRequestTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreatePerson.cs
Also moves the 'PII update' flag tests into unit tests project.
> Fix tests that are dependent on outbox message processing

- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/CreateTrnRequest.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/V3/CreateTrnRequestTests.cs
If there are multiple matches on DOB and NINO then create a review task.
> Handle multiple matches on DOB and NINO

- TeachingRecordSystem/src/TeachingRecordSystem.Core/ReferenceDataCache.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/JourneyNames.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/AddRouteState.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/CheckYourAnswers.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/CheckYourAnswers.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/Conventions.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/Route.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/Route.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/Status.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/Status.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/TrsLinkGenerator.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/JourneyTests/AddRouteToProfessionalStatusTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/RouteToProfessionalStatusPageExtensions.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/AddRoute/AddRouteStateBuilder.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/AddRoute/RouteTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/EditRoute/StatusTests.cs
The first page of the 'add route' journey
Changes proposed in this pull request
https://trello.com/c/0BfrzOq7/941-routes-and-professional-status-front-end-add-journey-route-type
Guidance to review
The archived Route types don't appear in the DB yet - so there's a migration to do and some tests to un-ignore when that happens.
> start add route journey - add a route type

- TeachingRecordSystem/src/TeachingRecordSystem.Api/Program.cs
fix dependency failure for api trssynchelper (fix for this error - https://ukgovernmentdfe.slack.com/archives/C065S0DA7TP/p1745312750499709).
> Add dqt note attachment service for v3 api fix

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/Country.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/SubjectSpecialisms.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/SubjectSpecialisms.cshtml.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/JourneyTests/AddRouteToProfessionalStatusTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/RouteToProfessionalStatusPageExtensions.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/AddRoute/CountryTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/RoutesToProfessionalStatus/AddRoute/SubjectSpecialismsTests.cs
subject-specialisms page plus:
fix to countries page (not loading countries list as demoed earlier!)
additions to E2E tests through all the pages
https://trello.com/c/DdhYzbUv/1044-routes-and-professional-status-front-end-add-journey-subject-specialisms
> Routes add subjects

- TeachingRecordSystem/src/TeachingRecordSystem.Core/StringExtensions.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/UserPermissionTypes.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/UserRoles.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/AddUser/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/_User.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/wwwroot/Styles/site.scss
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/JourneyTests/LegacyUserTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/JourneyTests/UserTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/PageExtensions.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/AddUser/ConfirmTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/AddUser/IndexTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/EditUserTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/CaptureEventObserver.cs
Following the access permissions redesign we need to update the Edit Users journey to reflect the new designs and functionality.
https://trello.com/c/Vlol9JWT/1042-create-new-edit-a-user-journey
* Adds edit users page
* Fixes styling issues:
* Allows user permissions tables to take up full page width
* Prevents user permission columns to spread too far apart on large screens
* Allows whole role options field to scroll horizontally on mobile view
> New edit user page

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/ApiTrnRequestsSortByOption.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Index.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/SortDirection.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/IndexTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateApiTrnRequestSupportTask.cs
> Add sorting to table of API TRN requests

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/CreateContactQuery.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/Queries/UpdateContactQuery.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/CreateContactHandler.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/QueryHandlers/UpdateContactHandler.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/ApplicationUsers/EditApplicationUser.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_Layout.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/CheckAnswers.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/CheckAnswers.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/Matches.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/Merge.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/ResolveApiTrnRequestState.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ConnectOneLoginUser/Connect.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/AddUser/Confirm.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser/Deactivate.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/EditUser/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Program.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TempData.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/V3/CreateTrnRequestTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/HostFixture.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/Resolve/CheckAnswersTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/Resolve/MatchesTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/Resolve/MergeTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/Resolve/ResolveApiTrnRequestTestBase.cs
This adds the basic version of the check answers page for the resolve API TRN request journey.
There are a few things that will follow in separate PRs:
- moving CRM updates to background jobs;
- creating an event;
- updating the support task with details;
- content fixes.
> API TRN request check answers page

- TeachingRecordSystem/src/TeachingRecordSystem.Core/TrnRequestHelper.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/CheckAnswers.cshtml.cs
Since we can't update the TRS DB and CRM atomically, this pushes the work of updating CRM into a background job (where the enqueuing of that job _is_ atomic with the TRS DB update).
It's not ideal having a lag here from when the user presses the 'Save' button to actually updating CRM but in reality Hangfire jobs are picked up very quickly so it likely won't be an issue. In any case, this lag will be gone soon once Contact data is migrated into TRS.
> Push CRM updates into a Hangfire job

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Qualifications.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/Status.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/Status.cshtml.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/QualificationsTests.cs
Add the logic for setting an exemption to true if there's an implicit exemption
> set exemption for implicit exemption route

- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/AssertEx.Http.cs
When we have flaky API integration tests all we see is an error about the status code not matching. This adds the response body to the error message to aid in diagnosing why the test is flaky.
> Improve failure messages when API response is not as expected

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/BackfillDqtNotesJob.cs
Backfilling notes takes a long time and sometimes times out. When the job restarts, it starts from the beginning again. This PR allows for the job to be restarted from the most recent row created in the notes table.
In the reporting database the oldest annotation was created on 19/03/2014, so i have defaulted it to that when there are no rows the notes table.
> Allow job to run from a starting point for dqt annotations

- TeachingRecordSystem/src/TeachingRecordSystem.Core/NationalInsuranceNumber.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/EditDetails/IndexTests.cs
Allows temporary NINO when editing person details
> Allow temporary NINO when editing person details

- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/IntegrationTransactionMapping.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/IntegrationTransactionRecordMapping.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250604145642_IntegrationTransaction.Designer.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250604145642_IntegrationTransaction.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250612124002_ChangeIntegrationTransactionsType.Designer.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250612124002_ChangeIntegrationTransactionsType.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/IntegrationTransaction.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/IntegrationTransactionRecord.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/TrsDbContext.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/IntegrationTransactionImportStatus.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/IntegrationTransactionInterfaceType.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/IntegrationTransactionRecordStatus.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/IntegrationTransactions/Detail.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/IntegrationTransactions/Detail.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/IntegrationTransactions/Index.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/IntegrationTransactions/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/IntegrationTransactions/IntegrationTransactionSortByOption.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/IntegrationTransactions/IndexTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateIntegrationTransaction.cs
https://trello.com/c/JZo9YMNN/1074-create-the-itr-interfaces-page-ui
Integration transaction page.
> Integration transaction page

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/ChangeReason.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/CheckYourAnswers.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/CheckYourAnswers.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/ChangeReason.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/CheckYourAnswers.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/EditRoute/CheckYourAnswers.cshtml.cs
file upload fix and add change reason details onto cya page for add route
rollout Stuart's bug fix for uploading file evidence on change reasons page
fix the broken link to the uploaded file
add the change reason to the cya page (missed from previous ticket to add change reasons collection)
> file upload fix

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/CheckYourAnswers.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/DeleteRoute/CheckYourAnswers.cshtml
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/JourneyTests/AddRouteToProfessionalStatusTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/JourneyTests/DeleteRouteToProfessionalStatusTests.cs
- rewording of the final buttons that commit the changes on routes
https://trello.com/c/n56edoya/1237-routes-delete-route-button
https://trello.com/c/LMu8xoQx/1227-routes-add-route-button?filter=label:Routes%20and%20Professional%20Statuses
> text on route delete button

- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/IntegrationTransaction.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/IntegrationTransactionRecord.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/TrsDbContext.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/IntegrationTransactionRecordStatus.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/IntegrationTransactions/Detail.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/IntegrationTransactions/Detail.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/IntegrationTransactions/Index.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/IntegrationTransactions/IntegrationTransactionRecordSortByOption.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/IntegrationTransactions/Row.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/IntegrationTransactions/Row.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/IntegrationTransactions/DetailTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/IntegrationTransactions/IndexTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/IntegrationTransactions/RowTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateIntegrationTransaction.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateIntegrationTransactionRecordAsyncAsync.cs
Add integration transaction detail page.
https://trello.com/c/DxeZKjM3/1073-create-the-itr-file-details-and-row-details-pages
> Add integration transaction detail page.

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/Route.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/RoutesToProfessionalStatus/AddRoute/Route.cshtml.cs
There was a bug in selecting the routes.
Also made the details open/closed depending on whether there's a route in the inactive routes selection
> Routes fix route selection

- terraform/aks/app.tf
All applications should use a standard job configuration module
Update the terraform configuration to use standard job configuration module
There should be no change to the current way of working for job.
https://trello.com/c/Khk6s3ZN/2351-migrate-to-jobconfiguration-tf-module
> Use job configuration module

- .github/workflows/pr.yml
- TeachingRecordSystem/.config/dotnet-tools.json
- TeachingRecordSystem/src/TeachingRecordSystem.Api/Program.cs
Makes the test matrix dynamic based on what files have changed in the PR.
> Only test affected projects on PR builds

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Index.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/PersonProfessionalStatusDetailViewModel.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_PersonProfessionalStatusDetail.cshtml
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/IndexTests.cs
* Adds QTLS status to Person details
> Add QTLS status to person details

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/Index.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Users/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Users/UsersTests.cs
https://trello.com/c/DaOq8XOS/1347-bug-changing-pages-on-add-and-manage-users-page-clears-selected-filter
> Retain filters when paging through user search results

- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/SupportTask.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/TrnRequestMetadata.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskData/TrnRequestManualChecksNeededData.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskType.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Infrastructure/Filters/CheckSupportTaskExistsFilter.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/TrnRequestManualChecksNeeded/Index.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/TrnRequestManualChecksNeeded/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/TrnRequestManualChecksNeeded/Resolve/Confirm.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/TrnRequestManualChecksNeeded/Resolve/Confirm.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/TrnRequestManualChecksNeeded/Resolve/Conventions.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/TrnRequestManualChecksNeeded/Resolve/Index.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/TrnRequestManualChecksNeeded/Resolve/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/wwwroot/Styles/site.scss
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/TrnRequestManualChecksNeeded/Resolve/ConfirmTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/TrnRequestManualChecksNeeded/Resolve/IndexTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateApiTrnRequestSupportTask.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateTrnRequestManualChecksNeededSupportTaskAsync.cs
E2E tests will follow when we have the list page that this journey is launched from.
> Add pages to resolve Manual checks needed tasks

- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Person.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/NpqTrnRequestSupportTaskCreatedPersonEvent.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskData/NpqTrnRequestData.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/NpqTrnRequestSupportTaskCreatedPersonEvent.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/NpqTrnRequests/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/NpqTrnRequests/Resolve/CheckAnswers.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/NpqTrnRequests/Resolve/CheckAnswers.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/NpqTrnRequests/Resolve/Merge.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/NpqTrnRequests/Resolve/ResolveNpqTrnRequestPageModel.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/NpqTrnRequests/IndexTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/NpqTrnRequests/Resolve/CheckAnswersTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateNpqTrnRequestSupportTask.cs
UI to process NPQ TRN requests, where matches are identified, but user elects to create a new person record.
https://trello.com/c/BdhzWXNP/1350-build-trn-request-potential-duplicate-journey-create-new-record-path
> Npq trn request create record

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Models/TrnRequestMetadata.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Index.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/NpqTrnRequests/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/NpqTrnRequests/NoMatches/CheckAnswers.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/NpqTrnRequests/NoMatches/CheckAnswers.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/NpqTrnRequests/Resolve/CheckAnswers.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/NpqTrnRequests/Resolve/CheckAnswers.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/NpqTrnRequests/IndexTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/NpqTrnRequests/NoMatches/CheckAnswersTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/NpqTrnRequests/Resolve/CheckAnswersTests.cs
NPQ TRN request with no matching records - create a person record
https://trello.com/c/kTDqcbKo/1352-build-trn-request-no-duplicate-journey
> Npq trn request no matches create

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/TrnRequestManualChecksNeeded/Index.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/TrnRequestManualChecksNeeded/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/TrnRequestManualChecksNeeded/TrnRequestManualChecksNeededSortByOption.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TagHelpers/FilterTagHelpers.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TrsLinkGenerator.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/TrnRequestManualChecksNeeded/IndexTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateApiTrnRequestSupportTask.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateTrnRequestManualChecksNeededSupportTaskAsync.cs
https://trello.com/c/JTG6TFxe/1370-build-further-checks-required-page-in-definite-matches-journey
> Add list of further checks required tasks

- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/CreateTrnRequest.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/TrnRequestMetadataMapping.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/TrsDbContextModelSnapshot.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/TrnRequestMetadata.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/Models/TrnRequestMetadata.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/Matches.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/NpqTrnRequests/Resolve/Matches.cshtml.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/JourneyTests/ApiTrnRequestSupportTaskTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/Resolve/CheckAnswersTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/Resolve/MatchesTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/Resolve/MergeTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/ApiTrnRequests/Resolve/ResolveApiTrnRequestTestBase.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/NpqTrnRequests/Resolve/CheckAnswersTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/NpqTrnRequests/Resolve/MatchesTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/NpqTrnRequests/Resolve/MergeTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/NpqTrnRequests/ResolveNpqTrnRequestTestBase.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateApiTrnRequestSupportTask.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestData.CreateNpqTrnRequestSupportTask.cs
We use 'Person' everywhere else instead of 'Record' in our types.
> Change 'Record' to 'Person' in TrnRequestMetadata types

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/BackfillPersonCreatedByTpsJob.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs
Job to backfill created_by_tps for the following tickets.
https://trello.com/c/NXB1fQJr/1308-create-capita-export-job-for-updated-teachers-to-export-to-blob-storage
https://trello.com/c/7wIHoDSc/1307-create-capita-export-job-for-new-teachers-to-export-to-blob-storage
> Added a job to backfill created_by_tps

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Webhooks/WebhookMessageFactory.cs
This amends webhook message mapping to look for mappers for versions up to the registered version (in the same way the API works) e.g. if an endpoint is registered for version 'V20250804' and we don't have a mapper for 'V20250804' but we have one for 'V20250627' then we use that.
> Handle new webhook versions by applying old version mappers

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/ManualMerge/Matches.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/ManualMerge/Merge.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/ChoosePersonAttributeViewModel.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_ChoosePersonAttribute.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/Matches.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/ApiTrnRequests/Resolve/Merge.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/NpqTrnRequests/Resolve/Matches.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/NpqTrnRequests/Resolve/Merge.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TagHelpers/HighlightTagHelper.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/JourneyTests/ApiTrnRequestSupportTaskTests.cs
Adds a partial that produces the left/right radio button selection where we compare two records and updates the `HighlightTagHelper` so that the highlight can be conditionally shown based on the `highlight` attribute.
> Remove some of the duplication in journeys that merge people

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Events/PersonMigratedEvent.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/CreatePersonMigratedEventsJob.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs
I've opted to do this in SQL in the name of speed.
https://trello.com/c/EcC9xVar/1399-trs-contact-migration-events
> Add a job to create PersonMigratedEvents

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/CapitaExportNewJob.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Jobs/CapitaExportNewJobTests.cs
- Added new export capita new job that exports newly created trns from tra to a storage container
https://trello.com/c/7wIHoDSc/1307-create-capita-export-job-for-new-teachers-to-export-to-blob-storage
> Create capita export job for new teachers

- TeachingRecordSystem/Directory.Packages.props
- TeachingRecordSystem/src/RoutesMapper/packages.lock.json
- TeachingRecordSystem/src/TeachingRecordSystem.Api/TeachingRecordSystem.Api.csproj
- TeachingRecordSystem/src/TeachingRecordSystem.Api/packages.lock.json
- TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Infrastructure/Oidc/ApplicationManager.cs
- TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/Program.cs
- TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/TeachingRecordSystem.AuthorizeAccess.csproj
- TeachingRecordSystem/src/TeachingRecordSystem.AuthorizeAccess/packages.lock.json
- TeachingRecordSystem/src/TeachingRecordSystem.Cli/packages.lock.json
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250805100125_OpenIddictUpgrade.Designer.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250805100125_OpenIddictUpgrade.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/User.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/packages.lock.json
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/TeachingRecordSystem.SupportUi.csproj
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/packages.lock.json
- TeachingRecordSystem/src/TeachingRecordSystem.WebCommon/packages.lock.json
- TeachingRecordSystem/src/TeachingRecordSystem.Worker/packages.lock.json
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/Infrastructure/Security/SimpleJwtBearerAuthentication.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/packages.lock.json
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.UnitTests/packages.lock.json
- TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.EndToEndTests/packages.lock.json
- TeachingRecordSystem/tests/TeachingRecordSystem.AuthorizeAccess.Tests/packages.lock.json
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/packages.lock.json
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.EndToEndTests/packages.lock.json
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/packages.lock.json
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/packages.lock.json
- TeachingRecordSystem/tests/TeachingRecordSystem.UiTestCommon/packages.lock.json
- TeachingRecordSystem/tests/TeachingRecordSystem.WebCommon.Tests/packages.lock.json
This has been blocking our update to .NET 9.
> Upgrade OpenIddict

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/CapitaExportAmendJob.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Jobs/CapitaExportAmendJobTests.cs
New capita export job to export amended files.
https://trello.com/c/NXB1fQJr/1308-create-capita-export-job-for-updated-teachers-to-export-to-blob-storage
> Capita export job amend

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskData/ChangeDateOfBirthRequestData.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskData/ChangeNameRequestData.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskData/NpqTrnRequestData.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskData/SupportRequestOutcome.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/NpqTrnRequests/NoMatches/CheckAnswers.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/NpqTrnRequests/Resolve/CheckAnswers.cshtml.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/NpqTrnRequests/NoMatches/CheckAnswersTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/NpqTrnRequests/Resolve/CheckAnswersTests.cs
Record support task outcome - resolved - for NPQ TRN requests that are resolved.
renames ChangeRequestOutcome to SupportRequestOutcome
> Npq trn requests support task outcome

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Webhooks/WebhookDeliveryService.cs
We want to see persistent webhook message delivery failures in Sentry, which means we have to log the failures as Errors.
> Log webhook message delivery failures as errors after 5 attempts

- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/Implementation/Operations/FindPersonByLastNameAndDateOfBirth.cs
In future we could look at adding a `previous_last_names` array on `persons` to make this quicker still.
> Fix slow query on Find endpoint

- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250815095614_PersonDqtAllowTeacherIdentitySignInWithProhibitions.Designer.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250815095614_PersonDqtAllowTeacherIdentitySignInWithProhibitions.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Person.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/Migrations/0081_TrsPersonsAllowColumns.sql
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
Also add the missing column from previous PR to the reporting DB.
> Sync the 'allow ID sign in with prohibitions' flag from DQT

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/CapitaExportAmendJob.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/CapitaExportNewJob.cs
- Change filename to use gmt date
- fix a bug whereby querying jobmetadata was detached because of using AsNoTracking.
> Remove AsNoTracking

- TeachingRecordSystem/src/TeachingRecordSystem.Api/RequireContactWritesEnabledAttribute.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240307/Controllers/TrnRequestsController.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20240606/Controllers/TrnRequestsController.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20250203/Controllers/TrnRequestsController.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20250425/Controllers/PersonsController.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20250425/Controllers/TrnRequestsController.cs
https://trello.com/c/GHLWedhS/1448-config-to-disable-contact-write-apis
> Add configuration to block endpoints that write PII

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_Layout.cshtml
Add link to the accessibility statement
> add link to accessibility statement

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Index.cshtml
Fixed rogue character in Index page for change request tile
> Fixed typo in tile markup

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/CreatePersonMigratedEventsJob.cs
Fixes the 'Trn' property in the created events and join should speed up the job too.
> Fix CreatePersonMigratedEventsJob

- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/PersonMapping.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250821121039_AddPersonDateOfDeath.Designer.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250821121039_AddPersonDateOfDeath.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/Person.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/TrsDataSync/TrsDataSyncHelper.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Services/TrsDataSync/TrsDataSyncHelperTests.Person.cs
> Add DateOfDeath to person

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/Migrations/0082_TrsPersonDateOfDeath.sql
- TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
Add date_of_death to reporting db
> Added date_of_death to reporting db

- TeachingRecordSystem/src/TeachingRecordSystem.Api/V1/Handlers/GetTeacherHandler.cs
We've had a few timeouts in Sentry; this optimizes the query.
> Fix V1 Get Teacher API perf

- TeachingRecordSystem/src/TeachingRecordSystem.Worker/Program.cs
We still need this for running some jobs.
> Restore the TrsDataSync CRM services

- TeachingRecordSystem/src/RoutesMapper/packages.lock.json
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Persons/PersonDetail/Timeline/Events/NpqTrnRequestSupportTaskResolvedEvent.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/NpqTrnRequests/Details.cshtml
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/Persons/PersonDetail/ChangeLogNpqTrnRequestSupportTaskUpdatedEventTests.cs
Some small UI changes for the NPQ TRN request change history when a person is updated / created.
https://trello.com/c/QE8lanzx/1451-trn-request-journey-content-design-tweaks
> Npq trn request history

- .github/workflows/main.yml
This environment will be going away shortly as we don't use it.
> Remove test environment from main deployment pipeline

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/ResetIncorrectHasEypsOnPersonsJob.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Files/BlobStorageFileService.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/Files/IFileService.cs
There are number of records which have `hasEyps` on the `Person` incorrectly set to true when they is no EYPS route associated with them.
This job corrects that and creates an event.
> Added job to reset HasEyps flag to false on Person records which don't have an EYPS related route

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/Shared/_Layout.cshtml
https://trello.com/c/o93xnH1T/1507-update-footer-with-the-default-crown-copyright-footer
> Add complete footer component

- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Jobs/EwcWalesImportJobTests.Induction.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Jobs/InductionImporterTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Jobs/QTSImporterTests.cs
Update tests to remove calls to createaccount.
> Remove calls to create account from legacy interfaces

- TeachingRecordSystem/src/TeachingRecordSystem.Core/Dqt/ServiceCollectionExtensions.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/CrmEntityChanges/CrmEntityChangesService.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/CrmEntityChanges/ICrmEntityChangesService.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/DqtReportingService.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/HostApplicationBuilderExtensions.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/TestableCrmEntityChangesService.cs
DQT is still being used for a few reporting things so this needs to come back for a while.
> Resurrect DQT sync to reporting DB

- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/SupportTask.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Models/User.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/CapitaExportAmendJob.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/CapitaImportJob.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Jobs/HostApplicationBuilderExtensions.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/IntegrationTransactionInterfaceType.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskCategory.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskData/CapitaPotentialDuplicateData.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Models/SupportTaskType.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/IntegrationTransactions/Detail.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/TeacherPensions/Index.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/TeacherPensions/Index.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/TeacherPensions/Resolve/Matches.cshtml
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/TeacherPensions/Resolve/Matches.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/TrsLinkGenerator.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Worker/Program.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Core.Tests/Jobs/CapitaImportJobTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.TestCommon/DbHelper.cs
https://trello.com/c/u2BitVLt/1411-create-capita-import-job-to-insert-into-trs
Trs job that imports capita files from a storage container.
Trs job for the capita file import.
> Capita import job

- TeachingRecordSystem/src/TeachingRecordSystem.Api/V3/V20250905/Controllers/TrnsController.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.Api.IntegrationTests/V3/V20250905/GetTrnTests.cs
Also for consistency with what we'll be doing with the other endpoints.
> Return a 410 if record is deactivated instead of 400

- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Mappings/MandatoryQualificationMapping.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250908145910_DqtSpecialismValueLength.Designer.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/DataStore/Postgres/Migrations/20250908145910_DqtSpecialismValueLength.cs
- TeachingRecordSystem/src/TeachingRecordSystem.Core/Services/DqtReporting/Migrations/0084_MqDqtSpecialismValue.sql
- TeachingRecordSystem/src/TeachingRecordSystem.Core/TeachingRecordSystem.Core.csproj
DQT specialism values aren't three digit codes like everything else :-/
> Lengthen DqtSpecialismValue

- TeachingRecordSystem/src/TeachingRecordSystem.Api/Program.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Program.cs
Best reviewed with 'Hide whitespace' enabled.
> Update Program.cs style in API to match other projects

- docs/workforce-data-import/monthly-process.md
Made a few enhancements to the workforce data docs so they aren't just queries in local files to me!
> Updated workforce data import process docs

- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/TeacherPensions/Resolve/Matches.cshtml.cs
- TeachingRecordSystem/src/TeachingRecordSystem.SupportUi/Pages/SupportTasks/TeacherPensions/Resolve/ResolveTeacherPensionsPotentialDuplicateState.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/TeacherPensions/Resolve/CheckAnswersTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/TeacherPensions/Resolve/ConfirmKeepRecordSeparateReasonTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/TeacherPensions/Resolve/KeepRecordSeparateTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/TeacherPensions/Resolve/MatchesTests.cs
- TeachingRecordSystem/tests/TeachingRecordSystem.SupportUi.Tests/PageTests/SupportTasks/TeacherPensions/Resolve/MergeTests.cs
Re-calculate the teacher pensions potential duplicate state on the state of the journey.
> Re-calculate teacher pensions matches state
